### ISSUE TITLE
Load new source files with revise(module)

### ISSUE THREAD

**Issue by gaika** [timholy/Revise.jl#107]
Is it possible to detect and automatically start tracking new files by calling `revise(module)`?

**Comment by timholy** [comment]
If you've created a new package, it should be tracked when you say `using MyModule`. Or do you mean, new file dependencies you've added to an existing project?

**Comment by gaika** [comment]
Yeah, for existing project/module when I add new files with `include`.

**Comment by timholy** [comment]
I haven't forgotten about this request, but I have *so many* packages I need to migrate to 0.7. It will be a while before this gets attention.
