### ISSUE TITLE
MethodError: no method matching parse_expr(..., ::LimeNumberNode, ...)

### ISSUE THREAD

**Issue by rfourquet** [timholy/Revise.jl#109]
This happen when the source file has a `begin ... end` block, here is the error message:
```julia
julia> Revise.track(Test)
ERROR: MethodError: no method matching parse_expr!(::Dict{Module,Revise.ExprsSigs}, ::LineNumberNode, ::Symbol, ::Module)
Closest candidates are:
  parse_expr!(::Dict{Module,Revise.ExprsSigs}, ::Expr, ::Symbol, ::Module) at /home/atma/.julia/dev/Revise/src/parsing.jl:111
Stacktrace:
[...]
```

I found an apparent easy fix, but am not familiar enough with the codebase to be confident in it: replace the first lines of `parse_expr` by:
```julia
  if ex.head == :block
        for a in ex.args
            if !(a isa Expr) # or `a isa LineNumber` to be more conservative, but fails again with e.g. `begin 1 end` 
                continue
            end
            parse_expr!(md, a, file, mod)
        end
        return md
    end
```
I could open a PR, but would need some guidance for how to write a test.

**Comment by timholy** [comment]
Thanks for reporting this! Your fix sounds fine.

Tests are a bit hard; maybe the easiest would be to add a small section to an existing test. I assume in that stacktrace, `parse_source!` is one of the callers? If so, then you could add a `begin...end` block [here](https://github.com/timholy/Revise.jl/blob/0335361d0f921f4cee0c4f71c4495779cd2c8dfc/test/runtests.jl#L57-L60).

**Comment by rfourquet** [comment]
> I assume in that stacktrace, parse_source! is one of the callers? If so, then you could add a begin...end block

Indeed, sorry for not including the stacktrace in the OP. I followed your suggestion, and it's tested correctly in that the tests fail without the fix. [PR](https://github.com/timholy/Revise.jl/pull/110) done :)
