### ISSUE TITLE
Revise.track(Base) gets the wrong paths

### ISSUE THREAD

**Issue by denizyuret** [timholy/Revise.jl#131]
It uses `Base._included_files` which seems to have paths like `/Users/osx/buildbot/slave/package_osx64/build/base/options.jl` which do not match the paths on the actual installation.  I think because of this Rebugger can't show code from Base but I am not sure.

**Comment by timholy** [comment]
I believe this was fixed in #133. Please test!

**Comment by timholy** [comment]
Fixed by a combination of #133, #143, #144, #145
