### ISSUE TITLE
option to track "included files" inside a module

### ISSUE THREAD

**Issue by pawbz** [timholy/Revise.jl#142]
Can we track files that are includes not in REPL, but in module. 
I am testing on v0.7.

```julia
module Mymodule

include("file.jl")

end
```

My `startup.jl` file already has the environment variable `JULIA_REVISE_INCLUDE` to string "1".
```julia
  ENV["JULIA_REVISE_INCLUDE"]="1"
  try
          @eval using Revise
          # Turn on Revise's automatic-evaluation behavior    
          Revise.async_steal_repl_backend()
  catch err
          @warn "Could not load Revise."
  end
```

**Comment by timholy** [comment]
This should already work, and indeed Revise has tests indicating this does work. If it's not working for you, can be you give me a step-by-step complete example of what you're trying: where are your files stored, in what order are you doing things?

In particular, how are you accessing `Mymodule`? You should be doing `using Mymodule` from the REPL. If it doesn't find it, try `push!(LOAD_PATH, "/path/to/my/src/code")` and then `using Mymodule`.

**Comment by pawbz** [comment]
Thank you, this is the complete example: 
* I install `Mysupermodule` package from a github repo.
```julia
Pkg.develop("http://Mysupermodule.git")
```
* Now I navigate to the `dev` folder and have this in `dev/Mysupermodule/Mysupermodule.jl`
```julia
module Mysupermodule
include("Mymodule/Mymodule.jl")
end
```
* Then the contents of `dev/Mysupermodule/Mymodule/Mymodule.jl` are:
```julia
module Mymodule
include("file.jl")
end
```
* I intend to track the `file.jl` and finally in REPL
```julia
using Mysupermodule
Mysupermodule.Mymodule.func()
```

**Comment by timholy** [comment]
Ah, wait, it appears that function changed its behavior relatively recently, and I guess Revise didn't test for this after all. Revise will have to incorporate a slightly modified version into its own code base.

Thanks for reporting this!

**Comment by pawbz** [comment]
I tested in REPL, indeed now Revise works as expected. 

But the changes in `Mymodule` are *not* updated in IJulia, whereas the changes in `Mysupermodule` are correctly picked up by IJulia, thanks to #150

**Comment by timholy** [comment]
Sorry, I just noticed this. I just tested and it works perfectly for me. (It also doesn't make any sense that it should follow one but not the other.) What platform are you on?
