### ISSUE TITLE
UV Error when attempting to watch (too) many files

### ISSUE THREAD

**Issue by samuelpowell** [timholy/Revise.jl#15]
`Revise.jl` is loaded in my `.juliarc.jl`,  then:

```
              _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using GSL

ERROR (unhandled task failure): start_watching (File Monitor): too many open files (EMFILE)
Stacktrace:
 [1] uv_error at ./libuv.jl:68 [inlined]
 [2] start_watching(::FileMonitor) at ./poll.jl:350
 [3] wait(::FileMonitor) at ./poll.jl:428
 [4] watch_file(::String, ::Int64) at ./poll.jl:507
 [5] revise_file_queued(::String) at /Users/spowell/.julia/v0.6/Revise/src/Revise.jl:412
 [6] (::Revise.##1#2)() at ./event.jl:73
```

The error repeats 50+ times.

If the number of watched files cannot be increased, or if this would be undesirable, perhaps an easy way to manage the problem would be to have a whitelist of modules for which tracking is not required?

**Comment by timholy** [comment]
Interesting, on Linux it doesn't complain. But I agree that GSL has a *lot* of files and there seems little point watching them all.

**Comment by Keno** [comment]
You could probably watch the entire package directory. Not sure we expose it in Base, but UV has the UV_FS_EVENT_RECURSIVE to recursively watch all files in a directory.\

**Comment by cstjean** [comment]
I encountered the same with `using Revise, OrdinaryDiffEq`, on OSX. It's also a package with lots of files.

**Comment by timholy** [comment]
http://docs.libuv.org/en/v1.x/fs_event.html suggests that RECURSIVE isn't supported on Linux.

But indeed it looks like it suffices to watch the parent directory, although we'll have to then use `readdir` and `mtime` to figure out which file has been recently modified. I'm pretty swamped ATM, but I'll try to get to this.

**Comment by timholy** [comment]
Let's move any further discussion of this (important) topic to #22.
