### ISSUE TITLE
Make Revise.track(Base) fast for everyone

### ISSUE THREAD

**Issue by timholy** [timholy/Revise.jl#168]
With Rebugger, presumably it's now much more common for people to trigger `Revise.track(Base)` simply by stepping into Base methods. Consequently, it's become a major negative to have `Revise.track(Base)` be slow. On my machine it's not too bad:
```julia
julia> @time Revise.track(Base); @time revise()
  0.335863 seconds (761.32 k allocations: 38.150 MiB, 2.98% gc time)
  0.942074 seconds (955.82 k allocations: 43.453 MiB, 1.04% gc time)
```
However, https://github.com/timholy/Revise.jl/issues/161#issuecomment-414616409 reported times on the order of ~15s, which really isn't acceptable.

The timing will be greatly affected by the amount of work that needs to be done, and this comes down to the `mtime` criterion. On my machine, I happen to have one file (`"InteractiveUtils.jl"`) that I must have touched at some point after building Julia:
```julia
julia> rlogger = Revise.debug_logger()
Revise.ReviseLogger(Revise.LogRecord[], Debug)

julia> Revise.track(Base)

julia> filter(r->r.group == "Watching", rlogger.logs)
1-element Array{Revise.LogRecord,1}:
 Revise.LogRecord(Debug, Recipe for Base, Watching, Revise_61343d83, "/home/tim/.julia/dev/Revise/src/recipes.jl", 26, (filename=/home/tim/src/julia-1.0/usr/share/julia/stdlib/v1.0/InteractiveUtils/src/InteractiveUtils.jl, mtime=1.5344475727586915e9, mtimeref=1.5337688806937075e9))
```
My current working hypothesis is that it's fairly fast on my machine because it only needs to examine one file, and that it's slow on some other machines because they must have many more files that trigger the `mtime` criterion.

If I had to guess, I suspect a major division might be between people who build from source and people who download binaries:

- if you build from source, you first have the files sitting on your hard drive and then you build julia. Consequently the build times in `base.cache` should be newer than the `mtime` on the file.
- if you download a binary, the build time in `base.cache` is from the buildbot, and the `mtime` for the files corresponds to the time Julia was downloaded and installed on the user's machine. Hence every file in Base has a fresher `mtime` which forces parsing by Revise.

There's just one hitch with that theory: if I download a binary on Linux, it's really fast:
```julia
julia> @time Revise.track(Base); @time revise()
  0.206909 seconds (734.45 k allocations: 36.860 MiB, 2.92% gc time)
  0.030500 seconds (21.35 k allocations: 1022.261 KiB)
```
So this theory requires an additional element: perhaps on Linux systems, the `mtime` is preserved in the download. Indeed:
```sh
tim@diva:~/bin/julia-1.0.0/share/julia/base$ ls -l
total 2120
-rw-r--r-- 1 tim holy 67233 Aug  8 20:27 abstractarray.jl
-rw-r--r-- 1 tim holy 10068 Aug  8 20:27 abstractarraymath.jl
...
```
which was the date of Julia's release (and I downloaded the binary weeks later).
However, perhaps on Windows systems that's not true?

Anyone want to test? (@pfitzseb?) This is a useful patch:

```diff
diff --git a/src/recipes.jl b/src/recipes.jl
index 53d53e4..9c15552 100644
--- a/src/recipes.jl
+++ b/src/recipes.jl
@@ -21,6 +21,7 @@ function track(mod::Module)
             filename = fixpath(filename)
             push!(fileinfos, filename=>FileInfo(submod, basesrccache))
             push!(files, filename)
+            @show filename mtime(filename)-mtcache
             if mtime(filename) > mtcache
                 with_logger(_debug_logger) do
                     @debug "Recipe for Base" _group="Watching" filename=filename mtime=mtime(filename) mtimeref=mtcache
```
Any time difference that shows as positive will trigger parsing.

If this guess is correct (and it may not be), I see two potential paths forward:

- modify Julia so that `base.cache` also includes an MD5SUM or similar. Presumably this would be much faster to compute. Obviously this can't happen overnight (1.x feature?)
- write a file `Revise/deps/base.mtimes` that records an updated `mtime`, perhaps the most recent time at which the diff was computed and no difference was found.

While the latter feels more "hacky," it doesn't require modifications to Julia and would probably be even faster. So I find myself tempted by the latter.

**Comment by pfitzseb** [comment]
Turns out `mtime` is preserved correctly on Windows as well, but seems to be off by either `4` or `10` seconds in some (many) cases.

With
```diff
diff --git a/src/recipes.jl b/src/recipes.jl
index 53d53e4..a0775d5 100644
--- a/src/recipes.jl
+++ b/src/recipes.jl
@@ -21,7 +21,7 @@ function track(mod::Module)
             filename = fixpath(filename)
             push!(fileinfos, filename=>FileInfo(submod, basesrccache))
             push!(files, filename)
-            if mtime(filename) > mtcache
+            if mtime(filename) > mtcache + 11
                 with_logger(_debug_logger) do
                     @debug "Recipe for Base" _group="Watching" filename=filename mtime=mtime(filename) mtimeref=mtcache
                 end
```
I get
```
julia> @time Revise.track(Base); @time revise()
  0.202008 seconds (778.51 k allocations: 39.182 MiB, 6.52% gc time)
  0.026933 seconds (21.35 k allocations: 1022.042 KiB)
```
which is very close to your timings. Indeed that makes sure no files are being parsed at all:
```
julia> rlogger = Revise.debug_logger()
Revise.ReviseLogger(Revise.LogRecord[], Debug)

julia> Revise.track(Base)

julia> filter(r->r.group == "Watching", rlogger.logs)
0-element Array{Revise.LogRecord,1}
```

**Comment by timholy** [comment]
Great, glad we understand the issue!

As I'm sure you understand, I'm a little reluctant to add an across-the-board 11 second bonus, since that would mean that anyone who edited a file within seconds after building wouldn't see those changes take effect. I can imagine several ways of fixing this on Revise's end, but they may all have the negative of needing at least one slow parsing of Base before setting things up so that future uses are fast. I worry that a negative experience on the first one might turn people off.

The fact that we're so close makes me wonder: is this something that we can fix on the build-bot side? Like, maybe on Windows the binary is built in an order where the files are copies after `base.cache` is written, and if we just swapped the order then everything would be fine?

Of course there still may be people for whom this won't suffice (e.g., what if you copy your julia installation from one directory to another?), so we may need to have some additional mechanism in place in Revise. But making it work well by default for the vast majority of users seems like a good first start.

**Comment by timholy** [comment]
Are there any obvious patterns to the list of files that have that 4 or 10s mismatch?

**Comment by timholy** [comment]
Actually, here's another question: when you download a binary build, are the source files read-only, by any chance? If so, perhaps we could use `iswritable` as a simple heuristic.

**Comment by pfitzseb** [comment]
> As I'm sure you understand, I'm a little reluctant to add an across-the-board 11 second bonus, since that would mean that anyone who edited a file within seconds after building wouldn't see those changes take effect.

Yeah that definitely isn't a good solution :)

> The fact that we're so close makes me wonder: is this something that we can fix on the build-bot side? Like, maybe on Windows the binary is built in an order where the files are copies after base.cache is written, and if we just swapped the order then everything would be fine?

Might make sense to just `touch` the cache after everything's done building and copying and whatnot?

> Are there any obvious patterns to the list of files that have that 4 or 10s mismatch?

Not really. Most are in `stdlib`, but definitely not all of them. There are also a couple of files with a 2s mismatch which I didn't see earlier.

> Actually, here's another question: when you download a binary build, are the source files read-only, by any chance? If so, perhaps we could use iswritable as a simple heuristic.

No, they aren't.

**Comment by pfitzseb** [comment]
What do you think of only introducing that 10s offset for binary builds? Those are trivial to identify by their different directory structure, and the concern about recently modified files doesn't really apply for those anyways.

**Comment by timholy** [comment]
> Might make sense to just touch the cache after everything's done building and copying and whatnot?

The issue is that the `mtime` is written into the `base.cache` file on a per-file basis. But now that you mention it, really that doesn't sound important: we could use the `mtime` of the file itself as a proxy for the whole thing.

> Actually, what do you think of only introducing that 10s offset for binary builds?

You're absolutely right. PR coming.

**Comment by timholy** [comment]
#170
