### ISSUE TITLE
standardize location printing

### ISSUE THREAD

**Issue by tpapp** [timholy/Revise.jl#179]
In [julia-repl](https://github.com/tpapp/julia-repl/blob/b63255d0771a007050f10a969d85832c4fe6e636/julia-repl.el#L79), I have a regex that matches file locations from Julia when giving warnings/errors. This makes them "clickable", so that a mouse click takes the user to the precise location.

I wonder if you could standardize the way this is printed across the package. My favorite format would be
```julia
at /tmp/Foo.jl:2
```
(since that is used by `Base`, and occasionally Revise.jl) but I am fine with 
```julia
/tmp/Foo.jl near line 2
```
or similar.

I am talking about these: [in `parse_source`](https://github.com/timholy/Revise.jl/blob/c8818b596db3997418ef1cc1b417a26f93a8a66e/src/parsing.jl#L55), and there was (is?) and example in the first format above I cannot find the location for. Perhaps having a function that makes up the file+line number string would be helpful.

**Comment by timholy** [comment]
I'm not sure I fully understand the request. Are you saying that you'd like the format printed from that error in `parse_source!` to be `at /tmp/Foo.jl:2`?

**Comment by tpapp** [comment]
1. I would like **all** potential output (warnings, errors, etc) to the console from Revise.jl that contains location information to be in a **single format** that I can match with a regex,

2. I don't have a strong preference for the format, but `/tmp/Foo.jl:2` would be nice. Ideally, some word preceding it, eg `at /tmp/Foo.jl:2` avoids false matches, but that's not a huge issue.

If `parse_source!` is the only function that emits locations, than this would be simple, but I am not sure it is (in the sense that I have not checked throughly).

**Comment by tpapp** [comment]
Just to clarify: I kept accumulating these regexs since Julia v0.6, so some of them may not be used any more (especially with the new logging infrastructure). So if `parse_source!` is now the only thing that emits locations, and it has the given format, I can accommodate this in `julia-repl`.

Cf https://github.com/JuliaLang/julia/pull/27953, which standardized this nicely for `Base`, the [same format](https://github.com/JuliaLang/julia/blob/807ae7166131ee69d6230d1884be4da80b622e61/stdlib/Logging/src/ConsoleLogger.jl#L60) would be fine.

**Comment by timholy** [comment]
#353 has a commit that implements this. I could find only one place from which location info was being printed by Revise. If you find more, please submit a report or PR.

**Comment by tpapp** [comment]
Thank you. I will look at the changes and see if there is anything remaining. I am rather busy at the moment though, so I may not get to it this week. I would appreciate if this issue could be kept open as a reminder.

**Comment by timholy** [comment]
It will close automatically. I *think* everything is done in Revise anyway, I suspect usage will show you if that's not right.
