### ISSUE TITLE
how to `steal_repl_backend` using `atreplinit`

### ISSUE THREAD

**Issue by ExpandingMan** [timholy/Revise.jl#184]
Doing `using Revise` causes latency in scripts that I'm running outside of the repl.  I can call `using Revise` with `atreplinit` and that seems to work fine, however I can't seem to do this with `steal_repl_backend`.  Is there a way to do this?  This seems like a common use case that should get documentation.

On second thought, after having looked into this a bit more it seems like this *may* not even be possible right now?

**Comment by timholy** [comment]
I'm not even fully sure what you're asking. Can you be more explicit about what you're doing and measuring?

Note that #185 just reduced the startup time a bit, but I don't think that's what you're asking about. (?)

**Comment by ExpandingMan** [comment]
Let me put it this way: suppose I want Revise to load when I start Julia but *only* when I'm using the REPL.

If I'm understanding things correctly, you'd have to do
```julia
atreplinit() do repl
    using Revise
end
```
However, once you get into the REPL, you'd still have to do `Revise.steal_repl_backend()` manually.  As far as I can tell you can't do `Revise.steal_repl_backend()` from within `atreplinit()` in a way that works.

It seems to me that the desired default behavior for Revise would be to load automatically, but only with the REPL.

**Comment by timholy** [comment]
Great, thanks for explaining.

It's a good idea to make it conditional on `atreplinit`. I have a (simple) fix for this, but it's waiting on https://github.com/JuliaLang/IJulia.jl/issues/738. (Every platform other than IJulia seems OK.)

**Comment by ExpandingMan** [comment]
Great, thanks.  Care to elaborate on what this fix will involve from the user perspective?  I'm not using IJulia, could I hack it into my `startup.jl` now?

Also once this is implemented, it might be a good idea to make it the default recommendation for the setup in the docs.

**Comment by timholy** [comment]
I just pushed #188 so you don't have to wait. I may not merge it immediately, in hopes of avoiding disruption for IJulia users.

**Comment by ExpandingMan** [comment]
Awesome thanks!
