### ISSUE TITLE
Building on top of Revise.jl

### ISSUE THREAD

**Issue by cstjean** [timholy/Revise.jl#19]
The fact that `using Revise` immediately turns it on is neat from a UX perspective, but doesn't it preclude building any other package on top of Revise? Eg. if I'm interested in `Revise.parse_source`, in my package X,

```julia
module X
using Revise: parse_source
...
end
```

I will accidentally trigger auto-revision behaviour for anyone importing `X`. Is there a way around that?

**Comment by timholy** [comment]
To clarify, which aspect of `parse_source` are you interested in? We could conceivably split part of Revise out into a separate package.

**Comment by cstjean** [comment]
`parse_source` was just an example. What I'm thinking is that, on one hand, Revise.jl is a better, more thoughtful version of ClobberingReload, and I might want to deprecate that package sometimes within the next year, and work with Revise.jl instead. On the other hand, I've recently started building a tracing module, which allows me to write `@trace Gadfly plot(x=[1,2,3], y=[1,2,3])` and get a trace of the functions called. It works by parsing the module's source, then for each function, `eval` a new "tracing" version in that module. It was natural to build it on top of ClobberingReload, but I couldn't do the same with Revise in its current form. 

> We could conceivably split part of Revise out into a separate package.

That could work. I don't have an immediate need - just wanted to start thinking about the future.

**Comment by timholy** [comment]
Sounds good. For tracing, have you looked at [Cassette.jl](https://github.com/jrevels/Cassette.jl)? CC @jrevels.

**Comment by cstjean** [comment]
I did, and I hope it works out, because it would be a lot cleaner than what I'm doing, but AFAIK it requires changes to Base, so it's 0.7 material.

**Comment by jrevels** [comment]
Yeah, Cassette is still an experiment at this phase and will require a couple of different compiler/Base reflection improvements before it's tenable (mainly to support nested tracing and make it 265-robust). My personal target is to have usable initial release by 1.0.
