### ISSUE TITLE
Not updating for a running task?

### ISSUE THREAD

**Issue by yadongli** [timholy/Revise.jl#193]
First, Revise.jl is a great tool that greatly improved my workflow. I'm running into a problem that a running task is not seeing the update if edits are made after the task is started.

The following example is using IJulia and Julia version 0.6.3, here the "simplerepr" is a method defined in another module.

function server(d)
    while true
        sleep(3.)
        println(simplerepr(d))
    end
    d
end

@schedule server("from running task: ")

after editing the simplerepr definition, the IJulia interactive session did immediately start using the new version (as expected), but the running task still uses the old version. Is there a way to make a running task to also update automatically?

The following is a sample output when running simplerepr("from console: ") from the same IJulia session after editing the module, the repeated message is from the running task.

"from console:  new version"
from running task:  old version
from running task:  old version
from running task:  old version
...

**Comment by timholy** [comment]
Sorry, but for the foreseeable future it's just not possible to make a running task update its code. If it's a matter of having it update its dependent functions, it seems like there's a small chance that `Base.invokelatest` might help?

**Comment by timholy** [comment]
Since this isn't something that Revise can really do, I'll close this as a `wontfix`.
