### ISSUE TITLE
Usage outside REPL

### ISSUE THREAD

**Issue by geluso** [timholy/Revise.jl#194]
Does Revise only work in the REPL? The docs say "the changes will be incorporated into the very next command you issue from the REPL."

I'm trying to write a program (ultimately drawing to Canvas) where I want the program to execute changes in a file while the program is still running. For instance look at the following.

Is it possible to run `julia Try.jl` which spins in the while loop printing out forever, then editing `Example.jl` and having the main program print out the changed contents?

**Example.jl**
```julia
function hello(str)
  println("Hello ", str)
end
```

**Try.jl**
```julia
using Revise

Revise.includet("./Example.jl")
while true
  hello("world")
  Revise.revise()
end
```

**Comment by timholy** [comment]
Did you try it? There's no cost to try :smile:.

**Comment by timholy** [comment]
Oh, you mean, "can you display the diff"? Yes, but not without editing Revise. If that's all you want to do, you're better off using `FileWatching` and then shelling out to `diff` directly.

**Comment by geluso** [comment]
Yes I've tried it and I absolutely love how Revise works in the REPL. Sorry for the phrasing. I'm not interested in the diff. I mean I want the output of the program to change so it executes new code when I edit the other file.

```
julia Try.jl
Hello world
Hello world
Hello world
Hello world
Hello world
Goodbye world         << edit hello function inside Example.jl and save so it has "println("Goodbye ", str)"
Goodbye world
Goodbye world
^C
```

**Comment by timholy** [comment]
Got it. Just change your loop to 
```julia
while true
    Base.invokelatest(hello, "world")
    Revise.revise()
end
```
If you're curious, the issue is one regarding ["world age"](https://docs.julialang.org/en/v1/manual/methods/#Redefining-Methods-1).

**Comment by geluso** [comment]
That works! Thank you and thanks for pointing me toward World Age.
