### ISSUE TITLE
Docstring of submodule is not updated

### ISSUE THREAD

**Issue by tkf** [timholy/Revise.jl#197]
Here is a MWE (run in `julia --startup-file=no`).

```julia
julia> using Revise

julia> Revise.async_steal_repl_backend()

julia> cd(expanduser("~/.julia/dev/Example/"))

julia> write("src/Example.jl", """
       "docstring"
       module Example

           "docstring for .Sub"
           module Sub
           end
       end
       """);

julia> using Example
[ Info: Recompiling stale cache file /home/takafumi/.julia/compiled/v1.0/Example/lLvWP.ji for Example [7876af07-990d-54b4-ab0e-23690620f79a]

julia> @doc Example
  docstring

julia> @doc Example.Sub
  docstring for .Sub

julia> write("src/Example.jl", """
       "updated docstring"
       module Example

           "updated docstring for .Sub"
           module Sub
           end
       end
       """);

julia> @doc Example
  updated docstring

julia> @doc Example.Sub
  docstring for .Sub


julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

julia> using Pkg

julia> Pkg.installed()["Revise"]
v"0.7.11"
```

Note that last `@doc Example.Sub` outputs `docstring for .Sub` while I expect `updated docstring for .Sub`.   The top-level docstring `@doc Example` is updated as I expected.

**Comment by timholy** [comment]
Revise may be able to fix this on its own, but there seem to be some issues updating docstrings for modules, see https://github.com/JuliaLang/julia/issues/29432. See #198.

**Comment by tkf** [comment]
Thanks a lot for looking into the problem!

**Comment by cstjean** [comment]
There's a funny behaviour now: changing the docstring inserts a horizontal line, and appends to the previous docstring:

```julia
help?> TestPkg.Foo
  Hello there 

help?> TestPkg.Foo
  Hello there 

  ────────────────────────────────────────────────────────────────────────────

  Hello there Bob 
```

**Comment by fredrikekre** [comment]
> changing the docstring inserts a horizontal line, and appends to the previous docstring:

Nah, that's just how docstrings are separated in the REPL; there is just two docstrings attached to `TestPkg.Foo`.

**Comment by cstjean** [comment]
Oh, right, that's https://github.com/JuliaLang/julia/issues/29432 which Tim pointed to above.

**Comment by KristofferC** [comment]
Is this fixed via https://github.com/JuliaLang/julia/pull/37626?

**Comment by timholy** [comment]
Looks like it. I took the test from #198 and submitted it as a PR anyway (#543).
