### ISSUE TITLE
`Typeof not defined` when processing a function signature

### ISSUE THREAD

**Issue by rdeits** [timholy/Revise.jl#199]
I'm encountering a strange issue when trying to use Revise to track RigidBodySim.jl. Editing the package is  yielding the following error message: 

```
┌ Warning: error processing module RigidBodySim.Core signature expressions Expr[:(Tuple{Core.Typeof(zero_control!), AbstractVector, Any, Any})] from :(zero_control!(τ::AbstractVector, t, state) = begin
│           τ .= 0
│       end)
└ @ Revise ~/.julia/packages/Revise/xO23U/src/exprutils.jl:94
ERROR: UndefVarError: Typeof not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
```

The method being referred to is defined here: https://github.com/JuliaRobotics/RigidBodySim.jl/blob/bf94b7e011262aebe7a15d624f4bbb38c0120afb/src/core.jl#L45

but I actually see the error after editing a different method, here: https://github.com/JuliaRobotics/RigidBodySim.jl/blob/bf94b7e011262aebe7a15d624f4bbb38c0120afb/src/core.jl#L74-L86

You should be able to reproduce my exact setup (on Julia 1.0.0) from this manifest and project file: https://gist.github.com/rdeits/ac843f6c10e0058d951f63ccb2ffd00b (hooray for the bold new Pkg3 future!). I can reliably trigger the issue by doing the following: 

```julia
julia> activate .

julia> using Revise

julia> using RigidBodySim

# Now make a trivial edit to RigidBodySim/src/core.jl, for example adding a new 
# statement to the function defined here: 
# https://github.com/JuliaRobotics/RigidBodySim.jl/blob/bf94b7e011262aebe7a15d624f4bbb38c0120afb/src/core.jl#L74-L86

# Then execute another top-level statement to trigger Revise:

julia> nothing
┌ Warning: error processing module RigidBodySim.Core signature expressions Expr[:(Tuple{Core.Typeof(zero_control!), AbstractVector, Any, Any})] from :(zero_control!(τ::AbstractVector, t, state) = begin
│           τ .= 0
│       end)
└ @ Revise ~/.julia/packages/Revise/xO23U/src/exprutils.jl:94
ERROR: UndefVarError: Typeof not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
```

Would it be helpful for me to also capture a Revise log?

**Comment by timholy** [comment]
Amusing! Happens because RigidBodySim has a module called `Core`, and Revise tried to evaluate an expression `Core.Typeof` inside `RigidBodySim`. Fixed by #200.

Sorry for the inconvenience.
