### ISSUE TITLE
entr-like functionality?

### ISSUE THREAD

**Issue by mlhetland** [timholy/Revise.jl#203]
A (hopefully small) feature request…

For quite some time, I've been using [`entr`](http://www.entrproject.org) as part of my coding workflow. For example, I have code generating TeX code, which is then compiled by `latexmk`, so all I do is save, and the PDF is updated. Or I use `entr` to run my tests, for example. Needless to say, for Julia, this can (with current compile times) sometimes lead to a bit of waiting. `Revise` would be ideal to cut down on that wait time, and I thought about setting up some wrapper/connection between a process (e.g., REPL) running with `Revise` and `entr` monitoring files, calling the appropriate code if something changes.

But … `Revise` is *already* monitoring files, of course, so this would probably be a huge waste! In general, I guess it's even monitoring the *right* files. So I guess my request boils down to the two following features, in order of descending priority:

1. **Registering a callback** or delegate, or some similar mechanism, to trigger specified user code after revision (à la `entr`); and
2. **Tracking non-Julia files** (e.g., in one of my use-cases, TeX-related files that are read and used as string constants at compile-time).

As the current version already uses strings for `track`, dispatch would be a bit of work there, but it could perhaps just be a keyword flag? E.g., have `julia=true` or something as the default?

**Comment by timholy** [comment]
See #93 and #103. This is the third request for this functionality (CC @essenciary and @yurivish), so I don't doubt this would be useful. But no one has ever tested it and reported back if it's useful. I'm not convinced it is all that useful without changing the mode for looking for updates, which is currently dependent upon REPL input.

**Comment by mlhetland** [comment]
Oh, sorry about that! I thought I looked through the issues, but missed these :-O No, I realized that it's not based on file changes. I guess maybe the functionality is a candidate for a separate library/tool, then!

**Comment by mlhetland** [comment]
But, yeah, a callback isn't really useful in itself for me – what I was hoping to avoid was having to go into a REPL or the like and execute something every time the file changes. I guess I'll look into alternatives!

**Comment by mlhetland** [comment]
For future seekers, this seems to do the trick, assuming the code you wish to run is in `main`:
```
julia> using Revise, FileWatching
julia> includet("myfile.jl")
julia> while true
           watch_file("myfile.jl")
           revise()
           main()
           sleep(.1)
       end
```
The `sleep` is to avoid triggering multiple watch events with a single change. (It seems that happens otherwise; there may be a more elegant solution to that, though.)

**Comment by timholy** [comment]
Thanks for posting that. I think the main way that would need to be extended would be to watch a user-specified collection of files, and update if any one of them changes.

**Comment by timholy** [comment]
Reopening since this contains an actionable nugget.

**Comment by mlhetland** [comment]
Agreed – it might be worth looking at what `entr` does, though there isn't much more to it. You give it a list of files, and it executes a command when one of them changes. That's basically it, but it may have some other ideas worth looking into – not sure. For example, it can watch directories, detecting new files; might be useful if you `include` all files in a directory automatically (which I do, in some code). This could be handled with `watch_folder` (which also tracks file changes).

**Comment by mlhetland** [comment]
Maybe something along these lines?
```julia
using FileWatching, Distributed

function watch(func::Function, files)
    @sync for file in files
        waitfor = isdir(file) ? watch_folder : watch_file
        @async while true
            waitfor(file)
            revise()
            func()
        end
    end
end

watch(myfiles) do
    myfunction()
end
```
Files could be supplied using, `Glob.jl` or something, for example.

There's no graceful exit here, of course (could be added). And for some reason, even with the `sleep`, I keep getting two events for files changing (but not directories; and no, I'm not watching the directory containing the changing file xD). I guess we could manually discard duplicates that occur within a certain timespan, rather than `sleep`ing (and just accumulating the dupes).

**Comment by timholy** [comment]
I like this solution. The one thing I wonder about is that the only Revise-specific component is that single call to `revise()` in the loop. So should Revise be "running" this or is Revise just a dependency of this kind of functionality?

**Comment by mlhetland** [comment]
Good question. Maybe we should have something like `Entr.jl`, which could have using Revise as an option, but that could also just run other stuff. In some cases, Revise might not be needed. Then again, with only something like the above, it would be a rather small package :-) Maybe it belongs in FileWatching? I.e., some function in FileWatching for watching a specified collection of files, that takes some callback that could itself call revise, or something? I'm not sure, really. I guess a reason I posted about this here initially was that my mental model of Revise included tracking whether files changed, and then updating based on that – and adding user code to the update cycle seemed close to what I generally do with `entr` (without Revise – therefore usually quite slowly).

From a usability standpoint, it might not be that unreasonable, I guess. E.g., permitting a callback as an optional first argument in `includet`. So you could do:
```julia
includet("myfile.jl") do
    my_custom_update()
end
```
But that only goes for a single file, of course. (Maybe one could include multiple files in a single call?-) So, yeah, I don't know. :-)

I guess my underlying wish was simply being able to replicate something along the lines of the functionality of `entr`, but leveraging Revise in order to avoid recompilation on every change. Exactly which package should be responsible, etc., I don't know.

**Comment by timholy** [comment]
You could propose adding it to FileWatching. Revise wouldn't even have to be a dependency, because you can include the call to `revise` in your thunk:

```julia
using FileWatching, Revise, MyStuff

function thunk()
    revise()
    dostuff()
end

entr(thunk, files)
```

**Comment by mlhetland** [comment]
Yeah, that's what I meant by

> I.e., some function in FileWatching for watching a specified collection of files, that takes some callback that could itself call revise, or something?

I guess that's an option, yeah.

On the other hand, it might be a special case of ”using Julia efficiently from the command-line” via Revise, which I mentioned briefly in the [the same post](https://discourse.julialang.org/t/compiler-work-priorities/17623/51) that referred back to this. If we had a solution to that, then I could just use the actual `entr` :-)

I've been thinking a little bit about this as a thing – say, a “fake” `julia` command that starts a Julia process in the background, if one isn't running, but otherwise uses that – with Revise – to run things. Might get messy quickly, perhaps, but my superficial idea was something like having
```
$ fake-julia script.jl
```
simply include `script.jl` the hidden REPL, or something. Would get a bit scary if you run several different scripts, and they all share the same namespace, though.

Or it could simply be a command-line RPC thing, where
```
$ julia-cli-rpc somefunction x y z
```
would evaluate `somefunction(x, y, z)` in some connected Julia process (again with Revise as an orthogonal piece of functionality). That would also permit the use of things like (say) `entr`.

**Comment by timholy** [comment]
This version:

```julia
using FileWatching, Revise, MyStuff
entr(files) do
    revise()
    dostuff()
end
```

is something you might reasonably pass as a command-string via `julia -e`.

As I think about it more, I think all this is a bit orthogonal to Revise. Consequently I think the solution lies in a different package/stdlib, so I'll close this again.
