### ISSUE TITLE
Is Revise forcing my dev-ed package to precompile each session even when no changes?

### ISSUE THREAD

**Issue by ianshmean** [timholy/Revise.jl#206]
A package I’m `develop`-ing precompiles every time I start a new session irrespective of if any changes took place. I’m using `Revise.jl`, is that perhaps forcing re-precompillation?

(I have also tried to force precompillation off with `__precompile__(false)` which still results in precompillation, which I think might be a known bug)

**Comment by ianshmean** [comment]
This doesn't seem to be caused by Revise so I'm closing it, but I'm not sure how to resolve this issue

**Comment by timholy** [comment]
Only thing I can think of: make sure all your dependencies are declared in `Project.toml` or `REQUIRE` and then make sure you call `pkg> resolve` in your primary environment.

**Comment by timholy** [comment]
Another possibility: does it use a package that declares `__precompile__(false)`?

**Comment by timholy** [comment]
What's your Julia version? I believe this was a bug fixed in 1.0.1 or 1.0.2.

**Comment by ianshmean** [comment]
I see this in both 1.0.2 and 1.1.0-DEV.655 (2018-11-13)

**Comment by timholy** [comment]
Please report as a Julia bug.

**Comment by ianshmean** [comment]
Ok I just commented on https://github.com/JuliaLang/julia/issues/28384
