### ISSUE TITLE
Revise not picking up what module changes comes from

### ISSUE THREAD

**Issue by djsegal** [timholy/Revise.jl#21]
Let's say i have two julia packages:

+ [Julz](https://github.com/djsegal/Julz.jl) — a framework that does stuff like loads files 
+ [Tokamak.jl](https://git.io/tokamak) — a package that uses the Julz framework

I recently added the ability to use revise in Julz // see: https://github.com/djsegal/Julz.jl/commit/34a13020935ddfea2b0c2fc9a5336965a248750e

--------

However, when changing files in Tokamak.jl, 

+ I get a notice that Revise knows it was changed (this is good!)
+ but Revise thinks the function is in the Main module (this is bad!)

This is shown below (see the `WARNING: replacing docs...` line)

```
julia> Tokamak.Q_E()
9.381818181818183

julia> # edit Q_E function

julia> Tokamak.Q_E()
WARNING: replacing docs for 'Q_E :: Tuple{}' in module 'Main'.
9.381818181818183
```

**Comment by djsegal** [comment]
I think this was dumb. You can pass module to track.

// see: https://github.com/timholy/Revise.jl/blob/76e2ce5643e1a35bd4ea680ac5832d76abed7339/src/Revise.jl#L476-L485

**Comment by timholy** [comment]
If you load both packages with `using Julz, Tokamak` it *should* keep them separate, and you shouldn't have to manually call `track`. If that's not what you're finding, do let me know.

**Comment by djsegal** [comment]
@timholy, It's different than that.

`using Tokamak` loads `Julz` // and then Julz calls `include(...)` for `Tokamak`

---

i.e. 
+ Tokamak calls Julz.include_all_files (see Tokamak's [bootload file]((https://github.com/djsegal/Tokamak.jl/blob/master/config/bootload.jl))
+ Include all files in Julz then correctly namespaces the Revise tracking (see [include_all_files.jl](https://github.com/djsegal/Julz.jl/blob/e631438f2b71f6fe233f0250b2c6817b63570be0/src/functions/utils/include_all_files.jl#L40-L47))

**Comment by djsegal** [comment]
Closing this
