### ISSUE TITLE
Using Revise by default with several processes

### ISSUE THREAD

**Issue by MaxandreJ** [timholy/Revise.jl#212]
Hi Tim,

Thank you so much for the great work on this package which has saved me a lot of time for my PhD.

I am using Atom and Juno, Julia v1.0.2 and I'm on MacOS. I tried to adapt your [startup.jl script for using Revise by default](https://timholy.github.io/Revise.jl/stable/config.html#Using-Revise-by-default-1) for when I start julia with several processes, for example with `julia -p 2`. This is the version that I'm using:
```
atreplinit() do repl
    try
        @eval @everywhere using Revise
        @async Revise.wait_steal_repl_backend()
    catch
    end
end
```

Unfortunately this doesn't work, I receive the following errors by Julia Client v 0.7.10:
```
Julia Client – Internal Error
UndefRefError: access to undefined reference
getproperty(::Any, ::Symbol) at sysimg.jl:18
get_main_mode() at repl.jl:10
changeREPLmodule(::String) at repl.jl:187
(::getfield(Atom, Symbol("##153#154")))(::Dict{String,Any}) at repl.jl:35
handlemsg(::String, ::Dict{String,Any}) at comm.jl:164
(::getfield(Atom, Symbol("##19#21")){Array{Any,1}})() at task.jl:259
```
and
```
Julia Client – Internal Error
UndefRefError: access to undefined reference
```
and
```
Julia Client – Internal Error
UndefRefError: access to undefined reference
getproperty(::Any, ::Symbol) at sysimg.jl:18
get_main_mode() at repl.jl:10
changeREPLmodule(::String) at repl.jl:187
(::getfield(Atom, Symbol("##153#154")))(::Dict{String,Any}) at repl.jl:35
handlemsg(::String, ::Dict{String,Any}) at comm.jl:164
(::getfield(Atom, Symbol("##19#21")){Array{Any,1}})() at task.jl:259
```

Any idea how to fix this? I know I can just write `@everywhere using Revise` at the beginning of my script but this using Revise by default script has proven very useful to me! Thank you!

**Comment by timholy** [comment]
Works for me in the REPL. Since the errors are coming from JuliaClient I think you might need to report the bug there (or even better, debug it yourself and contribute the fix).

**Comment by timholy** [comment]
Starting with 2.0 one no longer needs to run Revise on the workers.
