### ISSUE TITLE
Documentation: instructions for first-time user driven by immediate need

### ISSUE THREAD

**Issue by rulatir** [timholy/Revise.jl#225]
Please provide a usage example for the scenario where the file being edited is already open in an IDE, and I *just* need to tell `Revise` to do One Thing (reload the module) instead of Three Things (open configured editor, wait for the editor to terminate, reload the module).

**Comment by timholy** [comment]
I'm not sure which example in the documentation you're describing. The first one?

In general you don't need to tell Revise to do anything; it's automatic.
