### ISSUE TITLE
Tracking Base

### ISSUE THREAD

**Issue by cstjean** [timholy/Revise.jl#23]
I'm tentatively migrating my tracing code to reuse the Revise.jl infrastructure, and so far so good, but I'm not sure how/if the `track(Base)` [code](https://github.com/timholy/Revise.jl/blob/master/src/Revise.jl#L498) works:

```julia
julia> using Revise

julia> empty!(Revise.new_files)
0-element Array{String,1}

julia> mainfile = joinpath(dirname(dirname(JULIA_HOME)), "base", "sysimg.jl")
"/Applications/Julia-0.6.app/Contents/Resources/base/sysimg.jl"

julia> Revise.parse_source(mainfile, Main, dirname(mainfile))
WARNING: omitting /Applications/Julia-0.6.app/Contents/Resources/base/sysimg.jl from revision tracking

julia> Revise.new_files
0-element Array{String,1}

julia> collect(keys(Revise.file2modules))
1-element Array{String,1}:
 "/Users/cedric/.julia/v0.6/Revise/src/Revise.jl"
```

Does it require building Julia from source? On OSX.

**Comment by timholy** [comment]
Probably so. Revise's main purpose is to update for changes to the source code, so it has to have access to the source. That warning is emitted from [here](https://github.com/timholy/Revise.jl/blob/d1918056ab54b1e0540cc5ced2f59539cac915f1/src/Revise.jl#L311).

**Comment by cstjean** [comment]
The location of sysimg for me is `/Applications/Julia-0.6.app/Contents/Resources/julia/share/julia/base/sysimg.jl`, whereas `mainfile` is `/Applications/Julia-0.6.app/Contents/Resources/base/sysimg.jl`. Do you know how to get it in a OS-portable way? `realpath(functionloc(which(Base.include, (AbstractString,)))[1])` works, but it's not the cleanest code.

**Comment by timholy** [comment]
Does this work for you?
```julia
julia> mainfile = joinpath(dirname(dirname(JULIA_HOME)), "usr", "share", "julia", "base", "sysimg.jl")
"/home/tim/src/julia-0.6/usr/share/julia/base/sysimg.jl"

julia> isfile(mainfile)
true
```
(It's the path you gave, with 1 of the `julia`s replaced with `usr`.)

**Comment by cstjean** [comment]
`isfile(mainfile)` is false, sorry.

**Comment by cstjean** [comment]
The code used in [Base.find_source_file](https://github.com/JuliaLang/julia/blob/903644385b91ed8d95e5e3a5716c089dd1f1b08a/base/loading.jl#L132) is `joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "base", "sysimg.jl")`. I'll make a PR.
