### ISSUE TITLE
1 and 1.0 are treated as identical

### ISSUE THREAD

**Issue by cstjean** [timholy/Revise.jl#233]
I'm on Revise v.0.7.14, and if I have a method `f() = 1.0`, which I evaluate and then change to `f() = 1`, Revise fails to update the definition. `f()` still returns `1.0`

**Comment by timholy** [comment]
That's a really cute bug! :bug: 

With only a couple of moment's thought, I'd say it's also really difficult to do anything about:
```julia
julia> hash(1.0)
0x02011ce34bce797f

julia> hash(1)
0x02011ce34bce797f

julia> isequal(1, 1.0)
true
```

**Comment by timholy** [comment]
Good idea, but won't work here: this is used in the part of Revise that is like `diff`. You parse a new version of a file and see if the expressions you get out are the same as the old expressions. But parsing the same thing results in non-id expressions:

```julia
julia> ex1 = Expr(:call, :foo)
:(foo())

julia> ex2 = Expr(:call, :foo)
:(foo())

julia> objectid(ex1)
0xf3bed2781e03ce8c

julia> objectid(ex2)
0xf441bd2316754636
```

Now that I think about it, though, I think this *is* pretty easily fixable without committing type piracy: this package defines a `LineSkippingIterator` type whose purpose is to allow hashing and identity between expressions to be defined without worrying about differences in line numbers. So I (or anyone else :wink:) can just modify [these methods](https://github.com/timholy/Revise.jl/blob/97d3560783176c6ec32b9e660aee51a8e333c455/src/relocatable_exprs.jl#L123-L162) to check for numbers and require type-equality as well as value-equality (and incorporate the type as well as the value into the hash).
