### ISSUE TITLE
Functions used for default arguments not tracked

### ISSUE THREAD

**Issue by heliosdrm** [timholy/Revise.jl#235]
This is a minimal reproducible example of what happened:

I initially have two files in `MyModule` (as a package in `dev`):

1. `MyModule.jl`:
```julia
module MyModule

export foo
include("function.jl")

end
```

2. `function.jl`:
```julia
function foo(a::Number; b::Integer=1)
    a^b
end
```

Then I want to make the keyword argument `b` conditional to the type of the number `a`. So I add a third file, `parameters.jl`:

```julia
defb(a::Integer) = 1
defb(a::Float64) = 2
``` 

And modify `MyModule.jl` and `function.jl` accordingly:
1. `MyModule.jl`:
```julia
module MyModule

export foo
include("parameters.jl")
include("function.jl")

end
```

2. `function.jl`:
```julia
function foo(a::Number; b::Integer=defb(a))
    a^b
end
```

But Revise fails to track this:
```
julia> using Revise

julia> using MyModule
[ Info: Recompiling stale cache file /home/meliana/.julia/compiled/v1.0/MyModule/hdvNC.ji for MyModule [4a1d5045-ac3d-5255-9357-cf6dd8f99e68]

julia> foo(8.0) # Before the change
8.0

julia> foo(8.0) # After the change
ERROR: UndefVarError: defb not defined
Stacktrace:
 [1] foo(::Int64) at /home/meliana/.julia/dev/MyModule/src/function.jl:2
 [2] top-level scope at none:0
```

**Comment by timholy** [comment]
If you put them in the same file `function.jl`, does it work? If so, this is redundant with #107.

**Comment by heliosdrm** [comment]
Ok, it seemed the problem of the file `parameters.jl`not having been included before at the time of `using MyModule`, thanks.
