### ISSUE TITLE
Compatibility with Requires.jl

### ISSUE THREAD

**Issue by Djoop** [timholy/Revise.jl#244]
Hi, I noticed that Revise does not track changes to code loaded by Requires.jl. This would be code defined as follows:
```
module MyModule
…
include("somecode.jl")    # This code is revised as expected
function __init__()
    @require SomeOptionalPackage="…" begin
        include("optional_code.jl")     # This code is not tracked by Revise
    end
end
end
```
I understand that the code being defined inside a macro inside `__init__`, this must be much more tricky, but still I'm not sure to properly understand:
- would that be technically possible, or is it known to be a limitation?
- If it is not possible, is there a way to reload the code manually without restarting julia? I tried `revise(MyModule)` as suggested on the "Limitations" page of the doc, but it does not work.

**Comment by timholy** [comment]
As a workaround you can manually do `Revise.track(MyModule, "optional_code.jl")`.

**Comment by Djoop** [comment]
Oh great, sorry I looked in the documentation and couldn't find anything, but I didn't see the pull request. I guess we should keep this issue open until it is merged. The workaround also helps, thank you.
