### ISSUE TITLE
error tracking module from file

### ISSUE THREAD

**Issue by stevengj** [timholy/Revise.jl#258]
I was trying to use Revise to help debug the REPLCompletions standard library in Julia (in stdlib/REPL/src).  Since this is a stand-alone module, I can just do `include("REPLCompletions.jl"); using .REPLCompletions` and it works fine.  However, if I try to load it with `Revise.track` I get a slew of errors:
```jl
julia> using Revise; Revise.track("REPLCompletions.jl")
┌ Warning: error evaluating in module Main.REPLCompletions: const Completions = Tuple{Vector{Completion}, UnitRange{Int64}, Bool}
│   exception =
│    UndefVarError: Completion not defined
│    Stacktrace:
│     [1] #collect_args#33(::Bool, ::Function, ::JuliaInterpreter.Frame, ::Expr) at /Users/stevenj/.julia/packages/JuliaInterpreter/8bMSs/src/interpret.jl:64
│     [2] collect_args at /Users/stevenj/.julia/packages/JuliaInterpreter/8bMSs/src/interpret.jl:136 [inlined]
│     [3] lookup_callexpr at /Users/stevenj/.julia/packages/Revise/EuuFL/src/lowered.jl:13 [inlined]
│     [4] #methods_by_execution!#12(::Bool, ::Function, ::Any, ::Revise.CodeTrackingMethodInfo, ::Dict{Module,Array{Expr,1}}, ::JuliaInterpreter.Frame) at /Users/stevenj/.julia/packages/Revise/EuuFL/src/lowered.jl:165
...
```
I also tried using `JULIA_REVISE_INCLUDE=1` and got similar problems.  Am I supposed to be doing something differently to load a module from a file?

**Comment by stevengj** [comment]
Ah, `Revise.includet` seems to work.  I guess `track` is the wrong function here?

**Comment by timholy** [comment]
FYI the way I would have done it is `using REPL; Revise.track(REPL)`; that way you don't have to redefine any of the methods in REPL.

**Comment by timholy** [comment]
If this is poorly documented I'd love a suggestion about how to fix it.

**Comment by stevengj** [comment]
I guess it is unclear to me what `track(filename)` is supposed to do and how it differs from `includet(filename)`.

**Comment by timholy** [comment]
Good to know, I'll try to improve the docstrings. Just FYI: https://github.com/timholy/Revise.jl/blob/72e42d34ab5558590f27f8003331bb639cf12e95/src/Revise.jl#L617
