### ISSUE TITLE
revise on page reload in a web app

### ISSUE THREAD

**Issue by shashi** [timholy/Revise.jl#262]
I have a web app that uses Interact.jl to show some widgets, when I reload the page, the webapp's "handler" function is rerun which calls the said interact functions.

I would love to be able to edit Interact.jl and see the updated code run when I reload the page... Right now I need to stop the server and launch it again at the REPL. Any clues as to how I could get this to work?

**Comment by timholy** [comment]
See #269

**Comment by timholy** [comment]
Fixed by #269

**Comment by shashi** [comment]
Thanks @timholy !!
