### ISSUE TITLE
Revise.track reincludes the file (2.0.4 vs 1.1.0)

### ISSUE THREAD

**Issue by essenciary** [timholy/Revise.jl#263]
When using Revise v2, `Revise.track` reincludes the file which was already included via `include`. 

The same thing happens when using `includet`, the file will be included twice when using v2. 

A simple example, if we have two files, `main.jl` and `first.jl`: 

```julia
# main.jl
using Pkg
pkg"activate ."

using Revise

# include("first.jl")
# Revise.track("first.jl")

Revise.includet("first.jl")
```

```julia
# first.jl
println("first")
```

Running `$ julia main.jl` will output 
`first` 
on Revise 1 and 
`first`
`first`
on Revise 2. 

The behaviour is the same if you uncomment the commented lines and comment out the `includet`.

This is no bueno as it loads some of my big files twice, redefines constants and modules, etc.

**Comment by timholy** [comment]
I can't replicate this. First, if you're running this from the command line why doesn't Julia exit right away when finished including `first.jl`? Which file are you revising? (Revising `main.jl` should have no impact, if you're not already running Revise when it's loaded.) Also, please post `versioninfo()`, it shows if you have special environment settings (e.g., `JULIA_REVISE_INCLUDE`).

**Comment by essenciary** [comment]
Here is a quick output from the REPL session, you can see the behavior with Revise 1 and Revise 2: 

```julia
 ~/P/revise-test  julia                                                                 5.1s  Tue Apr  2 10:19:03 2019
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.1) pkg> activate .

(revise-test) pkg> st
    Status `~/Dropbox/Projects/revise-test/Project.toml`
  [295af30f] Revise v1.1.0

shell> open .

julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

shell> julia main.jl
first

(revise-test) pkg> up Revise
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/Dropbox/Projects/revise-test/Project.toml`
  [295af30f] ↑ Revise v1.1.0 ⇒ v2.0.4
  Updating `~/Dropbox/Projects/revise-test/Manifest.toml`
  [aa1ae85d] + JuliaInterpreter v0.3.2
  [6f1432cf] + LoweredCodeUtils v0.3.0
  [295af30f] ↑ Revise v1.1.0 ⇒ v2.0.4

shell> julia main.jl
first
first

julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

Also, please find attached the project after running the above code (so with Revise 2).

[revise-test.zip](https://github.com/timholy/Revise.jl/files/3032973/revise-test.zip)

**Comment by essenciary** [comment]
@timholy Thanks!

However, the issue of calling `include` and the `track` remains - this also leads to the file being included twice, on Revise 2.0.5. 

Is this the expected behavior in 2.x? It didn't work like that in v1.x. 

Thanks

**Comment by timholy** [comment]
Yes. Just call `includet` by itself. Or use `track("first.jl", define=true)` without the accompanying `include`.

Revise changed its internal paradigm drastically in 2.0. It now executes most of your code as it scans for methods. This is both scary and necessary if we want to capture all of the methods.

**Comment by essenciary** [comment]
@timholy 
Awesome, thanks! My problem with `indcludet` is that with Revise 1 I was using a combination of `include` and `track(MODULE, file)`. Simply replacing that with `includet` does not produce the same effect (the file is evaled in a different module). I have now switched to `track(MODULE, file, define=true)` and the behaviour is the same.

**Comment by timholy** [comment]
Can I ask, why are you not just using `using`? Is this an optional-dependency thing?
