### ISSUE TITLE
Bounds in REQUIRE cause downgrade

### ISSUE THREAD

**Issue by joshday** [timholy/Revise.jl#266]
I just saw this in `Pkg.update()`:

```
...
 [295af30f] ↓ Revise v2.0.1 ⇒ v1.1.0
...
```

Do older versions of Revise not include upper bounds?  It seems the resolver is downgrading Revise instead of upper-bounding what's in REQUIRE.

**Comment by joshday** [comment]
Based on discussion in the `pkg-usage` slack channel, https://github.com/timholy/Revise.jl/pull/265 should fix this.

**Comment by timholy** [comment]
Fixed by #265 (ref https://github.com/JuliaLang/METADATA.jl/pull/22616)
