### ISSUE TITLE
Revise on Core.Compiler not functional

### ISSUE THREAD

**Issue by vchuravy** [timholy/Revise.jl#270]
I didn't see another issue for this yet, but with `Revise @ v2.0.5`

```
 Revise.track(Core.Compiler)
┌ Warning: Core.Compiler is disabled
└ @ Revise ~/.julia/packages/Revise/17Klc/src/recipes.jl:139
...
```

Downgrading to `Revise @ v1.1.0` allows the recipe to work.

**Comment by pfitzseb** [comment]
This is basically a duplicate of https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/242, I think.

**Comment by timholy** [comment]
Yep. It already has a `@test_broken` for it.

**Comment by Keno** [comment]
Since the linked issue is closed, does this work again :)?

**Comment by pfitzseb** [comment]
Mostly: https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/277

**Comment by timholy** [comment]
See #289
