### ISSUE TITLE
Revise silently fails when I forget where {T}

### ISSUE THREAD

**Issue by MasonProtter** [timholy/Revise.jl#281]
Something I've noticed with revise is that if I add a function to a tracked file, say
```julia
function foo(a::Vector{T}) 
    ...
end
``` 
and then try to do something that depends on `foo` I'll just get a mysterious error claiming that there is no method matching `foo(a::Vector)`. When I restart my julia session out of exasperation, an error is thrown when parsing the module indicating I forgot a `where {T}`. It'd be nice if Revise could recognize this problem and throw a warning.

**Comment by timholy** [comment]
Seems like it got swallowed by my putting in Revise's internal debugging logs. Fixed in #282.
