### ISSUE TITLE
Revise Warning messages

### ISSUE THREAD

**Issue by m-wells** [timholy/Revise.jl#286]
Is there a way to suppress `Warning: error evaluating in module . . .` messages?  Typically the REPL will raise an error and the stack trace from `Revise` isn't helpful in debugging.

**Comment by timholy** [comment]
There isn't now. Isn't it sometimes useful to see the problematic expression?

**Comment by m-wells** [comment]
I'm having a hard time reproducing the issue I was experiencing earlier.  In fact the behavior right now is very useful.  In an attempt to reproduce it, I intentionally removed an `end` from a function in a module that had been loaded and it produces a very discrete `Failed to revise` warning.  Before I would get these very long warning messages and an `error` message.

**Comment by timholy** [comment]
Great. If this issue returns, comment again with a specific example and I'll reopen this.
