### ISSUE TITLE
Revise in startup.jl stopped working

### ISSUE THREAD

**Issue by marius311** [timholy/Revise.jl#291]
Not sure when this happened, but putting `using Revise` in my startup.jl no longer works. I can see the changes in `Revise.revision_queue` but I have to manually call `revise()`. Alternatively, it also works if I manually do `using Revise` as the first command on the REPL (as long as I didn't have `using Revise` in the startup.jl).  I'm on Julia 1.1.0 and I've checked with Revise v2.1.2 and gone back as far as v0.7.0 and can't find a version that works, so I suspect its something else about my system that changed recently, although I can't figure out what. Any suggestions what I could try to figure out what's gone wrong? Thanks.

**Comment by marius311** [comment]
FWIW, based on a hunch from reading https://github.com/timholy/Revise.jl/pull/54 it appears things work if instead of just `using Revise` I put the following in my startup.jl:

```julia
@async begin
    sleep(1)
    @eval using Revise
end
```

**Comment by timholy** [comment]
Config instructions are [here](https://timholy.github.io/Revise.jl/stable/config/).

**Comment by marius311** [comment]
Thanks, I admit I had missed that the thing to put in your startup is more complicated than just `using Revise`. I'm now starting to wonder if this ever worked for me? I'm pretty sure it did... 

In any case, even now that I'm following the correct instructions from your link, it still does not work and I have to `revise()` manually. Any ideas what I can do to further debug?

**Comment by timholy** [comment]
It's changed over time, as people have filed bugs about diverse conditions under which they use Julia.

To debug, please specify `versioninfo` and how you're using it (plain REPL, Atom console, VS Code console, IJulia, emacs shell, etc.)

**Comment by marius311** [comment]
Well... some combination of package updates, probably as I was testing your PR for the generated functions seems to have fixed it, so its working again ¯\\_(ツ)_/¯

For posterity in case it helps, this was my setup:

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 1
```

It was just plain REPL. After changing a file, I could see the changes in `Revise.revision_queue` but had to do a `revise()` by hand to get them to go.

**Comment by timholy** [comment]
Basically the same configuration I use. I can assure you it works for me, glad to hear it now seems to be working for you.

**Comment by newptcai** [comment]
The link says Julia 1.5+? Do you mean 1.0.5 instead?

**Comment by glitzflitz** [comment]
I have same doubt as @newptcai I'm on arch linux and current version of julia on official repo is v1.4.1

**Comment by newptcai** [comment]
I was told it meat 1.5, which has not been released.
