### ISSUE TITLE
Revise issue, with includet("filename"), on second run

### ISSUE THREAD

**Issue by jenlabossiere** [timholy/Revise.jl#292]
I'm using Revise to toggle breakpoints, with includet("filename") at the beginning. The first time I ran it, no issues. I was able to toggle a breakpoint and run the debugger. 

Then, for some strange reason, now I'm getting this error, no matter what the function is: 
<img width="881" alt="image" src="https://user-images.githubusercontent.com/43189030/56552877-77e09f80-6541-11e9-94a3-3de979e1863a.png">

I've turned Atom off and then on, more than a few times. I've coded a different file and tried on there. I've deleted Revise and JuliaInterpreter and redownloaded. I tried writing it line by line and it breaks when I try includet("filename"). I'm not sure what to do / what to change.

Note: Now when I click in the left column to toggle a breakpoint, it says: "no signatures found among the signatures Any[]"

**Comment by timholy** [comment]
While it sounds like this happens for anything you try, when I tried reproducing it I couldn't. I'm going to need a step-by-step guide to how to trigger this.

Here's what I tried:
- open atom, create a file `/tmp/test.jl` with contents `f() = 1`.
- in atom's console, type `includet("/tmp/test.jl")`
- set a breakpoint at `f`
- `Juno.@enter f()`. Everything seemed normal
- edit the file to add `g() = f()`
- `Juno.@run g()`. Everything seemed normal.

**Comment by jenlabossiere** [comment]
doing includet("filename") in the console has completely fixed it! I had it in the script itself, which was causing that error. Thank you so much for the list to fix it.

**Comment by timholy** [comment]
Great. If you can figure out how to clarify this in the docs, please submit a PR! (You can just click on the pencil icon for any of the files [here](https://github.com/timholy/Revise.jl/tree/master/docs/src)). As the author of both the package and the documentation, it's hard for me to envision where people might misunderstand; real users are better suited to point out where I've been unnecessarily vague or confusing.
