### ISSUE TITLE
Precompile error

### ISSUE THREAD

**Issue by andreasnoack** [timholy/Revise.jl#293]
After upgrading my packages in general and Revise specifically to 2.1.2 I'm getting 
```julia
julia> using Revise
[ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
ERROR: LoadError: AssertionError: precompile(getfield(Revise, m.name), (Bool, typeof(methods_by_execution!), Function, CodeTrackingMethodInfo, Dict{Module, Vector{Expr}}, Module, Expr))
Stacktrace:
 [1] _precompile_() at /Users/andreasnoack/.julia/packages/Revise/RW8TD/src/precompile.jl:16
 [2] top-level scope at none:0
 [3] include at ./boot.jl:326 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] top-level scope at none:2
 [7] eval at ./boot.jl:328 [inlined]
 [8] eval(::Expr) at ./client.jl:404
 [9] top-level scope at ./none:3
in expression starting at /Users/andreasnoack/.julia/packages/Revise/RW8TD/src/Revise.jl:1093
ERROR: Failed to precompile Revise [295af30f-e4ad-537b-8983-00126c2a3abe] to /Users/andreasnoack/.julia/compiled/v1.1/Revise/M1Qoh.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
```
when running in the `v1.1` environment. It succeeds when I try installing the version in clean environment.

Any ideas what is going on and how I can debug? Already to delete `compiled`. Also, downgrading to `1.1.0` also fixed the issue. couldn't try intermediate versions because of `JuliaInterpreter`.

**Comment by timholy** [comment]
What's your LoweredCodeUtils version? You need 0.3.2. https://github.com/JuliaRegistries/General/blob/master/L/LoweredCodeUtils/Versions.toml

If you figure out why you're not updated to the latest LoweredCodeUtils, please let me know (this is important to fix).

**Comment by fredrikekre** [comment]
You get LowerCodeUtils 0.3.1, because Revise is not compatible with 0.3.2 (according to the registry) https://github.com/JuliaRegistries/General/blob/9455558b1e56d6e912faf3f3249aa6a0d088d478/R/Revise/Compat.toml#L42

**Comment by timholy** [comment]
Interesting. In the `Project.toml` it's `~0.3.1` which I assume should have allowed compatibility? How did the registry get "corrupted"?

**Comment by fredrikekre** [comment]
Could just be that the last Revise version was registered before the switch and the converter automatically updated the upper bounds to the newest release.
