### ISSUE TITLE
Couldn't make Revise work with Juno

### ISSUE THREAD

**Issue by Deoch** [timholy/Revise.jl#296]
Hello, I have a problem using the package, and I can't make it work (even with the example provided in the documentation). I am still an inexperienced programmer, so I may do something wrong.

I am on julia 1.0.3, Juno 0.7.0 and Atom 0.8.5, with windows 10

Is there any additionnal manipulation to use the package on Juno instead of a terminal ?

Thanks

**Comment by timholy** [comment]
It should work fine, I use it in Juno all the time. You'll have to be more explicit about what you're trying and what's not working for you.

**Comment by VincentTam** [comment]
I am on Julia 1.1.0, Juno 0.7.0 and Atom 1.36.1, with Xubuntu 18.04, and I am faced with similar error.

[![Juno error](http://imgur.com/GUON9Kdl.png)](http://imgur.com/GUON9Kd.png)

A minimal program that I want to add breakpoints.

```julia
Z() = randn()                         # standard normal random variable
myfct() = Z() / Z()                   # "random variable" Z/Z = 1
myvec = broadcast(a->myfct(),1:10)    # "simulate" the "random variable" tens times
sum(myvec)/length(myvec)              # expect "average" to be 1, but result ≠ 1
```

**Comment by KristofferC** [comment]
@VincentTam, this has nothing to do with this issue and you have already gotten a response at https://discourse.julialang.org/t/cant-set-breakpoints-in-juno/23960/2.

**Comment by VincentTam** [comment]
@KristofferC From my uploaded screenshot, I did executed `using Revise` from the REPL before adding break points, but the errror still appeared.

By the time I posted my last message, my topic on Julia Discourse was under moderator's review.

The title reads "can't Revise work with Juno".  Would you say that Revise work with Juno from the screenshot?

**Comment by KristofferC** [comment]
https://discourse.julialang.org/t/ann-juno-0-8/22157

> Important: If you want to set breakpoints in files you need to have loaded Revise.jl and Revise needs to be [aware of the file in question](https://timholy.github.io/Revise.jl/stable/#What-Revise-can-track-1). This means that you can only set breakpoints in your own scripts (that are not part of a package) if you have `includet` them.

So you need to run `includet("temp.jl")` after `using Revise` if you want to set breakpoints in that file.

https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/259 should remove that limitation.

**Comment by VincentTam** [comment]
@KristofferC Thanks for your reply.  I've also found this in [your comment elsewhere](https://discourse.julialang.org/t/ann-juno-0-8/22157/9?u=vincenttam).  Unluckily, that's not in the docs that the reponse linked to.

I'm new to Julia debugging and the Discourse forum.  Do I have to choose either one forum when asking questions?

**Comment by KristofferC** [comment]
> Do I have to choose either one forum when asking questions?

In general it is good to not post the same question in multiple places. When in doubt, it is good to default to Discourse.
