### ISSUE TITLE
`entr` exits on watched file save

### ISSUE THREAD

**Issue by essenciary** [timholy/Revise.jl#303]
Please see the attached video. 
![out](https://user-images.githubusercontent.com/11292378/57446322-b8842c80-7254-11e9-9227-487479c680b9.gif)

```julia
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE = auto

(testapp) pkg> st
    Status `~/Dropbox/Projects/testapp/Project.toml`
  [c43c736e] Genie v0.9.2 #master (https://github.com/essenciary/Genie.jl)
  [682c06a0] JSON v0.20.0
  [39ec1447] Millboard v0.2.0
  [295af30f] Revise v2.1.4
  [340e8cb6] SearchLight v0.8.3 #master (https://github.com/essenciary/SearchLight.jl)

```

**Comment by pfitzseb** [comment]
Possibly a dup of https://github.com/timholy/Revise.jl/issues/298.

**Comment by timholy** [comment]
Was this fixed by #308? If so please close.

**Comment by essenciary** [comment]
Thanks, I'll retest and follow up!

**Comment by essenciary** [comment]
@timholy @mlhetland Works great, thanks so much! 
There doesn't seem to be any problem with spawning the call to `entr` which is great! 
I do see the code being triggered multiple times on file save, which I presume it's due to the IDE. This can be easily addressed by queuing the multiple calls and delaying action by 5s or so.

**Comment by mlhetland** [comment]
My solution to the multiple calls thing was essentially just the delay parameter; if you have a suggestion for more elegant handling, I'd be happy to tweak it. I, too, had to use a delay of several seconds with some editors, but that doesn't seem optimal, if you save often.

I did actually think about setting the default to the same as with `poll_file` (5.007 s), but I thought it better to let people do that themselves, if they needed it.

**Comment by mlhetland** [comment]
(And, in case you're delaying things yourself, and didn't see the change: There's now a `pause` keyword argument, specifically to avoid these multiple calls.)
