### ISSUE TITLE
includet errors on self-referential struct

### ISSUE THREAD

**Issue by Benoit9** [timholy/Revise.jl#304]
I have a script `testRevise.jl` that defines a type

`
mutable struct Node
	t :: Node
end
`

If I do at the REPL

` using Revise
includet("testRevise.jl")
`

I get the error below. But `include("testRevise.jl")` works fine.
Julia 1.1 & Revise v2.1.4

`
┌ Error: evaluation error
│   mod = Main
│   ex =
│    :(mutable struct Node
│          #= /exp/jaa/testRevise.jl:2 =#
│          t::Node
│      end)
│   exception =
│    UndefVarError: Node not defined
│    Stacktrace:
│     [1] lookup_or_eval(::Any, ::JuliaInterpreter.Frame, ::Any) at /home/xxx/.julia/packages/JuliaInterpreter/6LimI/src/interpret.jl:85
│     [2] lookup_or_eval(::Any, ::JuliaInterpreter.Frame, ::Any) at /home/xxx/.julia/packages/JuliaInterpreter/6LimI/src/interpret.jl:93
│     [3] evaluate_structtype(::Any, ::JuliaInterpreter.Frame, ::Expr) at /home/xxx/.julia/packages/JuliaInterpreter/6LimI/src/interpret.jl:301
│     [4] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at /home/xxx/.julia/packages/JuliaInterpreter/6LimI/src/interpret.jl:452
│     [5] #methods_by_execution!#14(::Bool, ::Bool, ::Function, ::Any, ::Revise.CodeTrackingMethodInfo, ::Dict{Module,Array{Expr,1}}, ::JuliaInterpreter.Frame) at /home/xxx/.julia/packages/Revise/UtBAC/src/lowered.jl:70
│     [6] #methods_by_execution! at /home/xxx/.julia/packages/Revise/UtBAC/src/lowered.jl:0 [inlined]
│     [7] #methods_by_execution!#9(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol,Symbol},NamedTuple{(:define, :skip_include),Tuple{Bool,Bool}}}, ::Function, ::Any, ::Revise.CodeTrackingMethodInfo, ::Dict{Module,Array{Expr,1}}, ::Module, ::Expr) at /home/xxx/.julia/packages/Revise/UtBAC/src/lowered.jl:49
│     [8] #methods_by_execution! at ./none:0 [inlined]
│     [9] #eval_with_signatures#59(::Bool, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:skip_include,),Tuple{Bool}}}, ::Function, ::Module, ::Expr) at /home/xxx/.julia/packages/Revise/UtBAC/src/Revise.jl:344
│     [10] #instantiate_sigs!#60(::Bool, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:skip_include,),Tuple{Bool}}}, ::Function, ::OrderedCollections.OrderedDict{Module,OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}}}) at ./none:0
│     [11] #instantiate_sigs! at ./none:0 [inlined]
│     [12] #track#65(::Bool, ::Bool, ::Function, ::Module, ::String) at /home/xxx/.julia/packages/Revise/UtBAC/src/Revise.jl:597
│     [13] #track at ./none:0 [inlined]
│     [14] includet(::Module, ::String) at /home/xxx/.julia/packages/Revise/UtBAC/src/Revise.jl:645
│     [15] includet(::String) at /home/xxx/.julia/packages/Revise/UtBAC/src/Revise.jl:655
│     [16] top-level scope at none:0
│     [17] eval(::Module, ::Any) at ./boot.jl:328
│     [18] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
│     [19] run_backend(::REPL.REPLBackend) at /home/xxx/.julia/packages/Revise/UtBAC/src/Revise.jl:943
│     [20] (::getfield(Revise, Symbol("##74#76")){REPL.REPLBackend})() at ./task.jl:259
└ @ Revise ~/.julia/packages/Revise/UtBAC/src/lowered.jl:52

`

**Comment by timholy** [comment]
To get the fix, currently you'll need the master branch of JuliaInterpreter, but hopefully we can make a new release soon.
