### ISSUE TITLE
`entr` enhancements [feature suggestions]

### ISSUE THREAD

**Issue by essenciary** [timholy/Revise.jl#305]
Here are a few suggested features which would make `entr` more powerful: 

1 - pass the matched file as an argument to the callback function.
Something in the line of: 
```julia
entr([...]) do file 
...
end
```
This would allow for more granular logic. 

2 - allow passing folders, not just files. There's rarely a need to watch individual files, it's more like "all the files in this folder" (ideally recursively). 

3 - it really shouldn't be blocking, but I assume that can be easily addressed with `@spawn`, `@fetch`, etc. 

---

My use case would be something like this: 

```julia
if config.AUTO_RELOAD 
  @spawn entr(
    filter(Revise.watched_files) do file_path
      startswith(file_path, Genie.APP_PATH)
    end
  ) do  
    websockets.reload_page()
  end
end
```

---

If you think they'd be useful I can make a PR.

**Comment by timholy** [comment]
Yes, please make a PR. Note #308.

**Comment by essenciary** [comment]
@timholy Thanks, will do!

**Comment by tkluck** [comment]
As for (3) you might be interested in #443 .

**Comment by c42f** [comment]
With #488 is merged, most of this is addressed.

(1) is mostly addressed because functions `f` passed to `add_callback(f, [files])` are only triggered for the specific files listed.
(3) is fixed directly because `add_callback` isn't blocking.

(2) is not yet addressed, I think.

**Comment by ffevotte** [comment]
I think (2) should be addressed as well , especially thanks to https://github.com/timholy/Revise.jl/blob/397db6d63b0f1c845ae51fa879c4c2645e35072b/src/pkgs.jl#L313-L317

Example:

```julia
julia> mkdir("foo")
"foo"

julia> using Revise

julia> t = @async Revise.entr(["foo"], postpone=true) do
         println("update")
       end
Task (runnable) @0x00007feed259b820

# Watching a directory translates to watching file "" within directory itself ("/tmp/foo")
julia> Revise.watched_files
Dict{String,Revise.WatchList} with 1 entry:
  "/tmp/foo" => WatchList(1.60578e9, Dict{String,Base.PkgId}(""=> [top-level]))

# File creation
julia> touch("foo/bar"); sleep(1)
update

# File creation, again
julia> touch("foo/baz"); sleep(1)
update

# File modification
julia> touch("foo/bar"); sleep(1)
update

# File deletion
julia> rm("foo/baz"); sleep(1)
update
```

(I seem to recall that watching directories can behave differently on some systems...)

**Comment by timholy** [comment]
Let's close this. Thanks for all who have contributed to `entr`!
