### ISSUE TITLE
Generated functions and world age

### ISSUE THREAD

**Issue by cstjean** [timholy/Revise.jl#31]
Generated functions only use the functions as they were in the world age where they were defined. 

> Some operations that should not be attempted include:
> Calling any function that is defined after the body of the generated function. 

This means:
```julia
module Tmp
f() = 3
@generated g() = f()
end
```

```julia
julia> using Revise, Tmp

julia> Tmp.f()
3

julia> Tmp.g()
3

# Change f
julia> Tmp.f()
WARNING: Method definition f() in module Tmp at /Users/cedric/Programa/RL/Tmp.jl:2 overwritten at /Users/cedric/Programa/RL/Tmp.jl:2.
4

julia> Tmp.g()
3
```

Furthermore, because the rexes are stored in an unordered set, I believe that changing both `Tmp.f` and `Tmp.g` (to `g() = f()+0`, say) would have a 50% chance of returning 3 or 4. Same with macros.

**Comment by timholy** [comment]
I don't think there's anything that can be done here about the core problem---all this package (currently) does is put a convenient wrapper around capabilities in Base. Since that doesn't work when you do it manually, it won't work with Revise either.

You're right about the unsorted Set though. We should rebase on OrderedSet from DataStructures. Quite busy now so I wouldn't mind a PR, but I will likely get to it eventually.

**Comment by timholy** [comment]
Unless generated functions start keeping track of their backedges to functions called from their generator, there's nothing we can do here.

Demo:
```julia
julia> module Tmp
       f() = 3
       g() = 5
       @generated function h()
           x = f()
           :($x, g())
       end
       k() = f()
       l() = g()
       end
Tmp

julia> Tmp.h()
(3, 5)

julia> Tmp.k()
3

julia> Tmp.l()
5

# Functions called from the "body" (quoted expression) do work
julia> m = first(methods(Tmp.g))
g() in Tmp at REPL[1]:3

julia> mi = m.specializations.func
MethodInstance for g()

julia> mi.backedges
2-element Array{Any,1}:
 MethodInstance for h()
 MethodInstance for l()

# Functions called from the generator are not tracked
julia> m = first(methods(Tmp.f))
f() in Tmp at REPL[1]:2

julia> mi = m.specializations.func
MethodInstance for f()

julia> mi.backedges
1-element Array{Any,1}:
 MethodInstance for k()
```

#41 is as close as we can come to fixing this now, the rest is a Base issue.
