### ISSUE TITLE
Failed to revise: StackOverflowError()

### ISSUE THREAD

**Issue by jzazo** [timholy/Revise.jl#315]
I am observing an error similar to this one: https://discourse.julialang.org/t/stackoverflowerror-with-revise-jl/23947

I've tried to narrow down the error message. Here are the steps to reproduce. I think JuMP may be interfering with revise, but I don't know how or why. I am loading Revise automatically every time I start Julia.
```
(v1.1) pkg> generate MWE
(v1.1) pkg> dev "path-to-MWE"
```
Then in `src/MWE.jl` edit
```
module MWE

export foo

function foo()
    return 1.0
end

end # module
```
Create `test/runtests.jl`
```
using MWE
using JuMP

foo()
```
Then, I run in Juno line by line `test/runtests.jl`. Then, I edit `foo()` as follows 
```
function foo()
    println("testing")
    return 1.0
end
```
and when I try to run foo() again in `test/runtests.jl` I get
```
julia> ┌ Warning: Failed to revise /home/javier/Desktop/MWE/src/MWE.jl: StackOverflowError()
       └ @ Revise ~/.julia/packages/Revise/7c9Zt/src/Revise.jl:548
```
Thanks for developing a great package.

**Comment by timholy** [comment]
I can't replicate this. Can you provide particulars about your environment? Specifically
```julia
(v1) pkg> st Revise
    Status `~/.julia/environments/v1/Project.toml`
  [da1fd8a2] CodeTracking v0.5.7
  [aa1ae85d] JuliaInterpreter v0.5.2
  [6f1432cf] LoweredCodeUtils v0.3.4
  [bac558e1] OrderedCollections v1.1.0
  [295af30f] Revise v2.1.5
  [8ba89e20] Distributed 
  [7b1f6079] FileWatching 
  [76f85450] LibGit2 
  [44cfe95a] Pkg 
  [3fa0cd96] REPL 
  [4ec0a83e] Unicode 

julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308* (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIAFUNCDIR = /home/tim/juliafunc
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 6
  JULIA_CPU_THREADS = 2
```

You can also `dev Revise` and make the changes I suggested in that discourse post; that will give you more information about the nature of the error.

**Comment by jzazo** [comment]
Thanks for your response. Here are the outputs you requested:
```
(v1.1) pkg> st Revise
    Status `~/.julia/environments/v1.1/Project.toml`
  [aa1ae85d] JuliaInterpreter v0.6.0
  [295af30f] Revise v2.1.6

julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

It turns out that when I `dev`'ed Revise to change the lines from the other thread, it started to work fine. So I removed Revise, added it again, and I don't see that behavior any more.

Thanks for help. If I see a similar behavior again, I'll report back, but I can no longer reproduce  :S

**Comment by georgematheos** [comment]
@timholy I am running into a similar issue to this again.  It looks like Revise's source code has changed since that discourse post, and so I'm not sure how to apply the "fix"/logging change suggested in the post to the current version of revise.

The error I'm getting is:
```
┌ Error: Failed to revise /Users/georgematheos/Developer/research/GenWorldModels.jl/src/lookup_or_generate.jl
│   exception =
│    StackOverflowError:
│    Stacktrace:
│     [1] set_to_running_name!(::Any, ::Dict{Symbol,Symbol}, ::JuliaInterpreter.Frame, ::Dict{Symbol,LoweredCodeUtils.MethodInfo}, ::Dict{Symbol,Union{Bool, Symbol}}, ::Symbol, ::Symbol) at /Users/georgematheos/.julia/packages/LoweredCodeUtils/Bg1Cc/src/LoweredCodeUtils.jl:315
└ @ Revise ~/.julia/packages/Revise/BqeJF/src/Revise.jl:760
```

This only seems to occur when I update one specific file, though I'm not totally sure why.  This file is probably having the values of `@generated` functions it creates modified from the changes I'm making, which is the main "unusual" thing about it.

Here is the requested debugging information:
```
st Revise
Project GenWorldModels v0.1.0
Status `~/Developer/research/GenWorldModels.jl/Project.toml`
  [295af30f] Revise v2.7.3 [`~/.julia/dev/Revise`]

julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
  JULIA_NUM_THREADS = 
```

**Comment by timholy** [comment]
What's your Revise version? 2.7.3 is the current version, but there have been package-manager induced downgrades. Currently I recommend
```julia
add Revise@2
pin Revise
```

**Comment by georgematheos** [comment]
Thanks for the suggestion!  I am using 2.7.3 already, so I don't think that is the problem; these commands did not affect the problem.

**Comment by timholy** [comment]
I'll need a MWE in order to make any progress on your issue, @georgematheos. Might be best to report as a new issue.
