### ISSUE TITLE
Changes not updating in a specific function

### ISSUE THREAD

**Issue by yha** [timholy/Revise.jl#316]
Reproduced on two different machines with the following:

`]dev Plots`
In Juno:
```
using Revise
using Plots
pyplot()

pl = plot(rand(4));
Atom.displayinplotpane(pl)
```
Insert some printing into `prepare_output` at `.julia/dev/Plots/src/plot.jl`:253 and `_before_layout_calcs(::Plot{PyPlotBackend})` at `.julia/dev/Plots/src/backends/pyplot.jl`:955 (both of these are called from `Atom.displayinplotpane`).
When rerunning, only the first change is reflected. The second one only prints after restarting Julia.

**Comment by pfitzseb** [comment]
I think this is happening because of Plots' non-standard code loading for backends. You'll probably need to track those changes [explicitly](https://timholy.github.io/Revise.jl/stable/user_reference/#Revise.track).

**Comment by yha** [comment]
Yes, it looks like `backends/pyplot.jl` is dynamically loaded (I had wrongly assumed only `PyPlot` and dependent modules would be).
But tracking explicitly doesn't seem to help here. The same issue is reproduced with the following code:
```
using Revise
using Plots
pyplot()

pl = plot(rand(4));
Revise.track(Plots, "$(dirname(pathof(Plots)))/backends/pyplot.jl")
Atom.displayinplotpane(pl)
```

**Comment by timholy** [comment]
Sorry for the long delay getting to this. I thought it was going to be very tricky, but with your manual `track` it turns out to have been a stupid relative-path issue with a one-line fix (and as usual a many-line test :wink:). See #395 .

This will come out as Revise 2.3.1.

**Comment by timholy** [comment]
You may have seen it, but https://github.com/JuliaPlots/Plots.jl/pull/2250#issuecomment-554639086 lists some options to get Revise to track such files automatically.
