### ISSUE TITLE
Optional continuous warnings after revise failure resp. on inconsistent state

### ISSUE THREAD

**Issue by oschulz** [timholy/Revise.jl#317]
A frequent problem I've encountered with less experienced users is that they often overlook a revise error message (e.g. when revise failed because of errors in the changed source code). Since revise reports this only once, the users are often unaware that they're still using the old version of the code afterwards.

It would be nice if Revise could (as an option) warn that on-disk source code and active code are inconsistent on every REPL/Jupyter-cell evaluation, to keep users aware that they're not running the code they think they are.

**Comment by timholy** [comment]
xref #321

**Comment by oschulz** [comment]
Thanks, Tim!
