### ISSUE TITLE
Remind user that file is skipped due to parsing error

### ISSUE THREAD

**Issue by ianshmean** [timholy/Revise.jl#321]
I think it could be helpful for `Revise` to remind the user that certain files are being skipped due to parsing errors.

For instance, every so often I might skip a parsing error message when multiple errors exist, and on subsequent method runs miss the fact that a file is being omitted... which leads me off into a fruitless debug loop. I try to remember that this can happen with Revise, so restart the session, but it's rarely the first thing I think of.

**Comment by timholy** [comment]
xref #317
