### ISSUE TITLE
First pass in separate process?

### ISSUE THREAD

**Issue by garrison** [timholy/Revise.jl#326]
Hi Tim,

Excellent talk the other day.  Regarding your [concern about executing code twice when taking two passes over a module](https://youtu.be/gXDI4DSp04c?t=838) (e.g. performing `init_c_library()` twice), have you considered doing the first pass in a separate process and communicating the resulting signatures back to the main process?  I don't think that this would handle every corner case, but would it be an improvement?   My apologies if I don't understand the full problem, but from the surface it sounds that this may be an approach worth exploring.  Feel free to close if there are obvious reasons it won't work.

**Comment by timholy** [comment]
That's a really interesting suggestion! And one I hadn't considered. It merits careful thought (i.e., more time than I currently have), so I will get back to this.

**Comment by timholy** [comment]
Closed by #255
