### ISSUE TITLE
Revise slow on `exit()`

### ISSUE THREAD

**Issue by ericphanson** [timholy/Revise.jl#327]
Sometimes I make a change that Revise can't handle, such as changing a `struct`. I know I need to restart Julia, so I call `exit()`, but then it takes awhile to wait while Revise parses the changes and throws an error (about the `struct` change) before I can exit. It would be really nice if `exit()` were special-cased somehow so that Revise doesn't try to recompile changes before the call goes through, since those changes shouldn't matter anyway. (I can only think of this going wrong if the changes Revise is processing are to redefine `exit()` itself... but that seems like a bad idea to do anyhow).

**Comment by KristofferC** [comment]
As a workaround, you could exit with Ctrl+D instead.

**Comment by ericphanson** [comment]
Ah, convenient! Thanks
