### ISSUE TITLE
`@__FILE__` is wrong when reloading

### ISSUE THREAD

**Issue by Keno** [timholy/Revise.jl#36]
When a function that uses `@__FILE__` is reloaded, the macro evaluates to `nothing` rather than the  filename.

**Comment by cstjean** [comment]
In ClobberingReload, I used [this function](https://github.com/JunoLab/CodeTools.jl/blob/40f3bf96d4a03ebd59551aef7419a532f072c49f/src/utils.jl#L24), and it worked fine.

**Comment by timholy** [comment]
I was already looking for `@__FILE__` calls, but in a too-limited context. See #37.
