### ISSUE TITLE
Making `Revise.juliadir` more robust

### ISSUE THREAD

**Issue by aytekinar** [timholy/Revise.jl#365]
Hi,

We are using a shared server where we build `julia` from the source. The building happens under a privileged user account (e.g., `root` or some other admin account). This results in problems when trying to use `Revise`. The offending line, in our (cc: @martinbiel) opinion, is the following

https://github.com/timholy/Revise.jl/blob/568af230364f97bfc4c859aae7fb7cb5dd5d3dcf/src/Revise.jl#L149

where `isdir` throws `EACCESS`. Rewriting the `isdir` part in a `try ... catch` block should solve the problem, but we do not know whether there are other places that need a similar fix.

**Comment by timholy** [comment]
Other than the test case below, I am not sure where other problems would crop up. Would you perhaps try the fix you propose? I don't have a build environment like yours, so it is much harder for me to test.

One issue to keep in mind is that if Revise can't access the source directories, the Juno debugger (or Debugger.jl) probably won't work on Base itself. To find out exactly how it fails, try something like
```julia
using CodeTracking
m = @which sum([1,2,3])
definition(m)
```
and let me know what happens. I might be able to identify more places where fixes are needed.

**Comment by aytekinar** [comment]
`try ... catch` block seems to fix my problem and passes all tests on my platform.

The code excerpt you have pasted results in the following:
```julia
julia> using CodeTracking

julia> m = @which sum([1,2,3])
sum(a::AbstractArray) in Base at reducedim.jl:652

julia> definition(m)

julia> 
```

If you think that everything seems to be OK, I will create a PR based on my topic branch.

**Comment by timholy** [comment]
For comparison,
```julia
julia> using CodeTracking, Revise

julia> m = @which sum([1,2,3])
sum(a::AbstractArray) in Base at reducedim.jl:652

julia> definition(m)
[ Info: tracking Base
:(#= /home/tim/src/julia-1/base/reducedim.jl:652 =# @inline sum(a::AbstractArray; dims=:) = begin
              #= /home/tim/src/julia-1/base/reducedim.jl:652 =#
              _sum(a, dims)
          end)
```

(Sorry, I should have specified that you also needed to have loaded Revise.)

The tests may not look for this. But clearly your fix makes it a lot better, and progress is all we need.

**Comment by aytekinar** [comment]
Weird. The above snippet gives

```julia
julia> using CodeTracking, Revise
[ Info: Precompiling CodeTracking [da1fd8a2-8d9e-5ec2-8556-3022fb5608a2]
[ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe]

julia> m = @which sum([1,2,3])
sum(a::AbstractArray) in Base at reducedim.jl:652

julia> definition(m)

julia>
```

on a normal user account, whereas it gives

```julia
julia> using CodeTracking, Revise
[ Info: Precompiling CodeTracking [da1fd8a2-8d9e-5ec2-8556-3022fb5608a2]
[ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe]

julia> m = @which sum([1,2,3])
sum(a::AbstractArray) in Base at reducedim.jl:652

julia> definition(m)
[ Info: tracking Base
:(#= /home/aytekin/Documents/My_PKGBUILDs/julia-stable/src/julia-stable-1.2.0/base/reducedim.jl:652 =# @inline sum(a::AbstractArray; dims=:) = begin
              #= /home/aytekin/Documents/My_PKGBUILDs/julia-stable/src/julia-stable-1.2.0/base/reducedim.jl:652 =#
              _sum(a, dims)
          end)

julia>
```

on the user account which had the source files when installing `julia`.

Without #367 (i.e., aytekinar/Revise.jl@b9a37760), however, even `using Revise` results in a failure. For instance, have you tried your script on a user account other than `tim` on your machine, while making sure `/home/tim` has 700 access mode?

**Comment by timholy** [comment]
That's not weird, it's what I expected. In order to extract the definition of that method, Revise has to be able to access the source code. `definition` returns `nothing` if it can't find the code.

Mostly I was wanting to check whether it would error, reassuring that it does not. And `definition` should still work fine for packages that are on an accessible directory. Just expect a few weirdnesses if you debug into Base methods.

**Comment by aytekinar** [comment]
OK, then, thanks! But I still don't understand why it does not work. I mean, in the end, when I run

```julia
julia> using Revise
[ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe]

julia> Revise.juliadir
"/usr/share/julia"

julia>
```

I seem to get the correct (system) path that has `base` files. Why do I still see `nothing`? I apologize in advance for asking (perhaps a stupid) question like this, but I am not a user of this package and I wanted to understand what is wrong.

**Comment by timholy** [comment]
Ah, interesting. It sounds like there may be another place or two that need a fix.
