### ISSUE TITLE
Cannot get basic Revise behavior to work with Ubuntu LTS on Fresh Julia

### ISSUE THREAD

**Issue by pdeffebach** [timholy/Revise.jl#368]
I posted earlier on Discourse about this issue [here](https://discourse.julialang.org/t/trouble-with-dev-and-revise/28818/7). 

Today I re-installed julia and tried the following. 

```
(v1.2) pkg> add Revise
(v1.2) pkg> add PkgTemplates
julia> using PkgTemplates
julia> t = Template(dir = ".")
julia> generate("HelloWorld", t)
(v1.2) pkg> st
    Status `~/.julia/environments/v1.2/Project.toml`
  [3d01b675] HelloWorld v0.1.0 [`~/Documents/Development/HelloWorld`]
  [14b8a8f1] PkgTemplates v0.6.2
  [295af30f] Revise v2.2.0

julia> using Revise, HelloWorld
julia> HellWorld.greet() # Returns "Hello, World!"
julia> edit(HelloWorld.greet) # Changed "Hello, World!" to "Hello!" in Vim
julia> HellWorld.greet() # Says "Hello, World!" still. 
```

I cannot get  Revise to work. Test pass when I run them using `Pkg`. It is not clear where things are going wrong.

**Comment by pdeffebach** [comment]
I can also confirm that the tutorial using `]dev Example` will not work for me either.

**Comment by timholy** [comment]
Works for me. Does it work if you're not using `"."` as the `dir` but defaulting to `~/.julia/dev`?

**Comment by pdeffebach** [comment]
Yes I can confirm that it still doesn't work. Is there any debugging I can do to figure out the point of failure?

**Comment by timholy** [comment]
Definitely. Start here: https://timholy.github.io/Revise.jl/stable/debugging/

**Comment by timholy** [comment]
Also, if you're on an NFS-mounted drive, you'll need to turn on polling (see the docs).

**Comment by pdeffebach** [comment]
Things work now, so I won't produce a bug report. 

This is the second time things seem to have stopped working but then have started working again. I think my mental model is improving on this so hopefully I will be able to catch where I go wrong next time. 

Thank you for your response. Closing this.
