### ISSUE TITLE
Revise stops working when using modules that are not listed as dependencies

### ISSUE THREAD

**Issue by mattuntergassmair** [timholy/Revise.jl#371]
Revise stops working if modules use a package that is not explicitly listed as a dependency in `Project.toml`.

Example (julia v1.1, started with `julia --project` from `MyPackage` folder):

```
module MyPackage

# this line breaks Revise!!
# ]add Colors solves the problem
using Colors

function foo()
    println("foo")
end

export foo

end # module
```
If `Colors` (or any other package) is not in the dependencies of `MyPackage`, then Revise stops working (silently, without raising an error or warning). Removing the line `using Colors` or adding it to the dependencies fixes the issue.

If it's not worth fixing, at least putting this information somewhere in the Docs would be very helpful.

**Comment by timholy** [comment]
When you say "stops working" do you mean not for other packages loaded in the same session? Or just for MyPackage?

**Comment by mattuntergassmair** [comment]
It seems to stop tracking any changes in the MyPackage module, for example changing the output of `foo()` in the minimal example above. So calling `foo()` again skips recompilation and runs the old version of the function. Not sure if it still tracks other packages.

**Comment by mattuntergassmair** [comment]
Actually I ran a quick test using `MyPackage` and `Example` in parallel, it still tracks changes in `Example`. So seems to just affect `MyPackage`.

The behavior should be easy to reproduce by running `julia --project` in the following folder structure

```
└── MyPackage
    ├── Manifest.toml
    ├── Project.toml
    └── src
        └── MyPackage.jl
```
and the following Project file
```
name = "MyPackage"
uuid = "ab86047e-e606-11e9-020a-1d793344fa1e"
version = "0.1.0"
```

Running the following in the REPL does not track changes for me: `using Revise` -> `using MyPackage` -> `foo()` -> changes to `foo()` -> run `foo()` again

**Comment by korsbo** [comment]
Thanks for reporting this, simply knowing where my revision issues come from has made my life easier!

**Comment by goretkin** [comment]
I don't think this is exactly the same symptom, but if on `using`/`import`ing a package I get:

```
┌ Warning: Package Geometry does not have GeometryTypes in its dependencies:
│ - If you have Geometry checked out for development and have
│   added GeometryTypes as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Geometry
└ Loading GeometryTypes into Geometry from project dependency, future warnings for Geometry are suppressed.
```

then Revise appears not to track that file. (doesn't show up in `keys(Revise.watched_files)`
