### ISSUE TITLE
Specific package won't revise (but others will)

### ISSUE THREAD

**Issue by kescobo** [timholy/Revise.jl#379]
I have a very strange issue with a specific package of mine that seems resistant to `Revise`ing, when `Revise` seems to work perfectly fine elsewhere.

Steps to reproduce:

```
] dev https://github.com/Klepac-Ceraj-Lab/echo_analysis.git

julia> using Revise

julia> using ECHOAnalysis

julia> resolve_sampleID("C0001_1F_1A_S2")
(sample = "C0001_1F_1A", subject = 1, timepoint = 1)

julia> edit(resolve_sampleID, [String]) # add a print statement

julia> resolve_sampleID("C0001_1F_1A_S2") # same output - nothing printed
(sample = "C0001_1F_1A", subject = 1, timepoint = 1)
```

I've tried this on 2 different machines, installing to the default project or a brand new one, with no luck. At the same time, I was able to go through the docs [example here](https://timholy.github.io/Revise.jl/stable/#Usage-example-1) just fine, and I created a whole new package and got it to work as well. So it seems to be a problem with this package in particular.

**Comment by timholy** [comment]
Any chance you already know how to solve
```
  Building RCall → `~/.julia/packages/RCall/g7dhB/deps/build.log`
┌ Error: Error building `RCall`: 
│ ERROR: LoadError: R_HOME is not a directory.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /home/tim/.julia/packages/RCall/g7dhB/deps/build.jl:44
│  [3] include at ./boot.jl:328 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1105
│  [5] include(::Module, ::String) at ./Base.jl:31
│  [6] include(::String) at ./client.jl:432
│  [7] top-level scope at none:5
│ in expression starting at /home/tim/.julia/packages/RCall/g7dhB/deps/build.jl:10
└ @ Pkg.Operations ~/src/julia-1/usr/share/julia/stdlib/v1.3/Pkg/src/backwards_compatible_isolation.jl:649
```

**Comment by kescobo** [comment]
Ugh - yeah. There's [info here](http://juliainterop.github.io/RCall.jl/stable/installation.html#Customizing-the-R-installation-1), but it can be a bit annoying though. 

Maybe try to explictly add RCall to your environment, then `] build RCall`? I use my own R installation on both linux and mac, and followed the instructions

```
ENV["R_HOME"]=""
ENV["PATH"]="....directory of R executable..."
Pkg.build("RCall")
```

If this takes you more than a few minutes to solve, let me know and I'll try to make a branch where I strip out the requirements for RCall.

**Comment by kescobo** [comment]
I think I've removed the RCall requirements from [this branch](https://github.com/Klepac-Ceraj-Lab/echo_analysis/tree/no-r), and I did the above test and it still doesn't work.

**Comment by timholy** [comment]
Does ECHOAnalysis recompile for you each time you use it? For me it does. Specifically I get this:
```julia
julia> using ECHOAnalysis
[ Info: Precompiling ECHOAnalysis [39b5b81a-5017-403f-bb48-824a42db2b1c]

julia> id = Base.PkgId(ECHOAnalysis)
ECHOAnalysis [39b5b81a-5017-403f-bb48-824a42db2b1c]

julia> paths = Base.find_all_in_cache_path(id)
1-element Array{String,1}:
 "/home/tim/.julia/compiled/v1.3/ECHOAnalysis/kIyeq_tZjuv.ji"

julia> sourcepath = Base.locate_package(id)
"/home/tim/.julia/dev/ECHOAnalysis/src/ECHOAnalysis.jl"

julia> Base.stale_cachefile(sourcepath, first(paths))
true
```
This looks like a Julia bug.

**Comment by timholy** [comment]
If I move your [`include_dependency`](https://github.com/Klepac-Ceraj-Lab/echo_analysis/blob/4837c275c4766824fde2b82292ef4302f46131a3/src/ECHOAnalysis.jl#L46) to a point after the `include`s, it fixes the problem for me. Can you confirm?

**Comment by kescobo** [comment]
>If I move your `include_dependency` to a point after the includes, it fixes the problem for me. Can you confirm?

Yes! Interesting.

>Does ECHOAnalysis recompile for you each time you use it? For me it does.

It does frequently, I assumed it was because I'm constantly switching projects and developing some of the dependencies, but never looked into it. Copying and pasting your code above, I get the same results on my main development branch. This is after moving the `include_dependency`, though these are probably unrelated problems?

**Comment by timholy** [comment]
> This is after moving the `include_dependency`

Double-checking, you're saying that on your development branch, moving the `include_dependency` isn't enough to fix it? Interesting. What if you drop the `include_dependency` altogether?

> though these are probably unrelated problems?

Revise will punt if the cache is stale, which is why it's not revising. And Base should rebuild it if the cache is deemed stale.

It seems that Julia is building a corrupt `*.ji` precompile file. This is definitely worth filing as a Julia bug.

**Comment by kescobo** [comment]
>Double-checking, you're saying that on your development branch, moving the include_dependency isn't enough to fix it? Interesting. What if you drop the include_dependency altogether?

Sorry for confusion. Moving the `include_dependency` after the regular `includes` on my main development branch *does* fix the Revise problem. 

I thought it didn't fix the stale cache thing - the first time I ran your code above I got `true` at the end, but I just reloaded it and now:

```
julia> Base.stale_cachefile(sourcepath, first(paths))
74-element Array{Any,1}:
 Missings
 PooledArrays
 StatsBase
 RecipesBase
 ColorBrewer
 CategoricalArrays
 ColorTypes
 FileWatching
 Tokenize
 ⋮
 SuiteSparse
 Statistics
 StaticArrays
 Main
 CSTParser
 Test
 FixedPointNumbers
 Unicode
 DataAPI
```

I think when I checked it the first time, it was after modifying a file to check on Revise, so maybe that was it. So I think this specific problem is solved.

Should I report the fact that it remains stale with the `include_dependency` at the beginning? Would that be in Pkg?

**Comment by timholy** [comment]
Glad to hear we now have a good workaround.

> Should I report the fact that it remains stale with the include_dependency at the beginning?

Yep.

> Would that be in Pkg?

Base Julia. (It's probably a bug in either `src/dump.c` or `base/loading.jl`.) Ping me on your bug report and I can chime in with any missing details.

**Comment by timholy** [comment]
I'll close here since the fix is elsewhere.
