### ISSUE TITLE
Revise >= v2.2.0 does not detect changes 

### ISSUE THREAD

**Issue by tencnivel** [timholy/Revise.jl#381]
Hello, Revise works fine until v2.1.10

After this version it doesn't take into account the changes in my projects

I am working with Julia 1.2.

I have attached ~/.julia/environments/v1.2/Manifest.toml and an example of project's Manifest.toml

[~/.julia/environments/v1.2/Manifest.toml](https://github.com/timholy/Revise.jl/files/3816150/environments_v1.2_Manifest.toml.txt)
[project's Manifest.toml](https://github.com/timholy/Revise.jl/files/3816156/project_Manifest.toml.txt)

**Comment by ExpandingMan** [comment]
Any chance this is related to #383?  Do you get any warnings at all?

**Comment by timholy** [comment]
If #385 didn't fix this, please reopen and provide additional detail.
