### ISSUE TITLE
Suggestion: Don't track non-dev packages

### ISSUE THREAD

**Issue by ianshmean** [timholy/Revise.jl#384]
There might be wrong assumptions in here, and it may not be a new idea.. I just thought I'd share the thought..

I have Revise loaded automatically, and if I do something like `using Package` then `pkg> update` it can quite often cause a wall-of-text style Revise warning report. I imagine that practice is common.

It seems like expecting Revise to survive through `using Package` and then a `pkg> update` or `pkg> add Package#master` etc. might be too challenging? 

I'm just wondering whether packages that are loaded that aren't dev-ed should even be tracked, given they are conceptually _read-only_, and whether it would just be simpler to give a warning if Revise notices that a non-dev package that's loaded has been changed, something like:
```
Package Package was changed, but has not been dev-ed, so changes aren't tracked by 
Revise. Reload session to use new version of Package
```

Edit: On second thought, maybe this is shortsighted.. if Revise _can_ handle it well, then it should

**Comment by timholy** [comment]
There are changes it does handle. I agree that it's also a problem.

Best fix is to close the remaining limitations of Revise. #255 hopefully was one big step along the way. Type-changes are probably the biggest remaining hurdle.

**Comment by timholy** [comment]
I think I'll close this. There aren't many things left it can't handle, and it's very useful to be able to toggle between `add` and `dev` mode. Moreover it provides incentive to finally find an acceptable solution to type redefinition.
