### ISSUE TITLE
Revise issues with VS Code

### ISSUE THREAD

**Issue by calum6371** [timholy/Revise.jl#396]
Hi, first thanks for writing Revise.jl it's been a huge help and time saver while developing packages!  I have been using it for a few months on VisualStudio Code (windows) however over the weekend it has stopped working and I can’t figure out why.

I’m on Julia v1.2 and Revise v2.2.2. My config/startup.jl should load Revise. e.g.
```
atreplinit() do repl
    try
        ENV["JULIA_REVISE"] = "manual"
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
    catch
    end
end
```

I’ve also tried the VSCode workaround version you mentioned in another post [here](https://github.com/julia-vscode/julia-vscode/wiki/Known-issues-and-workarounds).

I usually invoke my script on the VS Code REPL. e.g. include("myfile.jl") after changing some functionality in MyPackage but now the changes are not being registered without a full recompile which is wasting lots of time.

Any suggestions on how to solve this? Thanks!

**Comment by KristofferC** [comment]
What if you do an explicit `Revise.revise()`. I think the VSCode extension does some custom code execution now which might prevent the Revise hook from automatically running.

**Comment by calum6371** [comment]
> What if you do an explicit `Revise.revise()`. I think the VSCode extension does some custom code execution now which might prevent the Revise hook from automatically running.

This appears to have worked, thank you!

**Comment by timholy** [comment]
ideally this should be automatic, see #325. If you know how to fix it...
