### ISSUE TITLE
type SSAValue has no field code

### ISSUE THREAD

**Issue by mattuntergassmair** [timholy/Revise.jl#398]
Since `Revise.jl` v2.3.1, I am getting the following warning + error and Revise stops working:

```
Error: Failed to revise .../src/foo.jl
  exception =
   type SSAValue has no field code
   Stacktrace:
    [1] getproperty(::Any, ::Symbol) at ./Base.jl:20
    [2] find_corrected_name(::JuliaInterpreter.Frame, ::Int64, ::Symbol, ::Symbol) at /home/.../.julia/packages/LoweredCodeUtils/LmOAM/src/LoweredCodeUtils.jl:388
@ Revise ~/.julia/packages/Revise/Mlh6Z/src/Revise.jl:614
Warning: Due to a previously reported error, the running code does not match saved version for the following files:
  .../src/foo.jl
@ Revise ~/.julia/packages/Revise/Mlh6Z/src/Revise.jl:622
foo() = 42
```
Downgrading to v2.2.2 solved the problem for me. Unfortunately I cannot provide a minimal code example to reproduce the error, I am working in a large code base with many custom types and could not dissect the issue sufficiently. But - after commenting out a large part of the functional code - the content of `foo.jl` is the following:
```
foo() = 42
@with_kw struct MyStruct
    a::Float64
    b::Int64
end
```
Removing the struct and just having `foo()` in the file fixes the issue.

**Comment by timholy** [comment]
Can you remind me where `@with_kw` lives?

**Comment by fredrikekre** [comment]
Parameters.jl

**Comment by timholy** [comment]
Thanks!

I can't reproduce this, unfortunately. Can you `dev LoweredCodeUtils` and add a `@show body` right after [this line](https://github.com/JuliaDebug/LoweredCodeUtils.jl/blob/ac92660429f83f1fc3c7fb3e0af6a90ba964c873/src/LoweredCodeUtils.jl#L385)? And then paste the result right before the error?

**Comment by mattuntergassmair** [comment]
Ok, tried it out and I get `body = JuliaInterpreter.SSAValue(88)`

**Comment by timholy** [comment]
Oh shoot, that wasn't so useful, sorry. How about replacing that line with
```
@show stmt
body = @lookup(frame, stmt.args[3])
```
(The latter is an attempt to fix the problem.)

**Comment by mattuntergassmair** [comment]
The output is `stmt = :($(Expr(:method, :SimulationLogger, JuliaInterpreter.SSAValue(44), JuliaInterpreter.SSAValue(88))))` but the problem persists (NB: `SimulationLogger` is the struct that lives in `foo.jl` which I called `MyStruct` in the earlier example).

**Comment by timholy** [comment]
Why doesn't the [`@lookup`](https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/e8f07df463a87cd5b23584cba6c7c6caf12e073b/src/interpret.jl#L28-L68) solve the problem? What new error does it return?

**Comment by mattuntergassmair** [comment]
Sorry, I thought the error was the same as before but it now changed: it now fails on the line `body = @lookup(frame, stmt.args[3])` with the following error message:
```
stmt = :($(Expr(:method, :SimulationLogger, JuliaInterpreter.SSAValue(44), JuliaInterpreter.SSAValue(88))))
┌ Error: Failed to revise .../src/foo.jl
│   exception =
│    UndefRefError: access to undefined reference
│    Stacktrace:
│     [1] getindex at ./array.jl:728 [inlined]
│     [2] lookup_var at ~/.julia/packages/JuliaInterpreter/MXq3U/src/interpret.jl:4 [inlined]
│     [3] macro expansion at ~/.julia/packages/JuliaInterpreter/MXq3U/src/interpret.jl:60 [inlined]
│     [4] find_corrected_name(::JuliaInterpreter.Frame, ::Int64, ::Symbol, ::Symbol) at .../LoweredCodeUtils.jl/src/LoweredCodeUtils.jl:386
└ @ Revise ~/.julia/packages/Revise/0KQ7U/src/Revise.jl:614
```

**Comment by timholy** [comment]
Thanks for the update! This feels like progress.

In the absence of a MWE I may have to ask you to keep poking at it. Brief explanation of what's happening: an SSAValue is essentially a reference to the result of a previous computation. If Revise runs that computation, it's cached. Your `access to undefined reference` suggests that for some reason Revise decided it didn't need to run line 88 (from the `SSAValue(88)`), but then at a later point it needed the result of that line.

The big change in 2.3 is that Revise is more selective about which lines it runs in the interpreter (which is a huge improvement, see https://discourse.julialang.org/t/revise-2-3-0-improved-safety-and-performance-new-features/31069). But of course this introduces a risk of exactly the kind of bug you're reporting here.

The analysis of which "chunks" need to be evaluated in the interpreter happens [here](https://github.com/timholy/Revise.jl/blob/c2a119f07b101fcf4c69f507832855a22dcd59f7/src/lowered.jl#L34); perhaps you could do a `@show chunks` and see whether line 88 is among them. (If not, that will point to a bug somewhere in `backedges.jl`.) If it's not too bad, consider posting the result of
```julia
    JuliaInterpreter.print_framecode(stdout, frame.framecode)
    println("done")
```
inserted before [this line](https://github.com/timholy/Revise.jl/blob/c2a119f07b101fcf4c69f507832855a22dcd59f7/src/lowered.jl#L90) (or anywhere else convenient). The ranges in `chunks` correspond to the `%n` numbers (but there may be several distinct `CodeInfo`s in the same frame).

**Comment by mattuntergassmair** [comment]
Ok, I tried what you suggested: I added Revise in `dev` mode and added `@show chunks` as well as `print_framecode` in the places you pointed to. It seems like execution never hits either of those points, or at least I cannot see the output anywhere. Could it be that Revise errors before that?

PS: If it helps I could give you access to my git repo with instructions on how to reproduce the error?

**Comment by timholy** [comment]
Puzzling.

> PS: If it helps I could give you access to my git repo with instructions on how to reproduce the error?

That would probably be easiest.

**Comment by mattuntergassmair** [comment]
Ok, added you as a collaborator. I also added instructions to reproduce to the README along with contact details in case there are further questions.
PS: to correct my statement from above, the `@show chunks` does get executed, the error was on my side, something went wrong with adding the packages in `dev` mode
