### ISSUE TITLE
Recommended setup.jl configuration leads to error

### ISSUE THREAD

**Issue by IsakFalk** [timholy/Revise.jl#400]
The [documentation on using Revise.jl by deafult](https://timholy.github.io/Revise.jl/stable/config/#Using-Revise-by-default-1) states that adding the following
```julia
atreplinit() do repl
    try
        @eval using Pkg
        haskey(Pkg.installed(), "Revise") || @eval Pkg.add("Revise")
    end
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
    catch
    end
end
```
to the `.julia/config/startup.jl` ensures that every julia Julia session uses it by default.

When I add this and fire up `julia` in `zsh` leads to the following output
```sh
ERROR: LoadError: syntax: try without catch or finally
Stacktrace:
 [1] top-level scope at /home/isak/.julia/config/startup.jl:5
in expression starting at /home/isak/.julia/config/startup.jl:5
```
Following the error and adding a `catch` statement to the first `try` clause seem to resolve it. I am on Julia version `1.2.0`.

**Comment by IsakFalk** [comment]
Seems like the latest commit fixes this, but for some reason the online docs aren't up to date.

**Comment by fredrikekre** [comment]
https://timholy.github.io/Revise.jl/dev/config/#Using-Revise-by-default-1

**Comment by timholy** [comment]
Sorry for the inconvenience, @IsakFalk. This will be fixed when I tag the next release later this morning.

**Comment by timholy** [comment]
Actually, it won't because the documentation won't build because of https://github.com/JuliaLang/Pkg.jl/issues/1514.

I could allow failures on nightly, but I don't like to do that. Too many people use Revise for developing Julia itself, I want to be sensitive to things that need to be updated for the latest development version of Julia.
