### ISSUE TITLE
"Revise is not watching" warning when using Plots.jl and __init__-function

### ISSUE THREAD

**Issue by jaakkor2** [timholy/Revise.jl#403]
Following module
```julia
module debug_plotsrevise
using Plots
function __init__()
	pyplot()
end
function hey()
	plot(rand(10))
end
end # module
```
gives a warning
```
julia> using debug_plotsrevise
julia> ┌ Warning: C:\Users\jaakkor2\.julia\packages\Plots\2KhB2\src\Plots.jl\ is not an existing directory, Revise is not watching
└ @ Revise C:\Users\jaakkor2\.julia\packages\Revise\2NCCI\src\Revise.jl:488
```
Versions I have are Julia v1.3.0, Revise v2.3.2, Plots v0.28.2, PyPlot v2.8.2.

Even an empty `__init__`-function in the module causes the warning.

I think the warning started with Plots v0.28.0 (but I could be mistaken).

**Comment by timholy** [comment]
Sorry for the delay in addressing this. Fix coming in #406.
