### ISSUE TITLE
Icon/logo/wordmark

### ISSUE THREAD

**Issue by cormullion** [timholy/Revise.jl#405]
A trivial issue about this great package... 

I noticed that the main [Julia website](https://julialang.org) shows the Revise wordmark in a  squashed form:

<img width="552" alt="Screenshot 2019-12-07 at 14 01 04" src="https://user-images.githubusercontent.com/52289/70375802-3ea34700-18fa-11ea-9bb2-d2de3e8317b6.png">

That aspect ratio isn't ideal, really. I suppose you could keep to a square format by surrounding it with white space

<img width="489" alt="Screenshot 2019-12-07 at 14 06 36" src="https://user-images.githubusercontent.com/52289/70375861-cf7a2280-18fa-11ea-9d4b-c397c37de802.png">

Or you could make a separate squarish icon/logo, things like this (I just sketched up a few ideas):

<img width="400" alt="Screenshot 2019-12-07 at 13 59 18" src="https://user-images.githubusercontent.com/52289/70375876-0d774680-18fb-11ea-8fde-130f814e8228.png">
 
for use on other webpages and documentation. And then, for this page, use the logo, and put the wordmark to the side:

<img width="710" alt="Screenshot 2019-12-07 at 14 25 43" src="https://user-images.githubusercontent.com/52289/70376125-8081bc80-18fd-11ea-9568-24b1d00cfd40.png">

(Although that "z" spelling mistake does look odd to me... :) )

**Comment by timholy** [comment]
Christmas came early for Revise!

These are amazing. Re the spelling mistake, as you probably understand I was trying to convey the act of changing the source-text, but probably not very successfully. The red is often the color chosen in diffs for deletion, and the green for insertion. I'd still like to do something to convey the act of revision, can you think of a clearer way to do this?

Of your wordmarks, I like the first three the best. What's the intent with the second from left on the bottom row? (The one with the three Rs in different shades of gray.)

**Comment by KristofferC** [comment]
Just throwing out an idea but normally when you look at a diff you would see it something like

```diff
-Revize
+Revise
```

With perhaps some extra emphasis on the change from the z to s (darker background for that letter). Perhaps something could be done along that line.

**Comment by cormullion** [comment]
For an icon/logo, the aim is to find something simple and recognizable - it's easier if you avoid overly-literal "explicative" visuals (I don't think anyone asks "What do the three Julia dots stand for?" 😂). 

I think the wordmark (the long text) with the s/z is fine as it is and a cool idea (it's just that it reminds me of the [ise/ize confusion](https://jeremybutterfield.wordpress.com/2016/12/13/ise-or-ize-is-ize-american-2/), which is a problem for some of us Brits). I do think it needs a chunkier font for impact though:

<img width="537" alt="Screenshot 2019-12-08 at 09 58 28" src="https://user-images.githubusercontent.com/52289/70387781-4b2eaa80-19a1-11ea-8591-8d5f8fb88de0.png">

or 

<img width="413" alt="Screenshot 2019-12-08 at 10 03 59" src="https://user-images.githubusercontent.com/52289/70387848-1111d880-19a2-11ea-8819-72ef6cdcb862.png">

the plus/minus signs introduce some confusion...

<img width="432" alt="Screenshot 2019-12-08 at 10 04 21" src="https://user-images.githubusercontent.com/52289/70387856-1d963100-19a2-11ea-801b-bf4eb1f3a712.png">

The trickier one is the icon/logo, which has to find something iconic and suitable in such a compact space. Pursuing the diff idea: 

<img width="275" alt="Screenshot 2019-12-08 at 10 39 46" src="https://user-images.githubusercontent.com/52289/70388251-0efe4880-19a7-11ea-8ba3-e548b5c8ee6a.png">
 
which works less well as it gets smaller. Simpler would be

<img width="253" alt="Screenshot 2019-12-08 at 10 08 13" src="https://user-images.githubusercontent.com/52289/70387900-a745fe80-19a2-11ea-93fe-101aea0deb69.png">

...getting a bit cryptic now? This path leads inevitably to:

<img width="269" alt="Screenshot 2019-12-08 at 10 08 58" src="https://user-images.githubusercontent.com/52289/70387908-c2187300-19a2-11ea-868d-ad418e4b0130.png">

which works fine as long as you already know what it means, like the Nike swoosh ... :)

Perhaps I'll get some inspiration later.

**Comment by timholy** [comment]
I definitely like the chunkier font on the wordmark. And good point about that the icon/logo not needing to be so "explicative."

**Comment by timholy** [comment]
I like https://user-images.githubusercontent.com/52289/70387848-1111d880-19a2-11ea-8819-72ef6cdcb862.png for the wordmark and the upper-left of https://user-images.githubusercontent.com/52289/70375876-0d774680-18fb-11ea-8fde-130f814e8228.png for the logo.

**Comment by timholy** [comment]
xref #411

**Comment by cormullion** [comment]
I started doing a few more in an idle moment over the holiday, but I like the fresh approach! 😂 

![revise1](https://user-images.githubusercontent.com/52289/71547783-64bd8380-299c-11ea-84e7-6cffd364040f.png)

**Comment by timholy** [comment]
Ooh, those are nice! I particularly like the top two in the right column.

**Comment by timholy** [comment]
@cormullion, since there haven't been that many opinions ventured, shall we just pick something and go with it? What are your own preferences? I am happy to take advice when it comes to these matters (unlike you, I have no noteworthy talents in this domain).

**Comment by cormullion** [comment]
Hi Tim - thanks! I'll make a pull request later today (and try not to muck it up this time).😅
