### ISSUE TITLE
A potential logo design

### ISSUE THREAD

**Issue by fungktt** [timholy/Revise.jl#411]
I recently had a go at creating a logo (for Google Code-in) and I was wondering if it looks good and whether I could make some improvements so that it can used somewhere in the project?

![revise potential logo](https://user-images.githubusercontent.com/28962234/71374706-a645db80-25f6-11ea-983d-127b29cfbb47.png)

**Comment by fungktt** [comment]
This is another version with Julia colors!

![REV ISE copy 2](https://user-images.githubusercontent.com/28962234/71377278-4dc70c00-25ff-11ea-977c-4effb4875e6e.png)

**Comment by logankilpatrick** [comment]
I like it!

**Comment by timholy** [comment]
Revise definitely needs a better logo. See also #405.

**Comment by timholy** [comment]
Sorry @fungktt not to use your very generous contribution! I went with #413 instead.
