### ISSUE TITLE
ERROR: no Revise.track recipe for module

### ISSUE THREAD

**Issue by 4lrdyD** [timholy/Revise.jl#414]
Why does `Revise.track(mod)` not work for certain packages?, for instance

```
julia> Revise.track(ArrayFire)
ERROR: no Revise.track recipe for module ArrayFire
Stacktrace:
 [1] error(::String, ::Symbol) at .\error.jl:42
 [2] #_track#29(::Set{Tuple{Revise.PkgData,String}}, ::Function, ::Base.PkgId, ::Symbol) at C:\Users\user\.julia\packages\Revise\UtBAC\src\recipes.jl:77
 [3] #_track at .\none:0 [inlined]
 [4] #track#28 at C:\Users\user\.julia\packages\Revise\UtBAC\src\recipes.jl:12 [inlined]
 [5] track(::Module) at C:\Users\user\.julia\packages\Revise\UtBAC\src\recipes.jl:10
 [6] top-level scope at none:0
```
for several packages I think it works fine

**Comment by timholy** [comment]
That syntax is intended for `Base` and the stdlibs. Just say `using ArrayFire` and it will be tracked automatically.

**Comment by 4lrdyD** [comment]
@timholy, I needed to do `Revise.track (" explicit // path // to // file.jl ")`, so that it recognizes some change, Is this the only way to use to track third-party packages?

**Comment by timholy** [comment]
What do you mean by "3rd-party packages?" Most Julia packages work without any explicit tracking:

- https://timholy.github.io/Revise.jl/stable/#Usage-example-1 (have you tried playing with this demo? It should work just as advertised)
- https://timholy.github.io/Revise.jl/stable/#What-Revise-can-track-1

If you need to track a particular file, is it being loaded in some unconventional way?

**Comment by 4lrdyD** [comment]
@timholy `using Revise` must come before` using Module`!, this is what I had not taken into account, with this everything is ok!, I had packages that started automatically before using `Revise`, that was my problem, thanks and sorry for the inconvenience.
