### ISSUE TITLE
Suggested startup.jl gives a deprecation warning

### ISSUE THREAD

**Issue by visr** [timholy/Revise.jl#415]
The startup.jl as suggested here:
https://github.com/timholy/Revise.jl/blob/4297e4524accc47b31f5c8735e2b28f12f108b59/docs/src/config.md#using-revise-by-default

Gives a deprecation warning from Pkg since Pkg.installed is deprecated:
https://github.com/JuliaLang/Pkg.jl/blob/54eae6c1b591070918a65a581b7ab3a0c6d9d90c/src/Pkg.jl#L530-L540

This could be tweaked to use the new Pkg API on Julia 1.4. @KristofferC wondered, why not simply use something like

```julia
try
    using Revise
    @async Revise.wait_steal_repl_backend()
catch
    @warn "Revise is not installed"
end
```

Ref #370 which also suggests a startup.jl modification.

**Comment by timholy** [comment]
Added in #376. When I tested #370 it caused me problems, but I haven't tested it in a while. We could revert #376.

**Comment by timholy** [comment]
CC @m-wells

**Comment by m-wells** [comment]
Just tested this
```julia
atreplinit() do repl
    try
        @eval using Pkg
        if VERSION > v"1.3"
            "Revise" in getproperty.(values(Pkg.dependencies()), :name) ||
                @eval Pkg.add("Revise")
        else
            haskey(Pkg.installed(), "Revise") || @eval Pkg.add("Revise")
        end
    catch
    end
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
    catch
    end
end
```

**Comment by KristofferC** [comment]
That seems wrong since you can still load Revise even if it is in the v1.x project and that is not your current project (the current suggestion has the same problem).

**Comment by m-wells** [comment]
@KristofferC You're right.  If you call `julia --project=<new project>` this will always try to install `Revise`.  @timholy looks like manually installing `Revise` is the best way and a revert to
```julia
atreplinit() do repl
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
    catch
    end
end
```
is probably the best course of action.

**Comment by m-wells** [comment]
The following would work (with the caveat that the user needs to launch `julia` at least once without `--project=`) 
```julia
atreplinit() do repl
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
    catch
        try
            @eval using Pkg
            if VERSION > v"1.3"
                "Revise" in getproperty.(values(Pkg.dependencies()), :name) ||
                    @eval Pkg.add("Revise")
            else
                haskey(Pkg.installed(), "Revise") || @eval Pkg.add("Revise")
            end
        catch
        end

        try
            @eval using Revise
            @async Revise.wait_steal_repl_backend()
        catch
        end
    end
end
```

**Comment by KristofferC** [comment]
I would say that there is little to gain for the startup script to try to automatically install Revise. So just a try catch and a warning if it fails to load.

**Comment by m-wells** [comment]
I included the other code snippet for completeness but I think it is probably best to revert to the old style (with a warning in the catch block).
