### ISSUE TITLE
try again automatically after interrupt

### ISSUE THREAD

**Issue by tpapp** [timholy/Revise.jl#418]
Sometimes a <kbd>Ctrl-C</kbd> after a command interrupts Revise, not the actual calculation. After this, the user repeatedly gets
```julia
^C┌ Error: Failed to revise /home/tamas/research/redacted/src/utilities.jl
│   exception = InterruptException:
└ @ Revise ~/.julia/packages/Revise/S7mrl/src/Revise.jl:590
┌ Warning: Due to a previously reported error, the running code does not match saved version for the following files:
│ 
│   /home/tamas/research/redacted/src/utilities.jl
│ 
│ Use Revise.errors() to report errors again.
└ @ Revise ~/.julia/packages/Revise/S7mrl/src/Revise.jl:639
```

Suggestion: special case `InterruptException` and try again.

**Comment by timholy** [comment]
Writing tests for this class of errors is SOO much fun...

I guess the key issue is that it doesn't try again to fix it without you touching the file in some way?

**Comment by tpapp** [comment]
Yes. If it tried again automatically next time revision is triggered, that would be nice.
