### ISSUE TITLE
REPL auto mode not working

### ISSUE THREAD

**Issue by getzdan** [timholy/Revise.jl#42]
Can't get automatic `revise()` calls from the REPL to work.

The following is a M(not)WE:

test_revise.jl
```
using Revise

include("./test_module.jl")
using ReviseTestModule

Revise.track(ReviseTestModule, joinpath(dirname(Base.source_path()),"test_module.jl"))
```
test_module.jl
```
module ReviseTestModule
export testfunc
testfunc(x) = x^2 + 1
end
```

And the REPL session (with version info embedded)
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.1257 (2017-08-06 00:04 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit ae17198720* (37 days old master)
|__/                   |  x86_64-linux-gnu

julia> include("test_revise.jl")

julia> testfunc(0)
1
####### changing test_module.jl here to have `testfunc(x) = x^2 + 2`
julia> testfunc(0)    ## should recompile and return 2
1
```

The Package tests run fine. But, admittedly, it is hard to automatically test an interactive REPL. And as evolutionary bugology dictates this is where bugs will hide. Seems `steal_repl_backend()` is running alright, but there is both `Base.active_repl` and `Base.active_repl_backend` which left me confused. Anybody else seeing this? Is it reproducing? Which versions are afflicted?

**Comment by timholy** [comment]
Works for me. If I take `Revise` temporarily out of my `.juliarc.jl` file I can show you:
```julia
julia> using Revise

julia> push!(LOAD_PATH, pwd())
3-element Array{Any,1}:
 "/home/tim/src/julia-1.0/usr/local/share/julia/site/v0.7"
 "/home/tim/src/julia-1.0/usr/share/julia/site/v0.7"      
 "/tmp"                                                   

julia> using ReviseTestModule

julia> testfunc(2)
5

# Now go edit ReviseTestModule.jl and save it
julia> testfunc(2)
6
```
Might the problem be that you didn't name the file according to your module name? I saved your file as `ReviseTestModule.jl` and it all worked without trouble. I didn't try the alternative, so if this matters to you perhaps you can isolate the problem further?

**Comment by getzdan** [comment]
Changes the name to ReviseTestModule, and used `push!(LOADPATH,pwd())` and it still doesn't work automatically. When manually running `revise()` the function gets redefined as needed. Adding the full versioninfo():
```
Julia Version 0.7.0-DEV.1257
Commit ae17198720* (2017-08-06 00:04 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by timholy** [comment]
Weird. OK, before you say `using Revise`, is anything else loaded? Can you insert some debugging statements [here](https://github.com/timholy/Revise.jl/blob/431370153464fe2390e3d3ec484da6fed15dc705/src/Revise.jl#L444) (e.g., `@show dirname latestfiles wf`) and see whether anything gets triggered?

**Comment by getzdan** [comment]
Since `revise()` does get the right files, and I've verified they are watched and detected (by looking at the globals in Revise), my guess is the only problem is the REPL not calling `revise()` on every input. What version of Julia/Revise is working on your side?

**Comment by getzdan** [comment]
It started working. Possibly the module filename was the necessary change. I will try reproducing, but if the bug doesn't reproduce, the issue can be closed.

**Comment by getzdan** [comment]
The problem inducing change was the addition of a `@show backend.backend_task` debug print before and after the assignment to `backend_task` in `steal_repl_backend` I added at some point. Link to location: https://github.com/timholy/Revise.jl/blob/431370153464fe2390e3d3ec484da6fed15dc705/src/Revise.jl#L633-L646 .

But the issue can be closed, I suppose.

**Comment by timholy** [comment]
OK, thanks for tracking it down!

**Comment by getzdan** [comment]
Closed too early. The problem reappeared. I've narrowed it to a simple single line change which causes it.
Again, consider the following files.
`TestModule.jl`
```
module TestModule

export testfunc
function testfunc(;param = 20)
  @show param
end

end
```

and `test_revise.jl`
```
using Revise

include("./TestModule.jl")

using TestModule
Revise.track(TestModule, joinpath(dirname(Base.source_path()),"TestModule.jl"))

testfunc()
```

They produce the problem **but only when `testfunc()` line at the end of `test_revise.jl` is runs**. Commenting out this line and the REPL recompilation works as needed. With it, there is no automatic recompilation, but `revise()` from REPL captures and recompiles the changes.

**Comment by getzdan** [comment]
Update: It isn't related to running the tracked function. Any printout to screen, make the REPL stealing mechanism fail. In the above example `testfunc()` at the end of `test_revise.jl` can be replaced with `println("hello")` and the problem is still reproduced.

**Comment by timholy** [comment]
@getzdan, thanks so much for persisting with this and coming up with a much clearer picture of what's happening.

There's only one problem: your nicely-reduced test case doesn't behave for me the way it does for you---everything works properly for me. So I can't easily fix this.

I am running 0.6 because DataStructures doesn't build on current 0.7. Can you also reproduce this on 0.6? I see that you provided `versioninfo` above, here is mine:
```julia
julia> versioninfo()
Julia Version 0.6.1-pre.0                                                                                                                                                                                                                    
Commit dcf39a1 (2017-06-19 13:06 UTC)                                                                                                                                                                                                        
Platform Info:                                                                                                                                                                                                                               
  OS: Linux (x86_64-linux-gnu)                                                                                                                                                                                                               
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz                                                                                                                                                                                              
  WORD_SIZE: 64                                                                                                                                                                                                                              
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```
Specifically I am running (K)ubuntu 16.04. To me this seems likely to be a libuv bug on your platform, but not sure. Can anyone else reproduce this?

**Comment by timholy** [comment]
I should have thought of this earlier: see #54.
