### ISSUE TITLE
use REPL ast_transforms in Julia 1.5+

### ISSUE THREAD

**Issue by stevengj** [timholy/Revise.jl#423]
In Julia 1.5 or later (https://github.com/JuliaLang/julia/pull/34626), you can just do
```jl
pushfirst!(Base.active_repl_backend.ast_transforms, my_transformation)
```
to tell the REPL to perform arbitrary AST transformations.  (`pushfirst!` will do `ast = my_transformation(ast)` on each parsed `ast` *before* the default `REPL.softscope` transformation in Julia 1.5.)

This should be simpler than your current `steal_repl_backend` machinery, and more importantly it is composable with other code that wants to hook into the REPL.

**Comment by timholy** [comment]
Thanks for doing this, we've needed something like this for a long time.

**Comment by stevengj** [comment]
(Are there other REPL-stealing packages that should be using this mechanism too?)
