### ISSUE TITLE
Load error with duplicate .ji files

### ISSUE THREAD

**Issue by tribut** [timholy/Revise.jl#432]
Hey. This morning, I got the following error when opening a julia prompt:

~~~
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

┌ Warning: Could not load Revise
│   Error =
│    InitError: AssertionError: length(paths) == 1
│    during initialization of module Revise
└ @ Main ~/.julia/config/startup.jl:6
(v1.3) pkg> st
    Status `~/.julia/environments/v1.3/Project.toml`
  [295af30f] Revise v2.5.1 [`~/.julia/dev/Revise`]
~~~

`paths` was `["/home/felix/.julia/compiled/v1.3/JuliaInterpreter/PliIn_Tzgkg.ji", "/home/felix/.julia/compiled/v1.3/JuliaInterpreter/PliIn_dWBvD.ji"]` immediately before, so I moved the `compiled/v1.3/JuliaInterpreter` folder and it went away.

Not sure how I got into this situation, but I guess there is a bug somewhere?

**Comment by timholy** [comment]
Revise is the symptom rather than the cause; precompilation of Revise is handled by Julia, Revise itself has nothing to do with this. If you can figure out how to reproduce it, it would be worth reporting as a Julia issue.

**Comment by tribut** [comment]
Thanks! 

Can you clarify whether the fact that more than one `path` returns something else than `true` for `Base.stale_cachefile(sourcepath, path)` is already a bug?

Because in https://github.com/timholy/Revise.jl/commit/a8f4660a434c726aacb0e58635a5163dc9c78e41, the behavior of Revise seems to have changed from "take the first one that isn't stale" to "throw error if more than one exist".

**Comment by KristofferC** [comment]
Doesn't this just mean that there was more than one precompile file that is non-stale? So in that case, you could take anyone of them? I don't really understand the `@assert` myself and why this is considered a Julia bug.

**Comment by timholy** [comment]
Oh shoot, I missed where this was coming from.
