### ISSUE TITLE
Evaluation error with include()

### ISSUE THREAD

**Issue by tomyun** [timholy/Revise.jl#442]
Just encountered a strange issue when adding Gadfly dependency to my own package. When Gadfly tried including its own source file (`dataframes.jl`), Revise somehow thought this file should be coming from a working directory for my package.

Here are steps to reproduce.

1. Create a new package
```
(v1.3) pkg> generate HelloWorld
Generating project HelloWorld:
    HelloWorld/Project.toml
    HelloWorld/src/HelloWorld.jl

(v1.3) pkg> activate HelloWorld
Activating environment at `~/Projects/HelloWorld/Project.toml`

(HelloWorld) pkg> add DataFrames Gadfly
...
```

2. Edit package source to use DataFrames/Gadfly
```
> cat Helloworld/src/HelloWorld.jl
module HelloWorld

using DataFrames
using Gadfly

end # module
```

3. Try import this package under Revise
```
julia> using Revise

julia> using HelloWorld
[ Info: Precompiling HelloWorld [187c3756-9116-4ca1-bf81-5f69fec3b46a]
(compiled mode) evaluation error starting at /Users/tomyun/Projects/none:0

julia> could not open file /Users/tomyun/Projects/dataframes.jl
julia>
 [1] include at ./boot.jl:328 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1105
 [3] include at ./Base.jl:31 [inlined]
 [4] include at /Users/tomyun/.julia/packages/Gadfly/ISHWw/src/Gadfly.jl:1 [inlined]
 [5] link_dataframes() at /Users/tomyun/.julia/packages/Gadfly/ISHWw/src/mapping.jl:238
 [6] top-level scope at REPL[5]:0
while evaluating
begin
    link_dataframes()
    __pkguuid__ = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
end
in module Gadfly
```

What [link_dataframes()](https://github.com/GiovineItalia/Gadfly.jl/blob/4adfa197ff83fce752684bebf872940418021326/src/mapping.jl#L236) from Gadfly does is just to include one of its own source files (dataframes.jl). A culprit maybe is that this function is conditionally called by [@require](https://github.com/GiovineItalia/Gadfly.jl/blob/4adfa197ff83fce752684bebf872940418021326/src/Gadfly.jl#L66) only when DataFrames is available.
```
function link_dataframes()
    @debug "Loading DataFrames support into Gadfly"
    include("dataframes.jl")
end
```

Not sure if this issue is on Revise or Gadfly (or maybe Requires), I post it here first as it runs fine when Revise is not used.

I'm using Julia 1.3.1 and Revise 2.5.4 on macOS. Gadfly is 1.2.0 and DataFrames is 0.20.2.

```
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```

**Comment by timholy** [comment]
I can replicate this. It may be a few days before I can get to it, apologies for the inconvience!

**Comment by tomyun** [comment]
Confirmed no error message showing up with Revise 2.6.0. Thanks!
