### ISSUE TITLE
Using incorrect precompiled file

### ISSUE THREAD

**Issue by goretkin** [timholy/Revise.jl#447]
I got into some situation where Revise is tracking the wrong files (this was working before, and I'm not really sure how to reproduce this state)

```julia
julia> Revise.pkgdatas[Base.PkgId(GLMakie)].info.basedir
"/Users/goretkin/.julia/dev/GLMakie"

julia> Revise.srcfiles(Revise.pkgdatas[Base.PkgId(GLMakie)])
120-element Array{String,1}:
 "/Users/goretkin/.julia/packages/GLMakie/gMxEB/src/GLMakie.jl"                          
 "/Users/goretkin/.julia/packages/GLMakie/gMxEB/deps/deps.jl" 
....  
```

I'm not familiar with Julia's precompilation stuff, and this might be an error in that. But it looks like `Revise` is peeking into the one file under `/Users/goretkin/.julia/compiled/v1.3/GLMakie`, which is the precompilation artifact for the not-dev instance of `GLMakie`.

**Comment by goretkin** [comment]
Deleting the precompiled file fixed the issue for me. I don't have anything better to add than perhaps there should be an assertion that, if the cached information is used, that the paths should be consistent with the basedir.

On the other hand, it looks like the `srcfiles` are supposed to be relative anyway:
```julia
julia> Revise.srcfiles(Revise.pkgdatas[Base.PkgId(GLMakie)])
30-element Array{String,1}:
 "src/GLMakie.jl"                          
 "deps/deps.jl"
```

so perhaps the assertion should be that there are no absolute paths.

**Comment by timholy** [comment]
Interesting. You didn't `includet` Makie or anything did you? Or was Makie possibly loaded via `@require`? Or were you just doing this with standard `using Makie`?

For debugging this, one option is to [turn on logging](https://timholy.github.io/Revise.jl/stable/debugging/). This is what my startup file looks like:
```julia
    atreplinit() do repl
        try
            @eval using Revise
            @async Revise.debug_logger()
            @async Revise.wait_steal_repl_backend()
        catch e
            @warn(e.msg)
        end
    end
```
I've also pushed a debugging branch, `debug_447`. It fails tests so I can't enable it for general consumption, but it should be pretty reliable. Any chance you can run on that branch for a while and see if it pops up again?

**Comment by goretkin** [comment]
Thanks for taking the time. I'll use this branch from now on see if anything unexpected happens again. I already obliterated the state I was in, so I'm not sure if I'll have anything useful to report.

**Comment by timholy** [comment]
I'll try to keep it up-to-date, at least for a while. I just rebased it on the 2.6.0 release. Given your contributions I assume you're comfortable with git, but don't hesitate to ask if you have trouble updating.

**Comment by goretkin** [comment]
I have a similar situation again. There are stale precompile files from when I did not have `__precompile__(false)` on a project. Now that the project has the statement, the precompile files stay stale.

Yet, Revise still seems to rely on them. When I make some sort of change in an existing file, Revise shows 

```
┌ Warning: /Users/goretkin/projects/GridVAMP/src/visibility.jl no longer exists, deleting all methods
└ @ Revise ~/.julia/packages/Revise/WkyNB/src/Revise.jl:555
┌ Warning: /Users/goretkin/projects/GridVAMP/src/lattice.jl no longer exists, deleting all methods
└ @ Revise ~/.julia/packages/Revise/WkyNB/src/Revise.jl:555
┌ Error: evaluation error starting at /Users/goretkin/projects/GridVAMP/toplevel:17
│   mod = GridVAMP
│   ex =
│    quote
│        #= toplevel:17 =#
│        struct ConfigurationspacePoint{T}
│            #= /Users/goretkin/projects/GridVAMP/src/planning.jl:18 =#
│            q::T
│        end
│    end
│   exception =
│    UndefVarError: ConfigurationspacePoint not defined
```

yet the only reference to  e.g. `/Users/goretkin/projects/GridVAMP/src/visibility.jl` that exists is inside the `.ji` files.


```julia
julia> gv = collect(keys(Revise.pkgdatas))[2]
┌ Warning: Due to a previously reported error, the running code does not match saved version for the following files:
│ 
│   /Users/goretkin/projects/GridVAMP/src/planning.jl
│   /Users/goretkin/projects/GridVAMP/src/domains.jl
│ 
│ Use Revise.errors() to report errors again.
└ @ Revise ~/.julia/packages/Revise/WkyNB/src/Revise.jl:660
GridVAMP [e2a18fb8-4a0f-4b9e-a519-a2cfeccb4106]

julia> Revise.pkgdatas[gv]
┌ Warning: Due to a previously reported error, the running code does not match saved version for the following files:
│ 
│   /Users/goretkin/projects/GridVAMP/src/planning.jl
│   /Users/goretkin/projects/GridVAMP/src/domains.jl
│ 
│ Use Revise.errors() to report errors again.
└ @ Revise ~/.julia/packages/Revise/WkyNB/src/Revise.jl:660
PkgData(GridVAMP [e2a18fb8-4a0f-4b9e-a519-a2cfeccb4106]:
  "src/GridVAMP.jl": FileInfo(Main=>ExprsSigs(<0 expressions>, <0 signatures>), with cachefile /Users/goretkin/.julia/compiled/v1.3/GridVAMP/9ppnX_Y4mSH.ji)
  "src/grid_geometry.jl": FileInfo(GridVAMP=>ExprsSigs(<0 expressions>, <0 signatures>), with cachefile /Users/goretkin/.julia/compiled/v1.3/GridVAMP/9ppnX_Y4mSH.ji)
  "src/lattice.jl": FileInfo(GridVAMP=>ExprsSigs(<0 expressions>, <0 signatures>), with cachefile /Users/goretkin/.julia/compiled/v1.3/GridVAMP/9ppnX_Y4mSH.ji)
  "src/planning.jl": FileInfo(GridVAMP=>ExprsSigs(<38 expressions>, <0 signatures>), with cachefile /Users/goretkin/.julia/compiled/v1.3/GridVAMP/9ppnX_Y4mSH.ji)
  "src/visualize.jl": FileInfo(GridVAMP=>ExprsSigs(<0 expressions>, <0 signatures>), with cachefile /Users/goretkin/.julia/compiled/v1.3/GridVAMP/9ppnX_Y4mSH.ji)
  "src/visibility.jl": FileInfo(GridVAMP=>ExprsSigs(<0 expressions>, <0 signatures>), with cachefile /Users/goretkin/.julia/compiled/v1.3/GridVAMP/9ppnX_Y4mSH.ji)
  "src/domains.jl": FileInfo(GridVAMP=>ExprsSigs(<0 expressions>, <0 signatures>), with cachefile /Users/goretkin/.julia/compiled/v1.3/GridVAMP/9ppnX_Y4mSH.ji)
```

I ran it with https://github.com/timholy/Revise.jl/commit/53bc3632111900b3e09146bb531d190fbabbf328 and got the errors above.

Running with `master` did the right thing! Maybe it is being handled by [`filter_valid_cachefiles`](https://github.com/timholy/Revise.jl/pull/460) now.

It seems like this issue is resolved, then.

**Comment by timholy** [comment]
Just to check, did you switch from precompiled to non-precompiled within a single Julia session? I can understand how that might contribute to problems, because Revise handles the two *very* differently. Quoting from https://timholy.github.io/Revise.jl/stable/internals/,
> prepare source-code caches for every new file. These caches will allow Revise to detect changes when files are updated. For precompiled packages this happens on an as-needed basis, using the cached source in the `*.ji` file. For non-precompiled packages, Revise parses the source for each included file immediately so that the initial state is known and changes can be detected.

(The "lazy parsing" for precompiled packages is an absolutely crucial performance optimization, Revise would be incredibly frustrating without it.) If the [cachefile field](https://github.com/timholy/Revise.jl/blob/26f14fe951631f4dd33bab83b26dc1d5e5e84dcb/src/types.jl#L93) still points to the original `*.ji`, then Revise will probably keep using it. This is fixable by (1) recognizing when a change to a file makes the package non-precompilable, and responding by (2) defensively parsing all the previously-unparsed source files and then clearing the cachefile field.

It's a pretty niche case, so won't be high on the priority list, but perhaps we can at least clarify now whether that's all that's happening? What happens if you start a fresh Julia session and have made changes since declaring it `__precompile__(false)`? If any of these problems crop up, that's a sign of some other (probably more serious) bug.

**Comment by goretkin** [comment]
> Just to check, did you switch from precompiled to non-precompiled within a single Julia session?

No, the issue I was having persisted through a fresh julia session. The only way I was able to fix it was by deleting the `.ji` file.

I can try to reproduce it with the sequence that got me into the state, so that there's an actual reproducer instead of this `tar` file of `ji` files that are not that useful. Probably won't be today.

**Comment by timholy** [comment]
Since `master` fixed it, I think (?) from the problem description we can declare this fixed. By all means, please let me know if it affects you again!
