### ISSUE TITLE
Get "surface" AST from Revise since tracks expr & changes?

### ISSUE THREAD

**Issue by robertfeldt** [timholy/Revise.jl#458]
Thanks for `Revise`, it is amazing. I'm looking for ways to instrument Julia code. I'd rather use the "surface" AST rather than lowered code. It seems to me that `Revise` might be saving the surface AST for the modules/files/functions it is tracking. Is there any way to get the surface AST for a function from these intermediate `Revise` data structures?

**Comment by timholy** [comment]
See [CodeTracking.jl](https://github.com/timholy/CodeTracking.jl), which is a formal API for doing what you want.

**Comment by robertfeldt** [comment]
Thanks, Tim. I provide example code for others that might be later looking for something similar:

```
julia> using CodeTracking

julia> function t(x, y)
         if x > y
           return x
         else
           return x+y
         end
       end
t (generic function with 1 method)

julia> m = @which t(1, 2)
t(x, y) in Main at REPL[21]:2

julia> definition(m)
quote
    #= REPL[21]:1 =#
    function t(x, y)
        #= REPL[21]:2 =#
        if x > y
            #= REPL[21]:3 =#
            return x
        else
            #= REPL[21]:5 =#
            return x + y
        end
    end
end
```
