### ISSUE TITLE
Can't load release 2.6.1: UndefVarError: line_is_decl not defined

### ISSUE THREAD

**Issue by jeremiedb** [timholy/Revise.jl#461]
I couldn't load the latest Revise release (v2.6.1) using Julia 1.3.1 (Ubuntu 18). 

```julia
julia> using Revise
[ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
ERROR: LoadError: UndefVarError: line_is_decl not defined
Stacktrace:
 [1] include at ./boot.jl:328 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1105
 [3] include(::Module, ::String) at ./Base.jl:31
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:330 [inlined]
 [6] eval(::Expr) at ./client.jl:425
 [7] top-level scope at ./none:3
in expression starting at /home/jeremie/.julia/packages/Revise/C272c/src/Revise.jl:17
ERROR: Failed to precompile Revise [295af30f-e4ad-537b-8983-00126c2a3abe] to /home/jeremie/.julia/compiled/v1.3/Revise/M1Qoh_XTlTm.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1283
 [2] _require(::Base.PkgId) at ./loading.jl:1024
 [3] require(::Base.PkgId) at ./loading.jl:922
 [4] require(::Module, ::Symbol) at ./loading.jl:917
```

Environment contains only Revise: 

```julia
(MLJtest) pkg> st
    Status `~/Evovest/MLJtest/Project.toml`
  [295af30f] Revise v2.6.1
```

**Comment by timholy** [comment]
What version of CodeTracking do you have? (`pkg> st CodeTracking`) It shouldn't be able to install Revise 2.6.1 unless you have the right version of CodeTracking.

**Comment by timholy** [comment]
And no, it doesn't need to be exported, see https://github.com/timholy/Revise.jl/blob/99c2955fe7b8750ecc4af92d8a19fedc390a4319/src/Revise.jl#L17

**Comment by KristofferC** [comment]
Might be loaded by eg Juno at a different version or put into a sysimage or something along those lines.

**Comment by jeremiedb** [comment]
Good news is that error no longer shows. But it's a complete mystery: neither Manifest or Project files were modified since last attempts that resulted in the above loading error. Manifest shows CodeTracking version = "0.5.9". 

`pkg> st CodeTracking` resulted in: 
```
ERROR: The following package names could not be resolved:
 * CodeTracking (da1fd8a2-8d9e-5ec2-8556-3022fb5608a2 in manifest but not in project)
Please specify by known `name=uuid`.
```
I'm perplexed about root cause. I was working from Juno, @KristofferC, how could it be related to the IDE?

I'll close as the error no longer shows. Thanks for the help.

**Comment by timholy** [comment]
A possibility just occurred to me: you had a package update in your running session, and both CodeTracking and Revise updated simultaneously. In performing the updates, perhaps Revise updated itself before updating CodeTracking. Revise doesn't currently have any rules to determine the order in which packages are "serviced."

It would be nice to come up with a test case for this, just to be sure that this problem is real. But in anticipation of success, @KristofferC, is there an easy way to leverage Pkg to figure out a plausible order based on dependencies?
