### ISSUE TITLE
`entr` for all files

### ISSUE THREAD

**Issue by bogiebro** [timholy/Revise.jl#469]
Is there currently a way for `entr` to call a function when any file tracked by Revise changes, rather than just those specified explicitly?

**Comment by timholy** [comment]
Would be pretty easy to implement, just add a keyword argument that adds all files in `Revise.pkgdatas`. Marking as "help wanted."

This would have to be implemented in an `entr`-specific manner (which makes it much easier). For ordinary revisions (i.e., not `entr`), Revise is very deliberate about waiting until the next command is issued from the REPL, and I wouldn't approve changing that.
