### ISSUE TITLE
Bug in `entr` call to `watch_folder`

### ISSUE THREAD

**Issue by bogiebro** [timholy/Revise.jl#470]
Line 822 of Revise.jl calls `FileWatching.watch_folder`. It then calls `ret.changed` on the result. But `FileWatching.watch_folder` returns a pair:

```julia
julia> FileWatching.watch_folder("src")
"extra.jl" => FileWatching.FileEvent(false, true, false)
```
As the documentation says:
> The returned value is an pair where the first field is the name of the changed file (if available) and the second field is an object with boolean fields changed, renamed, and timedout, giving the event.

Should be an easy fix. I'll make a pull request.

**Comment by ffevotte** [comment]
I think this is now fixed by #488
