### ISSUE TITLE
includet removes equal code in same module scope

### ISSUE THREAD

**Issue by sebastianpech** [timholy/Revise.jl#475]
This is kind of a strange error. I made an MWE:

File `revise_incl.jl`
```
a = 0.8
a = 0.7
a = 0.8
```

In the REPL:
```
julia> using Revise
julia> includet("revise_incl.jl")
julia> a
0.7 # I'm expecting 0.8 here
```

Change content of `revise_incl.jl` to
```
a = 0.81
a = 0.7
a = 0.8
```

In the REPL:
```
julia> using Revise
julia> includet("revise_incl.jl")
julia> a
0.8 # now it gives the expected result
```
It seems, that if a variable has the same value assigned, that second assignment is ignored.

**Comment by sebastianpech** [comment]
hmm, I added a `@show` to every line in `revise_incl.jl` and in the first version with the two equal lines, the second doesn't event run.

**Comment by timholy** [comment]
Congratulations, you've found a real-world case of #249. The current bug is actually just a safeguard to keep from crashing Julia on other types of code that does similar kinds of things. I'm not saying there's not an immediate bandaid that could be applied, but it opens the door to some really scary stuff so my plan is to fix it by building up the infrastructure to be certain we always get correct behavior.

For now, the best answer is: separate "real" code out into packages, and just `include` (not `includet`) scripts.

**Comment by sebastianpech** [comment]
Yay ... Thanks for the explanation.
