### ISSUE TITLE
AstroBase.Bodies is a pathological case again

### ISSUE THREAD

**Issue by helgee** [timholy/Revise.jl#479]
As the title states, I successfully managed to completely destroy Revise's performance when revising `AstroBase.Bodies` again 😅 . Most of the work is done in this [macro](https://github.com/JuliaAstro/AstroBase.jl/blob/master/src/Bodies/graph.jl#L32) after refactoring.
This is not an immediate problem because I consider this module "done" for now but I guess it might be an interesting benchmark.

### Steps to reproduce

1. `using Revise, AstroBase`
2. Make a change in e.g. [`planets.jl`](https://github.com/JuliaAstro/AstroBase.jl/blob/master/src/Bodies/planets.jl)
3. Wait a looong time... (EDIT: Cancelled after an hour)

**Comment by timholy** [comment]
Sorry about that. I'll guess it was probably 79143f13c47e583e4e799518bec295f27cda75b9, you can try Revise 2.6.4 until this is fixed.
