### ISSUE TITLE
`UndefVarError: linetable not defined` for Julia 1.5.0-beta1

### ISSUE THREAD

**Issue by sloede** [timholy/Revise.jl#506]
I recently switched to Julia 1.5.0-beta1 and have since encountered a weird issue:

In certain projects (e.g., [ToyFHE.jl](https://github.com/JuliaCrypto/ToyFHE.jl), I get an error when I try to use Revise after setting `--project` to the specific package:

```julia
julia> using Revise
[ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
ERROR: LoadError: UndefVarError: linetable not defined
Stacktrace:
 [1] include(::Function, ::Module, ::String) at ./Base.jl:380
 [2] include(::Module, ::String) at ./Base.jl:368
 [3] top-level scope at none:2
 [4] eval at ./boot.jl:331 [inlined]
 [5] eval(::Expr) at ./client.jl:467
 [6] top-level scope at ./none:3
in expression starting at /home/mschlott/.julia/packages/Revise/tV8FE/src/Revise.jl:16
ERROR: Failed to precompile Revise [295af30f-e4ad-537b-8983-00126c2a3abe] to /home/mschlott/.julia/compiled/v1.5/Revise/M1Qoh_cSnZ6.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
```
It only happens for some projects, it does not occur if I start the REPL without a project set, and I do not have the same issue for Julia 1.4.0. Any idea what could cause the problem? (If this is not a Revise issue but a project-specific issue, please let me know and I'll move this issue there).

**Comment by timholy** [comment]
You've got a stale `Manifest.toml` somewhere, perhaps in `.julia/dev/Revise` itself.

**Comment by sloede** [comment]
Thank you for the fast reaction. I only use vanilla `Revise` from the registry, so no `dev` version etc. That means I should probably try to get in touch with the authors of the issue-causing packages, right?

**Comment by timholy** [comment]
Maybe elsewhere then, maybe even ToyFHE? Also if you're using Juno then #507, #508 might be relevant.

**Comment by sloede** [comment]
Not using Juno, but thanks for the hint!
