### ISSUE TITLE
MethodError when using Revise

### ISSUE THREAD

**Issue by LouiseDyson** [timholy/Revise.jl#507]
I'm continually getting the error: MethodError: Cannot `convert` an object of type Tuple{LineNumberNode,Expr} to an object of type Array{Tuple{LineNumberNode,Expr},1}

This seems to happen no matter what I'm trying to revise. For example doing the Usage Example [from the doc](https://timholy.github.io/Revise.jl/stable/). When I change the Example.jl file to include a function, it gives me the error (paths edited to remove my username): 

```
Error: evaluation error starting at ...\.julia\dev\Example\src\Example.jl:4
│   mod = Example
│   ex =
│    quote
│        #= ...\.julia\dev\Example\src\Example.jl:4 =#
│        hello(who::String) = begin
│                #= ...\.julia\dev\Example\src\Example.jl:9 =#
│                "Hello, $(who)"
│            end
│    end
│   exception =
│    MethodError: Cannot `convert` an object of type Tuple{LineNumberNode,Expr} to an object of type Array{Tuple{LineNumberNode,Expr},1}
│    Closest candidates are:
│      convert(::Type{T}, ::AbstractArray) where T<:Array at array.jl:490
│      convert(::Type{T}, ::T) where T<:AbstractArray at abstractarray.jl:14
│      convert(::Type{T}, ::LinearAlgebra.Factorization) where T<:AbstractArray at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\factorization.jl:53
│      ...
│    Stacktrace:
│     [1] convert(::Type{Union{Missing, Array{Tuple{LineNumberNode,Expr},1}}}, ::Tuple{LineNumberNode,Expr}) at .\missing.jl:69
│     [2] setindex!(::IdDict{Type,Union{Missing, Array{Tuple{LineNumberNode,Expr},1}}}, ::Any, ::Any) at .\abstractdict.jl:583
│     [3] add_signature!(::Revise.CodeTrackingMethodInfo, ::Any, ::LineNumberNode) at C:\Users\dysonl\.julia\packages\Revise\tV8FE\src\Revise.jl:489
└ @ Revise ...\.julia\packages\Revise\tV8FE\src\lowered.jl:106
```
I'm using Revise v2.7.2 on Atom v0.12.15 with Juno v0.8.2 and Example v0.5.4.

**Comment by LouiseDyson** [comment]
Reinstalling everything for the third time seems to have done the trick, but I've still no idea why there was a problem in the first place.

**Comment by timholy** [comment]
Glad you fixed it! I'm not sure what it would have been, but if the problem reappears let me know. Maybe knowing the versions of CodeTracking, JuliaInterpreter, and LoweredCodeUtils would help?

**Comment by AStupidBear** [comment]
I ecountered the same issue several days ago, and I had no idea what's wrong. I added ` @eval Base.convert(::Type{Array{Tuple{LineNumberNode,Expr},1}}, x::Tuple{LineNumberNode,Expr}) = [x]` to `startup.jl` to avoid this error.

**Comment by KristofferC** [comment]
Are all of you using Juno?

**Comment by LouiseDyson** [comment]
I'm using Juno. The versions of CodeTracking, JuliaInterpreter and LoweredCodeUtils I have now are below. Of course this is in the setup where everything seems to work, but I think the only thing I did differently on this install was to make sure it installed Revise before instantiating the rest of the project, so maybe there's some conflict with another package?

[[CodeTracking]]
version = "0.5.11"
[[JuliaInterpreter]]
version = "0.7.19"
[[LoweredCodeUtils]]
version = "0.4.5"

**Comment by timholy** [comment]
It seems like something allowed CodeTracking 1.0 in through the door even though it's not compatible with Revise 2.x.

**Comment by pfitzseb** [comment]
Juno declares compatibility with CodeTracking 1.0, so you'll get the wrong version loaded if you install Revise after Juno has been loaded (or switch to a different environment). "Classic" Juno bug (or rather design-problem), I suppose.

**Comment by timholy** [comment]
The curious part is they had Revise 2.7.2, which explicitly forbids that combination. I would have thought it would have selected a version of Revise from the old days before upper bounds were common.

**Comment by KristofferC** [comment]
>  The curious part is they had Revise 2.7.2, which explicitly forbids that combination.

You can always load bad combinations of packages if you change your active project in between loading packages. So if you load package `X` at version `x`, change to another project and load `Y` that is incompatible with `x`, Julia will still use `X` at `x`  since that is already loaded (even though the current manifest specifies `X` at some other version, compatible with `Y`.

So what frequently happens with Juno is that the dependencies for Juno are loaded first (effectively fixing the version of these packages in the current Julia session). Then the user changes to some active project and loads other packages there. If one of the Juno dependencies are incompatible, then things won't work properly.

**Comment by LouiseDyson** [comment]
Ah that's interesting, and good to know! But I believe I only have one project with one manifest (and was just switching to a new computer). Does Juno / Julia make some default manifest somewhere else that I might have been accidentally loading?

**Comment by KristofferC** [comment]
Juno installs itself and dependencies in the global manifest and loads packages from there when starting.

**Comment by lassepe** [comment]
I am seeing the same but *without* Juno, if I do `using Revise; using Flux`.

I can see in my `Manifest.toml` that `CodeTracking 1.0.0` was loaded even though it should be incompatible with `Revise 2.7.2`. The dependency path for me is: 

`Flux v.0.10.4` -> `CuArrays 2.2.1` -> `CUDAnative 3.1.0` -> `GPUCompiler 0.2.0` -> `Cthulhu 1.1.2` -> `CodeTracking 1.0.0`

I don't understand why this happens though. `Cthulhu 1.1.2` has set
```
[compat]
CodeTracking = "0.5, 1"
```
and `Revise 2.7.2`  has
```
[compat]
CodeTracking = "0.5.9"
```

FYI: I have `Revise` installed in my global environment  and `Flux` in my project (though I think that should not matter for this problem).

**Comment by cstjean** [comment]
I'm seeing this behaviour on VSCode FWIW.
