### ISSUE TITLE
convert an object of type `Tuple{LineNumberNode,Expr}`

### ISSUE THREAD

**Issue by aminya** [timholy/Revise.jl#508]
I get this error in Julia 1.6.0-DEV, when I evaluate a function of a module, or I add some new deps to a module.
```julia
    end
end)MethodError: Cannot `convert` an object of type Tuple{LineNumberNode,Expr} to an object of type Array{Tuple{LineNumberNode,Expr},1}
Closest candidates are:
  convert(::Type{T}, ::AbstractArray) where T<:Array at array.jl:556
  convert(::Type{T}, ::T) where T<:AbstractArray at abstractarray.jl:14
  convert(::Type{T}, ::LinearAlgebra.Factorization) where T<:AbstractArray at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\factorization.jl:58
  ...
Stacktrace:
 [1] convert(::Type{Union{Missing, Array{Tuple{LineNumberNode,Expr},1}}}, ::Tuple{LineNumberNode,Expr}) at .\missing.jl:69
 [2] setindex!(::IdDict{Type,Union{Missing, Array{Tuple{LineNumberNode,Expr},1}}}, 
::Any, ::Any) at .\iddict.jl:72
 [3] add_signature!(::Revise.CodeTrackingMethodInfo, ::Any, ::LineNumberNode) at C:\Users\yahyaaba\.julia\packages\Revise\tV8FE\src\Revise.jl:489)Revise.LogRecord(Error, evaluation error starting at C:\Users\yahyaaba\.julia\packages\FilePathsBase\SZiBu\src\test.jl:609, lowered, Revise_e943ed8b, "C:\Users\yahyaaba\.julia\packages\Revise\tV8FE\src\lowered.jl", 106, (mod=FilePathsBase.TestPaths, ex=begin

```

**Comment by KristofferC** [comment]
https://github.com/timholy/Revise.jl/issues/507

**Comment by timholy** [comment]
As indicated in the issue @KristofferC  linked, version numbers of CodeTracking, JuliaInterpreter, LoweredCodeUtils, and Revise would help, but the key information is whether you're using Juno and whether you did anything to start up or change your environment.

**Comment by aminya** [comment]
Yes, I am inside Juno, and I am using Atom as a direct dependency of some test package.
```julia
pkg> st
  [c52e3926] Atom v0.12.15
  [00ebfdb7] CSTParser v2.4.1-DEV `https://github.com/julia-vscode/CSTParser.jl.git#master`
  [53a63b46] CodeTools v0.7.0
  [ffa9a821] DocumentFormat v3.1.1-DEV `https://github.com/julia-vscode/DocumentFormat.jl.git#master`
  [5789e2e9] FileIO v1.3.0
  [8fc22ac5] FilePaths v0.8.1 `https://github.com/rofinn/FilePaths.jl.git#master`
  [5903a43b] Infiltrator v0.3.0
  [2b0e0bc5] LanguageServer v3.1.1-DEV `https://github.com/julia-vscode/LanguageServer.jl.git#master`
  [295af30f] Revise v2.7.2
  [b3cc710f] StaticLint v4.4.1-DEV `https://github.com/julia-vscode/StaticLint.jl.git#master`
  [fd094767] Suppressor v0.2.0
  [cf896787] SymbolServer v4.5.1-DEV `https://github.com/julia-vscode/SymbolServer.jl.git#master`
  [44cfe95a] Pkg
```

**Comment by timholy** [comment]
I don't know enough about what Juno's doing internally to be very helpful, but I would start by looking for `Manifest.toml` files in some of Juno's dependencies and deleting them.

**Comment by pfitzseb** [comment]
What's the output of `pkg> st -m CodeTracking`?

**Comment by aminya** [comment]
> `st -m CodeTracking`?

```julia
  [da1fd8a2] CodeTracking v0.5.11
```

**Comment by timholy** [comment]
Something, somewhere is using CodeTracking 1, not CodeTracking 0.5. https://github.com/timholy/CodeTracking.jl/commit/afc73a957f5034cc7f02e084a91283c47882f92b

**Comment by aminya** [comment]
I can double-check the Manifest later tonight, but this was what I saw.

**Comment by timholy** [comment]
My point is that something is switching environments on you. Not sure what happens with Juno, but if you're launching Julia with `julia --project`, perhaps search your `.julia/dev` folder for `Manifest.toml` files.

**Comment by micousuen** [comment]
I am using Juno and experiencing this problem for days. Inspired by [julia-vscode/julia-vscode #1283](https://github.com/julia-vscode/julia-vscode/pull/1283#issuecomment-647702535)   My temporary solution for this is in Juno is:

1. In Juno, start a clean REPL. Don't activate your project first, and check if "pkg>st -m CodeTracking" give you a 1.*.* version of CodeTracking then this temp fix might work to you. 
2. Then run "pkg>add CodeTracking@0.5.11". Where 0.5.11 is the version of CodeTracking used in my project Manifest.toml. Make sure you add the same version. 
3. (Optional)Then run "pkg>pin CodeTracking" to avoid further updating. Once this been fixed in the future version, you can run "pkg>free CodeTracking" to unpin it. 
4. exit your current REPL and open a new one. You might notice REPL will recompile Atom package. 
5. Then use as usual. Now you can activate your own project, but some packages might need recompile.

**Comment by timholy** [comment]
Yes, this is a robust solution. Another option is `add Revise@2` followed by `pin Revise`.
