### ISSUE TITLE
Latest master broken

### ISSUE THREAD

**Issue by quinnj** [timholy/Revise.jl#509]
I imagine @timholy is aware, but it seems that https://github.com/JuliaLang/julia/commit/d6d5208d66be637543232bec4b0c79b2811ea1c6 breaks Revse (it's unable to track changes for me at all)

**Comment by timholy** [comment]
Nope, hadn't built master since then. This one looks like it might take a while to fix, but we'll see how it goes.

**Comment by timholy** [comment]
Doesn't fix everything, but https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/412 may help a fair bit. Still got stuff to fix in LoweredCodeUtils and Revise.
