### ISSUE TITLE
Missing site link

### ISSUE THREAD

**Issue by zdroid** [timholy/Revise.jl#512]
This repository's description is missing a website link (probably should be https://timholy.github.io/Revise.jl/stable/).

**Comment by timholy** [comment]
Isn't the blue badge linking there?

**Comment by zdroid** [comment]
To get to the blue badge, I have to scroll past half of the page (and even more on mobile screen). It's intuitive to put it in the description instead.

**Comment by timholy** [comment]
Hmm, I've seen very few packages do that, but it's done now. Thanks for the suggestion!
