### ISSUE TITLE
Could revise update docstrings as well?

### ISSUE THREAD

**Issue by juliohm** [timholy/Revise.jl#517]
I often write docstrings incrementally and check the if they are properly highlighted on the REPL. Could Revise.jl notice changes in docstrings somehow?

**Comment by timholy** [comment]
It should work find (see the `runtests.jl.` file and search for "doc"). The only known bug is #197. You'll have to provide a MWE so I can reproduce the problem you're seeing.

**Comment by timholy** [comment]
Closing due to lack of reproducer.
