### ISSUE TITLE
Revise[3] makes using slower

### ISSUE THREAD

**Issue by PallHaraldsson** [timholy/Revise.jl#542]
Timings on Julia 1.6 master.

The first timing, is `@time` in startup-file to remind me, Revise is running, and how slow it is to start (not too slow, if a one-time cost):

```
$ julia -q -e "@time using PyCall"
  0.685074 seconds (663.64 k allocations: 45.365 MiB, 2.18% gc time)
  2.359309 seconds (3.45 M allocations: 193.523 MiB, 2.56% gc time)

$ julia --startup-file=no -q -e "@time using PyCall"
  1.762603 seconds (2.88 M allocations: 160.599 MiB, 1.63% gc time)
```

You might know about this, but not your users? I've suggested at Julialang to not run the startup file with `-e`. Until then, maybe add logic to disable Revise itself, if not running interactively? I checked, this affects subsequent `using` statements too, e.g. for `using GTK3_jll`. I was hoping it was just a one time cost.

**Comment by timholy** [comment]
It may be the `invokelatest` which are crucial to reducing the startup latency (compare Revise2 and Revise3). Can you benchmark and check?

**Comment by PallHaraldsson** [comment]
Hi again,

A.
I'll respond here to: https://github.com/JuliaLang/julia/issues/37761#issuecomment-699482365
>You seem to imagine all factors are multiplicative.

Actually I don't think that, nor meant to misrepresent your package. I just reported the absolute timing, (again) forgot about this issue I had just reported here, that Revise loads in the background, and distorts your/my timings. Then @tkf showed me (thanks) the absolute timing wasn't that bad. I only meant 4x times slower in that case. Yes, should have rather mentioned/emphasized the difference in absolute times (I hadn't begun to investigate the issue here, couldn't rule out non-constant effect).

However, there does seem to be a multiplacive effect. To simplify, let's say there's a constant 1 (or half sec) overhead, it's seems to be multiplied by each `using`.

I'm not sure if it's frowned upon to respond to a closed issue (I started it! on "my" issue there) or with off-topic, but I'll do it here:

B.
What do you think about making Dict to be OrderedDict? I'm looking into that, and benchmarking, and that's more pressing I think (because of Julia 1.6 deadline) than me looking into the issue with Revise3.

**Comment by PallHaraldsson** [comment]
As I said, both (presumably all non-Revise) packages have overhead with `using` (also roughly, but not fully constant allocations overhead of 362 k vs 204 k (0.19 M)

```
$ time julia --startup-file=no -e '@time using Revise; yield(); @time using DataStructures; @time using PyCall;'
  0.709836 seconds (664.49 k allocations: 45.409 MiB)
  0.537125 seconds (461.94 k allocations: 28.519 MiB)
  1.976841 seconds (3.09 M allocations: 172.853 MiB, 3.91% gc time)

real	0m3,569s
user	0m3,774s
sys	0m0,659s
$ time julia --startup-file=no -e '@time using DataStructures; @time using PyCall;'
  0.112559 seconds (99.91 k allocations: 7.569 MiB)
  1.765622 seconds (2.89 M allocations: 160.666 MiB, 2.27% gc time)

real	0m2,207s
user	0m2,512s
sys	0m0,569s
```

To see it, you must choose packages with non-overlapping dependencies, I seemingly saw no or little effect for OrderedCollections.jl then realized you're including it with Revise.jl itself.

I'm not too worried about the overhead, or fixing it, more that people are aware, or disabling it for production code. See at top.

**Comment by PallHaraldsson** [comment]
A.
What do you think about either i) adding a banner (to stderr?) when `using` or `import`ing:

```
[WARNING] A small constant <1 sec. slowdown because of Revise
```

And, at least for startup. I do have `@time using Revise` to remind me it's running, but ironically, with the time so low by now, I still forget.

Or ii) disable Revise when not running interactively. It would help if you do not get this warning then. Maybe do both, i.e. the former, also interactively as I do not want people to unfairly blame Julia or (other) slow-loading packages.

B.
Are these the only two things Revise does, can, slow down? Plus startup itself.

**Comment by KristofferC** [comment]
Just:

1. Don't load Revise when you don't want to use it? If you only want to use it in interactive mode, only load it in interactive mode (see e.g. https://kristofferc.github.io/OhMyREPL.jl/latest/installation/#Automatically-start-with-Julia.).

2. Make a sysimage with Revise.

**Comment by PallHaraldsson** [comment]
Hmm, why not? I followed the official instructions (as most would): https://timholy.github.io/Revise.jl/stable/config/

and they only have atreplinit() for pre-1.5, so Tim seems to have gone out of his way to simplify.

I'm not thinking of myself (aslo other users that followed the instructions), I changed and it seems to work. I could make a PR for the install info, but why would you ever want either of your packages non-interactive?

Should I rather add atreplinit() or some other way to Revise's __init__()?

**Comment by timholy** [comment]
> To simplify, let's say there's a constant 1 (or plus/minus half sec) overhead, it's seems to be multiplied by each using.

You're still not thinking about this clearly. For example:
```julia
julia> Base.loaded_modules
Dict{Base.PkgId, Module} with 43 entries:
  Logging [56ddb016-857b-54e1-b83d-db4d58db5568]          => Logging
  Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]          => Profile
  TOML [fa267f1f-6049-4f14-aa54-33bafae1ed76]             => TOML
  LibCURL [b27032c2-a3e7-50c8-80cd-2d36dbcbfd21]          => LibCURL
  Sockets [6462fe0b-24de-5631-8697-dd941f90decc]          => Sockets
⋮

julia> using Flux

julia> Base.loaded_modules
Dict{Base.PkgId, Module} with 95 entries:
  ExprTools [e2ba6199-217a-4e67-a87a-7c52f15ade04]         => ExprTools
  Logging [56ddb016-857b-54e1-b83d-db4d58db5568]           => Logging
  Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]           => Profile
  Reexport [189a3867-3050-52da-a836-e630ba90ab69]          => Reexport
⋮
```
So with just "1 using" we actually loaded 52 packages. If there were "1s latency per `using`" then this would have cost us 52s, and that's *way*, *way* off. So far off, the terms in which you seem to be thinking are just wrong.

There is essentially no difference between a `using` you type at the command line and a `using` that gets issued by a package dependency, other than the (constant) overhead of handling the REPL.

> What do you think about either i) adding a banner

No, because by the time people see the banner they will have already paid 0.75 of that 1s. And the next 0.25s only happens if you load a package. Most people will, but sometimes people won't. So the banner would do nothing other than annoy people.

I'll add a note to the docs (see #545) and call this closed.
