### ISSUE TITLE
Julia REPL crash report (it worked 1 week ago)

### ISSUE THREAD

**Issue by Cvikli** [timholy/Revise.jl#544]
I reproduced the issue and found out that running cells cause the issue if the code `using Revise` is used:
So the most minimalist code:
```
#%%
using Revise
#%%
6
#%%
```
Error: 
![image](https://user-images.githubusercontent.com/11393096/94261925-ebef5600-ff32-11ea-96e7-3ab295fdc3d9.png)

Tested Revise version: 
2.7.5 - julia 1.5.1
3.1.2 - julia 1.5.2

**Comment by Cvikli** [comment]
Wow! 
Only the julia-vscode updated I think in the past week! 

That should be the problem! :o :(

**Comment by Cvikli** [comment]
The issue is really hard to get due to the extension crash. If this 1.0.8 version causes the issue, then we have to solve this fast because there should be a lot of people using Revise with vscode.

**Comment by Cvikli** [comment]
I tried to delete the package with hand and reinstall.
Tried 2.7.0, 2.7.6, 2.6.0 with 1.5.1 but each of them fail.

Any idea what should I try? 
Also I faced with this same issue on two computer simultaneously. What is this "world age"?

**Comment by Cvikli** [comment]
I figured out one way to use Revise.

Juno works.

**Comment by timholy** [comment]
You should probably report this to julia-vscode.

**Comment by Cvikli** [comment]
I found some interesting thing, Juno doesn't use revise even if I am writing `using Revise` it, maybe this is the reason it is working in case of Juno.

Can this problem arise when we use Distributed?

**Comment by Cvikli** [comment]
Well, this issue pointed out, we can't do nearly anything without the Revise, testing the architecture is like 500% slower without it. :D

**Comment by Cvikli** [comment]
I reproduced everything on an other machine:
Julia:
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen Threadripper 1950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
Environment:
  JULIA_EDITOR = "/snap/code/44/usr/share/code/code"
  JULIA_NUM_THREADS = 8
```
Packages:
```
  [6e4b80f9] BenchmarkTools v0.5.0
  [336ed68f] CSV v0.7.7
  [052768ef] CUDA v1.3.3
  [d360d2e6] ChainRulesCore v0.9.10
  [5ae59095] Colors v0.12.4
  [864edb3b] DataStructures v0.17.20
  [b552c78f] DiffRules v1.0.1
  [31c24e10] Distributions v0.23.12
  [da5c29d0] EllipsisNotation v0.4.0
  [587475ba] Flux v0.11.1
  [59287772] Formatting v0.4.1
  [c27321d9] Glob v1.3.0
  [a2cc645c] GraphPlot v0.4.3
  [bd48cda9] GraphRecipes v0.5.4
  [cd3eb016] HTTP v0.8.19
  [033835bb] JLD2 v0.2.1
  [2535ab7d] JSON2 v0.3.2
  [98e50ef6] JuliaFormatter v0.9.2
  [aa1ae85d] JuliaInterpreter v0.8.1
  [093fc24a] LightGraphs v1.3.3
  [bdcacae8] LoopVectorization v0.8.26
  [1914dd2f] MacroTools v0.5.5
  [c03570c3] Memoize v0.4.3
  [47be7bcc] ORCA v0.5.0
  [bac558e1] OrderedCollections v1.3.1
  [9b87118b] PackageCompiler v1.2.1
  [d96e819e] Parameters v0.12.1
  [a03496cd] PlotlyBase v0.4.1
  [91a5bcdd] Plots v1.6.6
  [0cf705f9] Redis v1.0.0
  [295af30f] Revise v3.1.2 `https://github.com/timholy/Revise.jl.git#master`
  [104b5d7c] WebSockets v1.5.2
  [e88e6eb3] Zygote v0.5.8
  [8ba89e20] Distributed
```
julia-vscode:
`Julia Insider 1.0.8`
Code:
```
#%%
using Revise
"Loaded"
#%%
"I can't run this CELL due to some revise crash?"
#%%
```
Error:
![image](https://user-images.githubusercontent.com/11393096/94293488-9e88de00-ff5e-11ea-9f16-6bf8280af074.png)
I hope this help you more! If anything I can test, add or anything, let me know!

**Comment by Cvikli** [comment]
I think I found the problem.
```
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:23:33.049Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-47-generic snap
```
The update was about 1 week ago, which is close to equivalent with the day it broke the Revise VsCode cell.

Updated to vscode insider everything works fine. 
```
Version: 1.50.0-insider
Commit: 772aa0723f7f6b04b710bc3a92b7a904b60ef439
Date: 2020-09-28T05:37:11.967Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-47-generic
```

Btw... I don't understand why am I the only one who bumped into this issue.

**Comment by Cvikli** [comment]
Okay, I see there will be something wrong with my setup because it again fails. 

I will try to figure this whole thing out as soon as possible.

**Comment by Cvikli** [comment]
Okay, i found the solution!

settings.json
```
{
    "julia.useRevise": false
}
```
This command broke everything in the settings. Removing it solved the problem. 

What a crazy error! :D

**Comment by timholy** [comment]
Thanks for letting me know! I'll close this but if others come across this, your diagnosis will be very helpful.
