### ISSUE TITLE
consistently fails to revise

### ISSUE THREAD

**Issue by ric-cioffi** [timholy/Revise.jl#547]
I'm not sure when this all started but everything was working fine before updating to 1.5. Since then I have been consistently having problems revising my module. 
I have a local module (somewhat large) that loads a bunch of packages. I load Revise at julia startup, `activate MyModule` and then `using MyModule`. Then, when updating *some* files, not all, in any way (even adding a comment line), Revise gets stuck forever. I then have to manually interrupt the process, and the `InterruptException` seems to always break in the same part, namely on ... `isequal(::Revise.LineSkippingIterator, ::Revise.LineSkippingIterator) at /Users/Riccardo/.julia/packages/Revise/fUuEE/src/relocatable_exprs.jl:101`

Specifically, the error I get is:

```
Error: Failed to revise /Users/Riccardo/.../HACT/src/dep/m3_refreshV.jl
│   exception =
│    InterruptException:
│    Stacktrace:
│     [1] indexed_iterate(::Tuple{Symbol,Int64}, ::Int64, ::Int64) at ./tuple.jl:81
│     [2] isequal(::Revise.LineSkippingIterator, ::Revise.LineSkippingIterator) at /Users/Riccardo/.julia/packages/Revise/fUuEE/src/relocatable_exprs.jl:101
└ @ Revise ~/.julia/packages/Revise/fUuEE/src/Revise.jl:705
```

I have tried to follow the instructions on [debugging revise](https://timholy.github.io/Revise.jl/stable/debugging/) but cannot do so because as soon as things break it becomes basically impossible to run any other commands as Revise seems to always try to update the broken file and gets stuck again, at which point I have to interrupt again and the logger is empty. All of this on julia@v1.5.2 and Revise@v3.1.2

I understand this might not be the most informative bug report but I'm not really sure where to start from.

**Comment by timholy** [comment]
So here's my guess: something about the new environment is incompatible with the version of Revise you started with. See https://github.com/JuliaLang/julia/issues/35663. You could test this by starting in the new environment without loading Revise and then trying to `pkg> add Revise@v...`, where `...` should be the version of Revise you're running when you first launched Julia. If you see a package conflict, that's probably your answer. Alternatively, it's possible that your new environment has a `Manifest.toml` that just needs updating.

**Comment by ric-cioffi** [comment]
In my main environment I have `[295af30f] Revise v3.1.2` and I usually have it load in my `startup.jl` file.
Following your suggestion I commented out the `using Revise` line, then fired up julia and `] activate MyModule; add Revise@v3.1.2` (revise was not in `MyModule`'s environment) but it didn't give me any conflicts. I guess that wasn't the problem.
I tried to `] resolve` from `MyModule`'s and the main environments, no changes were made so the `Manifest.toml` files look ok (if I correctly understood what `resolve` does).

**Comment by timholy** [comment]
But Revise is still broken? (I'm guessing yes.) 

Without a reproducible test case there's nothing I can do, so if you can't generate one you may have to figure this out yourself. Here's what I'd do:
1. `dev Revise`. Make sure you're using the latest master, for the benefit of vscode there was some file restructuring and you definitely don't want the pain and suffering of a difficult rebase if you fix the bug using the old file organization.
2. Insert `return bt` before https://github.com/timholy/Revise.jl/blob/75f3d3e5cbdbd574f5b3efd5b1d257824c39d3d4/src/utils.jl#L187 (that function prevents Revise from showing backtraces containing lots of its own internals, but here you want that)
3. Sprinkle `@show` statements in various places. I'd start with `revise` itself, like `@show pkgdata file` in https://github.com/timholy/Revise.jl/blob/75f3d3e5cbdbd574f5b3efd5b1d257824c39d3d4/src/packagedef.jl#L729 and again in the "Do the evaluation" block just below that. That way at least you'll know what file it's working on when it gets stuck.
4.FYI: the error that gets triggered when you interrupt is in Revise's code for comparing expressions (the `LineSkippingIterator` performs the comparison while ignoring any differences in line numbers between two expressions).

**Comment by ric-cioffi** [comment]
Thanks, I'll try to figure out where the problem is and report back

**Comment by tomyun** [comment]
Kinda relieved to see someone having the issue as with me. I have been experiencing a very similar issue with my own project since upgraded to Revise 3, but didn't have time to look further and instead had to stick with Revise 2 for a while.

After any file was modified after `using Revise`, it'd get stuck forever when revise triggered. Then had to Ctrl-C several times to interrupt and got something like:

```
┌ Error: Exception while generating log record in module Revise at /Users/tomyun/.julia/packages/Revise/fUuEE/src/Revise.jl:705
│   exception =
│    InterruptException:
│    Stacktrace:
│     [1] handle_message(::Logging.ConsoleLogger, ::Base.CoreLogging.LogLevel, ::String, ::Module, ::Symbol, ::Symbol, ::String, ::Int64; maxlog::Nothing, kwargs::Base.Iterators.Pairs{Symbol,Tuple{InterruptException,Array{Union{Ptr{Nothing}, Base.InterpreterIP},1}},Tuple{Symbol},NamedTuple{(:exception,),Tuple{Tuple{InterruptException,Array{Union{Ptr{Nothing}, Base.InterpreterIP},1}}}}}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Logging/src/ConsoleLogger.jl:156
│     [2] macro expansion at ./logging.jl:332 [inlined]
│     [3] errors(::Array{Any,1}) at /Users/tomyun/.julia/packages/Revise/fUuEE/src/Revise.jl:705
│     [4] revise(; throw::Bool) at /Users/tomyun/.julia/packages/Revise/fUuEE/src/Revise.jl:790
│     [5] revise() at /Users/tomyun/.julia/packages/Revise/fUuEE/src/Revise.jl:730
│     [6] #invokelatest#1 at ./essentials.jl:710 [inlined]
│     [7] invokelatest(::Any) at ./essentials.jl:709
│     [8] top-level scope at none:1
│     [9] eval(::Module, ::Any) at ./boot.jl:331
│     [10] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:134
│     [11] repl_backend_loop(::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:195
│     [12] start_repl_backend(::REPL.REPLBackend, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:180
│     [13] run_repl(::REPL.AbstractREPL, ::Any; backend_on_current_task::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:292
│     [14] run_repl(::REPL.AbstractREPL, ::Any) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
│     [15] (::Base.var"#807#809"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:399
│     [16] #invokelatest#1 at ./essentials.jl:710 [inlined]
│     [17] invokelatest at ./essentials.jl:709 [inlined]
│     [18] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:383
│     [19] exec_options(::Base.JLOptions) at ./client.jl:313
│     [20] _start() at ./client.jl:506
└ @ Revise ~/.julia/packages/Revise/fUuEE/src/Revise.jl:705
┌ Warning: The running code does not match the saved version for the following files:
│
│   /Users/tomyun/Projects/Research/Cropbox.jl/src/util/simulate.jl
│
│ If the error was due to evaluation order, it can sometimes be resolved by calling `Revise.retry()`.
│ Use Revise.errors() to report errors again. Only the first error in each file is shown.
│ Your prompt color may be yellow until the errors are resolved.
└ @ Revise ~/.julia/packages/Revise/fUuEE/src/Revise.jl:799
^CERROR: InterruptException:
Stacktrace:
 [1] maybe_set_prompt_color(::Symbol) at /Users/tomyun/.julia/packages/Revise/fUuEE/src/Revise.jl:1173
 [2] revise(; throw::Bool) at /Users/tomyun/.julia/packages/Revise/fUuEE/src/Revise.jl:803
 [3] revise() at /Users/tomyun/.julia/packages/Revise/fUuEE/src/Revise.jl:730
 [4] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [5] invokelatest(::Any) at ./essentials.jl:709
 [6] top-level scope at none:1
```

`Revise.retry()` again stuck forever and Ctrl-C led me to the same stack trace as OP.

```
julia> Revise.retry()
^C┌ Error: Failed to revise /Users/tomyun/Projects/Research/Cropbox.jl/src/util/simulate.jl
│   exception =
│    InterruptException:
│    Stacktrace:
│     [1] indexed_iterate at ./tuple.jl:81 [inlined] (repeats 2 times)
│     [2] isequal(::Revise.LineSkippingIterator, ::Revise.LineSkippingIterator) at /Users/tomyun/.julia/packages/Revise/fUuEE/src/relocatable_exprs.jl:102
└ @ Revise ~/.julia/packages/Revise/fUuEE/src/Revise.jl:705
^C┌ Error: Failed to revise /Users/tomyun/Projects/Research/Cropbox.jl/src/util/simulate.jl
│   exception =
│    InterruptException:
│    Stacktrace:
│     [1] iterate at /Users/tomyun/.julia/packages/Revise/fUuEE/src/relocatable_exprs.jl:73 [inlined]
│     [2] iterate at /Users/tomyun/.julia/packages/Revise/fUuEE/src/relocatable_exprs.jl:71 [inlined]
│     [3] isequal(::Revise.LineSkippingIterator, ::Revise.LineSkippingIterator) at /Users/tomyun/.julia/packages/Revise/fUuEE/src/relocatable_exprs.jl:97
└ @ Revise ~/.julia/packages/Revise/fUuEE/src/Revise.jl:705
```

I'll also try some debugging efforts to figure out the problem.

**Comment by timholy** [comment]
Please reopen if it's not actually fixed by LoweredCodeUtils 1.2.3.

**Comment by ric-cioffi** [comment]
That seems to have fixed it for me. I'll need to double check a couple more cases but that seems to work now. Thanks a lot :)

**Comment by tomyun** [comment]
It seems to work for me too. Thanks!

**Comment by Babber** [comment]
@timholy, could you pleases be a bit more explicit on how to apply your fix? I have the same problem. I installed `LoweredCodeUtils`, but even if I load it with `using LoweredCodeUtils`, I still get the same error message and my module doesn't get revised. I get that the issue is related to `LoweredCodeUtils.methoddefs!`, but what to do with it? Sorry if I overlook something trivial here.
