### ISSUE TITLE
exception = function type in method definition is not a type

### ISSUE THREAD

**Issue by hdavid16** [timholy/Revise.jl#557]
I am having an issue that is difficult to reproduce and I haven't been able to fix. When I make any change to my test.jl file. I get the error below (even when I change a comment line). I should note that line 98 just has an `end` to close a `for` loop. Also, there is no `Function` type declared in the arguments for any of the functions in this file. Any thoughts?

```julia
┌ Error: Failed to revise c:\..\test.jl
│   exception =
│    function type in method definition is not a type
│    top-level scope at c:\...\test.jl:98
│    Revise evaluation error at c:\...\test.jl:98
│ 
└ @ Revise C:\Users\HD\.julia\packages\Revise\qYvgD\src\packagedef.jl:691

**Comment by timholy** [comment]
Without more information, basically no idea. There's a small chance you'll get more hints if you `dev` Revise and follow the instructions to uncomment a line in `trim_toplevel!`. (Just moments ago I pushed a commit documenting this trick, so make sure you're on the latest.)

**Comment by hdavid16** [comment]
Ok. I'll just wait for a future update. I am actually getting Revise to complain about line 98 when I edit other files in the package I'm working on. The only common thing I can find between the files that error upon edit is that they use `ResumableFunctions`. Thanks for your time though...

**Comment by timholy** [comment]
> I'll just wait for a future update.

You mean, you're hoping this will magically be fixed in the future? It might happen, but it will depend on someone finding a reproducer. If you can share your code but it's big, you can make a [gist](https://gist.github.com/) if necessary.

**Comment by hdavid16** [comment]
Unfortunately, I can't share the code at the moment. I'll do some code maintenance on my package and get back to this in the future. You may close the issue if you wish and I'll reopen if I can make the error reproducible.

**Comment by A-ali123** [comment]
https://github.com/timholy/Revise.jl/issues/557#issuecomment-705739257

**Comment by hdavid16** [comment]
@timholy, I have now put together a very simple example to reproduce this error. I put it in the following repo: https://github.com/hdavid16/ReviseResumable.jl

If I run `./examples/ex1.jl`, it will run. However, once I make any change to the resumable function in `./src/resumable.jl` and then try to rerun `ex1.jl`, I will get the error:

```julia
┌ Error: Failed to revise c:\Users\HD\.julia\dev\ReviseResumable\src\resumable.jl
│   exception =
│    function type in method definition is not a type
│    top-level scope at c:\Users\HD\.julia\dev\ReviseResumable\src\resumable.jl:98        
│    Revise evaluation error at c:\Users\HD\.julia\dev\ReviseResumable\src\resumable.jl:98
│ 
└ @ Revise C:\Users\HD\.julia\packages\Revise\nWJXk\src\packagedef.jl:691
┌ Warning: The running code does not match the saved version for the following files:
│
│   c:\Users\HD\.julia\dev\ReviseResumable\src\resumable.jl
│
│ If the error was due to evaluation order, it can sometimes be resolved by calling `Revise.retry()`.
│ Use Revise.errors() to report errors again. Only the first error in each file is shown.
│ Your prompt color may be yellow until the errors are resolved.
└ @ Revise C:\Users\HD\.julia\packages\Revise\nWJXk\src\packagedef.jl:789
```
This error can be obtained by adding a new print statement inside the resumable function (or adding/deleting a comment or part of the code inside the function).
There seems to be an issue with Revise and ResumableFunctions.jl. Any insight would be appreciated.

**Comment by timholy** [comment]
For me:
```julia
julia> using ReviseResumable
[ Info: Precompiling ReviseResumable [80d58ff9-3b30-45f0-9ea0-2f24891a39e4]

julia> include("example/ex1.jl")
Will now wait for 1 period...
Waiting complete!

julia> 1+1
2

julia> include("example/ex1.jl")
Will now wait for 1.1 period...
Waiting complete!
```

Versions:
```julia
(@v1.5) pkg> st Revise LoweredCodeUtils JuliaInterpreter
Status `~/.julia/environments/v1.5/Project.toml`
  [aa1ae85d] JuliaInterpreter v0.8.4
  [6f1432cf] LoweredCodeUtils v1.2.6
  [295af30f] Revise v3.1.9

julia> versioninfo()
Julia Version 1.5.4-pre.0
Commit 599ecd8210* (2020-11-10 10:50 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_CPU_THREADS = 4
```

**Comment by hdavid16** [comment]
Hi @timholy. Thanks for taking a look.

You need to actually change the code in `./src/resumable.jl` in between your include statements to reproduce the error. For instance, deleting row 20 of that file (the one with `println("Will now wait for 1 period...")`) and then re-running the `include` statement gives the error posted previously.

FYI,
```julia
(@v1.5) pkg> st Revise LoweredCodeUtils JuliaInterpreter
Status `C:\Users\HD\.julia\environments\v1.5\Project.toml`
  [295af30f] Revise v3.1.6

(@v1.5) pkg> versioninfo()
ERROR: Could not determine command

**Comment by timholy** [comment]
I did; see that it went from
```
Will now wait for 1 period...
```
to
```
Will now wait for 1.1 period...
```

**Comment by hdavid16** [comment]
Yes, you are right. I am able to reproduce what you showed without the error popping up. However, when I delete one of the print statements, I do get the error. Can you try if it does the same on your end?

**Comment by timholy** [comment]
```julia
julia> include("example/ex1.jl")
Will now wait for 1 period...
Waiting complete!

julia> 1+1
2

julia> include("example/ex1.jl")
Waiting complete!
```

**Comment by hdavid16** [comment]
Ok. I'm at a loss then. I am doing this in vscode while deving the package. I don't know if this makes any difference. Any idea?

**Comment by timholy** [comment]
Have you tried `add Revise@3.1.9`? I don't know if that's important or not, but it is one difference between us. I am also not sure which JuliaInterpreter & LoweredCodeUtils you have (it didn't say above), and those are important components of the pipeline.

**Comment by timholy** [comment]
I'm doing this in the REPL. Don't know if that's important or not.

**Comment by hdavid16** [comment]
I have upgraded Revise to match your version and have also added the same versions of JuliaInterpreter and LoweredCodeUtils (didn't have those before). I ran it in the REPL. Deleted the first print statement, no error. Deleted the second print statement, the error appeared again....

**Comment by timholy** [comment]
Any chance you can post a video somewhere of the exact steps you're doing? There may be some subtle difference that is not coming through the medium of text responses.

There's of course also the chance that it's a bug on Julia 1.5.1 but not 1.5.3. But I think that's less likely.

**Comment by hdavid16** [comment]
Certainly: https://youtu.be/dbnXDFC_lZc

I will upgrade to 1.5.3 to see if it makes any difference.

**Comment by timholy** [comment]
The video fixed the problem: you were doing a *second* revision, and I was not.

It's unlikely I'll get to this today, but I wanted you to know I can now replicate this.

**Comment by timholy** [comment]
With LoweredCodeUtils 1.2.8:
```julia
julia> include("./example/ex1.jl")
[ Info: Precompiling ReviseResumable [80d58ff9-3b30-45f0-9ea0-2f24891a39e4]
Will now wait for 1 period...
Waiting complete!

julia> include("./example/ex1.jl")
Will now wait for 1.1 period...
Waiting complete!

julia> include("./example/ex1.jl")
Will now wait for 1.1 period...
Waiting really complete!

julia> include("./example/ex1.jl")
Will now wait for 1.1 period...

julia> include("./example/ex1.jl")
```

Fixed by https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/60

**Comment by hdavid16** [comment]
Awesome! I will go ahead and upgrade. If I run into any issues with my development using ResumableFunctions, I will let you know. This is going to speed things up so much. Thanks @timholy

**Comment by timholy** [comment]
LCU1.2.8 might introduce a bug while fixing others, but 1.2.9 *should* fix everything. (It's due out in ~15 minutes.)

**Comment by hdavid16** [comment]
Hi @timholy, I upgraded to 1.2.9, but continue having the error...

I add a comment above the first print statement and rerun ex1.jl and the error returns...

I also tried the same runs you showed above and made it past the first two, but then failed on the third one...

```julia
(@v1.5) pkg> st Revise JuliaInterpreter LoweredCodeUtils
Status `C:\Users\HD\.julia\environments\v1.5\Project.toml`
  [aa1ae85d] JuliaInterpreter v0.8.8
  [6f1432cf] LoweredCodeUtils v1.2.9
  [295af30f] Revise v3.1.11
```

**Comment by hdavid16** [comment]
@timholy, just following up on the continued issue to check that it hasn't slipped though the cracks. Thanks!

**Comment by hdavid16** [comment]
As an update, the newer version of LoweredCodeUtils has improved the use of `Revise` with `ResumableFunctions`. Sometimes, `Revise` works after making changes to a `ResumableFunction`. However, 5 out of 10 times, `Revise` will still error, requiring a restart of the REPL.

**Comment by haberdashPI** [comment]
I also encounter this problem when using `ResumableFunctions`. Happy to try and narrow down to a smaller MWE if it helps.

**Comment by baggepinnen** [comment]
+1 for encountering this issue, also in a file using ResumableFunctions
```
  [295af30f] Revise v3.4.0
  [6f1432cf] LoweredCodeUtils v2.2.2
  [aa1ae85d] JuliaInterpreter v0.9.16
```

**Comment by hdavid16** [comment]
I haven't seen this error appear in my most recent project with Revise and ResumableFunctions. @haberdashPI @baggepinnen are you still seeing this error?

**Comment by baggepinnen** [comment]
I have not seen it for a while either, but I rarely use revise so I'm not sure if it's still a problem
