### ISSUE TITLE
Special-case exit() so that exiting is always quick?

### ISSUE THREAD

**Issue by ianshmean** [timholy/Revise.jl#562]
Revise (v3.1.6) does work when calling `exit()`, which I'm assuming in most cases the user just wants a prompt exit.

Could `exit()` be specially treated to just exit promptly and not do any revision detection?

Just an idea, not urgent/critical

**Comment by timholy** [comment]
Easy to do. I think Ctrl-D already did this, but adding exit shouldn't hurt anything.

**Comment by ianshmean** [comment]
Awesome. Thanks!

**Comment by schillic** [comment]
In recent versions (I tried Revise v3.5.2 with Julia v1.8.5) the quick `exit()` workaround does not work anymore. I thought I'd report that here.

**Comment by timholy** [comment]
It should: https://github.com/timholy/Revise.jl/issues/796#issuecomment-2376366616
