### ISSUE TITLE
Avoid revising when calling `exit`

### ISSUE THREAD

**Issue by mohamed82008** [timholy/Revise.jl#565]
Sometimes I switch branches and I know Revise will fail to update the module so I call `exit()` but `Revise` still lags the REPL for a few seconds before it fails and then `exit()` is run. It would be nice to special case `exit()`.

**Comment by fredrikekre** [comment]
https://github.com/timholy/Revise.jl/pull/563

**Comment by mohamed82008** [comment]
haha cool! thanks!
