### ISSUE TITLE
typemax error

### ISSUE THREAD

**Issue by cstjean** [timholy/Revise.jl#568]
On Revise 1.3.6 + Julia 1.5, I have some macro invocation like

```julia
@def_model Foo begin
    f(x) = 5
end
```

which macroexpands into a lot of function definitions, but nothing particularly exotic. In particular, it defines a function like `g(x) = 5`. When I change `5` to `6`, I would expect Revise to pick up the change, but it doesn't: `g(2)` still returns 5. Calling `Revise.revise(that_module)` works. No error is shown. But if I turn on the logger via `rlogger = Revise.debug_logger()`, then revising (i.e. changing the 5 to 7) now fails with an error

```julia
┌ Error: Failed to revise /Users/cedric/blah.jl
│   exception =
│    AssertionError: ld[idx] < typemax(eltype(ld))
│    Stacktrace:
│     [1] (::Revise.var"#79#81"{OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}},OrderedCollections.OrderedDict{Revise.RelocatableExpr,Union{Nothing, Array{Any,1}}}})() at /Users/cedric/.julia/packages/Revise/nWJXk/src/packagedef.jl:255
└ @ Revise ~/.julia/packages/Revise/nWJXk/src/packagedef.jl:693
┌ Warning: The running code does not match the saved version for the following files:
```

Does that ring a bell? If not, I'll produce an MWE, but there's a lot of trimming involved.

**Comment by timholy** [comment]
It's from https://github.com/timholy/Revise.jl/blob/023b6c254272601a51d11b2517eb9238eb395ee1/src/packagedef.jl#L250-L258. That code handles multiple definitions, e.g., if you copy a method from one file to another but forget to delete the first one before making a revision. It seems to suggest line number problems, but beyond that I cannot say.

**Comment by cstjean** [comment]
MWE:

```julia
module MyModule

using MacroTools: @q

function my_fun end

macro some_macro(value)
    return esc(@q $MyModule.my_fun() = $value)   # with normal `quote` it works fine
end

@some_macro 20   # changing this value isn't revised
end

> using Revise, MyModule
> MyModule.my_fun()
```

> It seems to suggest line number problems, but beyond that I cannot say.

Good guess. It's caused by `@q`, which strips away line numbers. I admit that I was never quite sure where it was appropriate to use. If you think it's just not right to strip away line numbers at the top-level, I'll repent and replace it with regular `quote`.

**Comment by timholy** [comment]
Wild. Check this out:

```julia
julia> module MyModule

       using MacroTools: @q

       function my_fun end

       macro some_macro(value)
           return esc(@q $MyModule.my_fun() = $value)   # with normal `quote` it works fine
       end

       end
Main.MyModule

julia> Base.Meta.lower(MyModule, :(@some_macro 20))
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.getproperty(Main.MyModule, :my_fun)
│   %2 = Core.Typeof(%1)
│   %3 = Core.svec(%2)
│   %4 = Core.svec()
│   %5 = Core.svec(%3, %4, $(QuoteNode(:(#= none:0 =#))))
│        $(Expr(:method, nothing, :(%5), CodeInfo(
    @ none within `none'
1 ─     return 20
)))
└──      return nothing
))))
```

On line %6, that 3-argument `:method` expression has `nothing` for the name (see https://docs.julialang.org/en/v1.6-dev/devdocs/ast/#Expr-types, note this is outdated and now `false` has been replaced with `nothing`). I don't know if this is a Julia bug or a MacroTools bug, care to check? But it's probably not a Revise bug.

**Comment by cstjean** [comment]
Interesting, on Julia 1.5.1 + MacroTools 0.5.6 I don't see the `nothing`. Maybe the `typemax` error comes from elsewhere?

```julia
julia> using MacroTools: @q

julia> module MyModule

       using MacroTools: @q

       function my_fun end

       macro some_macro(value)
           return esc(@q $MyModule.my_fun() = $value)   # with normal `quote` it works fine
       end

       end
Main.MyModule

julia> Base.Meta.lower(MyModule, :(@some_macro 20))
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.getproperty(Main.MyModule, :my_fun)
│   %2 = Core.Typeof(%1)
│   %3 = Core.svec(%2)
│   %4 = Core.svec()
│   %5 = Core.svec(%3, %4, $(QuoteNode(:(#= none:0 =#))))
│        $(Expr(:method, :(Base.getproperty(Main.MyModule, :my_fun)), :(%5), CodeInfo(quote
    return 20
end)))
└──      return
))))
```

**Comment by timholy** [comment]
Sorry, I didn't think the typemax was your main problem. Does the typemax error happen on Julia 1.5? Your MWE doesn't generate the typemax error for me, but I was probably using 1.6.

**Comment by cstjean** [comment]
Right, the `typemax` isn't the problem, it's the non-revision. I fixed it anyway by getting rid of the `@q`, would you prefer if we just closed this?

> But even on 1.5 that's a pretty weird :method Expr.

With `:(` it yields:

```julia
│   %5 = Core.svec(%3, %4, $(QuoteNode(:(#= REPL[2]:8 =#))))
│        $(Expr(:method, :(Base.getproperty(Main.MyModule, :my_fun)), :(%5), CodeInfo(quote
    return 20
end)))
```

vs. 

```julia
│   %5 = Core.svec(%3, %4, $(QuoteNode(:(#= none:0 =#))))
│        $(Expr(:method, :(Base.getproperty(Main.MyModule, :my_fun)), :(%5), CodeInfo(quote
    return 20
end)))
```

with `@q`. The missing line information is the only difference AFAICT, which of course is the whole point behind `@q`.

For top-level expansions, `@q` doesn't make that much sense anyway because it's better to have the macro's line numbers rather than nothing.

**Comment by timholy** [comment]
I suspect you've still found a Julia bug, though. In https://docs.julialang.org/en/v1/devdocs/ast/#Expr-types, I think the names used for the 1-argument and 3-argument methods should be the same. In your case, they are not. Are you comfortable reporting this as a Julia issue, or should I?

**Comment by cstjean** [comment]
> Are you comfortable reporting this as a Julia issue, or should I?

Please do it, I don't completely understand the issue you're seeing. I agree that the `@q` expansion is wrong on 1.6 according to the devdocs...

**Comment by timholy** [comment]
To save me some time, what's the "normal `quote`" implemention of `some_macro` that works?

**Comment by cstjean** [comment]
```julia
julia> module MyModule

          function my_fun end

          macro some_macro(value)
              return esc(:($MyModule.my_fun() = $value))   # with normal `quote` it works fine
          end

          end
WARNING: replacing module MyModule.
Main.MyModule

julia> Base.Meta.lower(MyModule, :(@some_macro 20))
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.getproperty(Main.MyModule, :my_fun)
│   %2 = Core.Typeof(%1)
│   %3 = Core.svec(%2)
│   %4 = Core.svec()
│   %5 = Core.svec(%3, %4, $(QuoteNode(:(#= REPL[2]:8 =#))))
│        $(Expr(:method, :(Base.getproperty(Main.MyModule, :my_fun)), :(%5), CodeInfo(quote
    return 20
end)))
└──      return
))))
```

I'm curious what it yields in 1.6

**Comment by timholy** [comment]
Still has `nothing` there. Thanks!

**Comment by cstjean** [comment]
Thank you!
