### ISSUE TITLE
Base.TOMLCache method error

### ISSUE THREAD

**Issue by xijiang** [timholy/Revise.jl#569]
Julia Version 1.6.0-DEV.1473
Commit af3cd59e13 (2020-11-11 16:26 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, znver2)

using Revise
ERROR: InitError: MethodError: no method matching Base.TOMLCache()
Closest candidates are:
  Base.TOMLCache(::Base.TOML.Parser, ::Dict{String, Base.CachedTOMLDict}) at loading.jl:215
  Base.TOMLCache(::Any, ::Any) at loading.jl:215
Stacktrace:
 [1] manifest_file(project_file::String)
   @ Revise ~/.julia/packages/Revise/qxX5H/src/pkgs.jl:451
 [2] manifest_file
   @ ~/.julia/packages/Revise/qxX5H/src/pkgs.jl:461 [inlined]
 [3] __init__()
   @ Revise ~/.julia/packages/Revise/qxX5H/src/Revise.jl:1334
 [4] _include_from_serialized(path::String, depmods::Vector{Any})
   @ Base ./loading.jl:662
 [5] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
   @ Base ./loading.jl:748
 [6] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:986
 [7] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:902
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:889
during initialization of module Revise

Revise@v3.x.y gave same error messages as Revise@v2.7.6.
Any suggestion?
Regards.

**Comment by timholy** [comment]
What Revise version are you on? This should be fixed on 3.1.5 and up.

**Comment by xijiang** [comment]
Oh, by default my julia is install v3.1.3. It is strange that mine is not installing the latest `Revise`.
`add Revise@v3.1.7` solved the problem.

great package btw.
