### ISSUE TITLE
Revise doesn't update methods if the signature changes indirectly

### ISSUE THREAD

**Issue by FedericoStra** [timholy/Revise.jl#582]
Let's say that I have a file `test.jl` with contents

```julia
module test
T = Int
foo(::T) = 42
end
```

At the REPL I execute

```julia
julia> push!(LOAD_PATH, "."); using Revise

julia> using test
[ Info: Precompiling test [top-level]

julia> test.T
Int64

julia> methods(test.foo)
# 1 method for generic function "foo":
[1] foo(::Int64) in test at /home/***/test.jl:3
```

If I now change line 2 to `T = Char`, then `test.T` gets updated

```julia
julia> test.T
Char
```

but `test.foo` does not

```julia
julia> methods(test.foo)
# 1 method for generic function "foo":
[1] foo(::Int64) in test at /home/***/test.jl:3
```

I suspect that Revise is trying to do something smarter than it probably should and skips the redefinition of `foo` because "it looks the same".

**Comment by timholy** [comment]
This is basically #249. To me at least, it's really not clear whether it's solvable in general. Consider a module that initializes a C library that segfaults if you initialize it twice; this is actually quite common, much more common than non-`const` interlocking dependencies across a package. You could write this as

```julia
let T = Int
    global foo
    foo(::T) = 42
end
```
and then it would revise. (Not just define the new method, it will also delete the original.)

If you're expecting it to reload the whole module, use `revise(test)`. That won't delete the original `foo` method but it will re-evaluate the module. https://github.com/cstjean/ClobberingReload.jl behaved more like you may expect, *replacing* the module, but it was found to be quite difficult to accurately update all dependent modules.

**Comment by FedericoStra** [comment]
Sorry that I didn't find #249, I searched a bit through the issues but couldn't find anything similar.

The problem of initializing C libraries is quite serious indeed, but I wonder if the default behavior can be reversed: default to uploading dependent definitions, which covers the majority of cases, and have a macro such as `@revise_once`/`@dont_revise` to protect code that should not be re-executed upon revising.

With the current behavior there is a huge risk that the code loaded in the REPL is not the same code that we look at in the editor. I don't feel any certainty that I'm actually working with the revised code; the only way I feel sure about it is by restarting.

Redefining `const`s or `struct`s is out of the question at the moment, because it throws an error, but in my example we don't get any signal that something wrong is going on. I feel quite worried about it, because my example was extremely simple and clear, but the same problem could arise in a more complex module with more intricate interdependencies.

**Comment by timholy** [comment]
That said, no one besides myself (as a purely theoretical issue) and now you has ever reported it as a problem. Given that there have been more than 250 issues reported, it leaves me thinking that almost no one actually writes Julia code that way. I've never seen an example in the wild. I was worried about it until I realized that trying to solve that problem will create more problems than it will solve.

Almost all code that defines methods based on non-constant value tends to be in a scope block. I showed `let` above, but more commonly consider a `for` loop`:

```julia
for T in (Float32, Float64)
    @eval mysizeof(::Type{$T}) = sizeof($T)
end
```

This also revises just fine; you can add new types to the list or even remove some of them and Revise will delete & add methods appropriately to reflect the current state of the list.

Relying on non-contant module globals to make define-time decisions just seems a bit dicey to me. Maybe others feel similarly which is why it doesn't tend to come up.

There have been reports about failing to properly handle *data* (e.g., #475), which is part of why `includet` works the way it does now (evaluating data, once, but not trying to revise it).

**Comment by FedericoStra** [comment]
I'm not arguing that it is a good coding practice in production code (it most definitely isn't), but I feel the issue comes up quite naturally while prototyping. Imagine that you have the following module
```julia
# define some types we would like to experiment with
struct Alternative1 ... end
struct Alternative2 ... end
...

# define a type alias to pick a particular choice
TypeAlias = Alternative1 # Alternative2, Alternative3, Tuple{Int,Char}, ...

# define the code in terms of the type alias
foo(::TypeAlias, ::Int) = ...
bar(::TypeAlias, ::TypeAlias) = ...
quz(::String, ::TypeAlias, ::Int) = ...
```

`TypeAlias` allows to quickly switch between several choices without modifying all the signatures.

**Comment by timholy** [comment]
Oh, that is interesting. I see why you might want that. Truth be told, I built almost [all the infrastructure](https://juliadebug.github.io/LoweredCodeUtils.jl/stable/edges/) to do this properly, but then came to the conclusion that it would likely introduce serious problems of its own.

I'll think about it. Not today, but I'll think about it.

There are also various proposals to replace modules wholesale (e.g., https://github.com/JuliaLang/julia/pull/33872 and https://github.com/timholy/Revise.jl/issues/18#issuecomment-571854977), though the experience of %autoreload and ClobberingReload suggests that's likely to be trickier than it seems and may introduce its own form of fragility (I've heard lots of complaining about `%autoreload` from my Python colleagues).
