### ISSUE TITLE
Revising the addition of a docstring

### ISSUE THREAD

**Issue by mbauman** [timholy/Revise.jl#583]
Ok, this is a little silly, but I was just demoing Revise to someone and blindly tried adding a docstring, expecting it to become available (akin to other changes).

Not a crucial thing, but could be nice to support.

**Comment by timholy** [comment]
Should work?

https://github.com/timholy/Revise.jl/blob/1dd0a70997882a10d15ac92b08e7f14f9ea441cd/test/runtests.jl#L1055-L1269

**Comment by mbauman** [comment]
Interesting.  Here's what I was trying (Julia 1.5.0, Revise 3.1.9)

```julia
module TestPackage

greet(name="World") = "Hello $(name), nice to meet you!"

end # module
```

```
julia> using Revise

julia> using TestPackage
[ Info: Precompiling TestPackage [606d46c6-36d6-41d4-9f3b-24d4fb92e632]

julia> TestPackage.greet("me")
"Hello me, nice to meet you!"

help?> TestPackage.greet
  No documentation found.
```

Edit the module to contain:

```Julia
module TestPackage

"""
    greet

foo
"""
greet(name="World") = "Hello to $(name), so glad to see you!"

end # module
```

then:

```
julia> TestPackage.greet("Grandma Yvette")
"Hello to Grandma Yvette, so glad to see you!"

help?> TestPackage.greet
  No documentation found.
```

**Comment by mbauman** [comment]
Ah, it works if it already has a docstring — it's the _adding_ of a new docstring that doesn't.

**Comment by timholy** [comment]
Color me amazed. Despite trying to set up good APIs and sensible logic, I get caught over and over again by subtle differences blockin something that should work. It seems that almost every single thing anyone ever wants to do needs a test.

**Comment by mbauman** [comment]
I just need to do more live and interactive demos.  They have a way of exploring new paths in fun and exciting ways!

**Comment by timholy** [comment]
You are so right. I notice everything bad about Julia whenever I'm teaching someone new or demonstrating how awesome it is. :laughing:

**Comment by timholy** [comment]
It also requires that the module have no docstrings whatsoever. It's a Julia bug. Fix coming momentarily.

**Comment by timholy** [comment]
xref https://github.com/JuliaLang/julia/issues/38819 and fix in 38821.
