### ISSUE TITLE
Revise fails on nightly?

### ISSUE THREAD

**Issue by grahamas** [timholy/Revise.jl#593]
As of updating to last night's nightly from 2020 Dec 10's build (I skipped all the builds in between), Revise fails (on multiple, seemingly unrelated files; all files that I've tried). I have been updating packages in the meantime, but it's plausible I haven't updated in two weeks, so it could've been a Revise update. I get one of two errors:

```
┌ Error: Failed to revise /home/graham/git/NeuralModels/src/nonlinearity.jl
│   exception =
│    TypeError: in <:, expected Type, got Vararg
│    Stacktrace:
│     [1] top-level scope
│       @ ~/git/NeuralModels/src/nonlinearity.jl:7
│    Revise evaluation error at /home/graham/git/NeuralModels/src/nonlinearity.jl:7
│    
└ @ Revise ~/.julia/packages/Revise/34vmN/src/packagedef.jl:699
```
or
```
┌ Error: Failed to revise /home/graham/.julia/dev/AxisIndices/src/abstractarray.jl
│   exception =
│    UndefVarError: _apply_latest not defined
│    Stacktrace:
│     [1] getproperty(x::Module, f::Symbol)
│       @ Base Base.jl:26
│     [2] top-level scope
│       @ ~/.julia/dev/AxisIndices/src/abstractarray.jl:2
│    Revise evaluation error at /home/graham/.julia/dev/AxisIndices/src/abstractarray.jl:2
│    
└ @ Revise ~/.julia/packages/Revise/34vmN/src/packagedef.jl:699
```
It's maybe worth noting that both of these errors were in response to my putting an `@show x` line inside a function, or removing said line (the code loads and runs fine in either case with a REPL restart)

Since all this happens in the background, I'm not really sure how to debug this, but I'll try to create a MWE with a dummy package or something and then see if I can't narrow down what update triggered this (though I won't be able to test julia builds between Dec 10 and Jan 8 since I didn't download them -- but I can at least say whether or not the current Revise version works on the Dec 10 build)

**Comment by timholy** [comment]
It's surely the vararg transition: https://github.com/JuliaLang/julia/pull/38136. You can see from the growing number of references at the end of that PR that there are many packages affected.

I don't have time to fix this right now, but everything should work on Julia 1.6, if you can use that.

**Comment by timholy** [comment]
Revise does not catch this in any of its tests: #595 was the only teeny change needed.

I'm going to need a MWE (or any reproducer) to make progress on this.

**Comment by timholy** [comment]
This has probably been fixed; if not, please file an issue with a reproducer.
