### ISSUE TITLE
Not catching f(x::typeof(a)) when `a` changes

### ISSUE THREAD

**Issue by mauro3** [timholy/Revise.jl#594]
Consider
```julia
a = 1 
f(x::typeof(a)) = x
```
when updating
```
a = 1.0
```
then `f` does not get redefined.  Not sure this is even possible, so feel free to close.

The reason I thought about this, is in a situation where I use NamedTuples as poor-man's structs:
```
v1 = (a=1, b=2)
v2 = (d=4, b=3)
f(x::typeof(v1)) = ...
f(x::typeof(v2)) = ...
```

**Comment by timholy** [comment]
#249

**Comment by timholy** [comment]
Since this duplicates #582 (another report of #249) I'll close this.
