### ISSUE TITLE
Any way to manually trigger revision for already tracked file? 

### ISSUE THREAD

**Issue by marius311** [timholy/Revise.jl#598]
I'm on a cluster with a slow network filesystem, such that with `JULIA_REVISE_POLL` (which has to be used in this case), it can be ~30 seconds for Revise to pick up a change between when I save the file and when Revise updates my session. Is there any way I could manually mark a file to be revised? Basically if I know I just edited/saved `Foo.jl`, and revise _is_ already tracking the package `Foo`, can I run something to revise `Foo.jl` now, rather than waiting around 30 seconds?

**Comment by timholy** [comment]
`Revise.revise_file_now`

**Comment by marius311** [comment]
Works, thanks! If anyone else is looking, its the following slight mouthful: 

```julia
Revise.revise_file_now(Revise.pkgdatas[Base.PkgId(Foo)], "src/Foo.jl")
```

**Comment by filchristou** [comment]
I guess you could do `Revise.revise_file_now` for all `Revise.watched_files`, but that looks very internal. Is there something else?  If not I could make a PR implementing a `Revise.revise_watched_files_now` that does what I mentioned. Let me know if you think that's a good idea.
