### ISSUE TITLE
Example not working with vim

### ISSUE THREAD

**Issue by thofma** [timholy/Revise.jl#6]
Somehow I cannot get the example to work. This is on a fresh julia 0.6 installation:
```julia
julia> using Revise

julia> using Example

julia> Example.f()
ERROR: UndefVarError: f not defined
# now define f in Example.jl
julia> WARNING: /home/bla/.julia/v0.6/Example/src/Example.jl changed in ways that Revise cannot track. You will likely have to restart your Julia session.
julia> 

julia> Example.f()
ERROR: UndefVarError: f not defined

julia> versioninfo()
Pkg.Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

julia> Pkg.status()
2 required packages:
 - Example                       0.4.1              526e34fd (dirty)
 - Revise                        0.0.1
```
I have the feeling I am missing something.

**Comment by timholy** [comment]
Hmm, strange. Can you show me `git diff` from the `Example` directory?

**Comment by thofma** [comment]
```diff
~/.julia/v0.6/Example ((v0.4.1) *)$ git diff
diff --git a/src/Example.jl b/src/Example.jl
index 9e11f0e..69d2a1c 100644
--- a/src/Example.jl
+++ b/src/Example.jl
@@ -4,4 +4,6 @@ export hello, domath
 hello(who::String) = "Hello, $who"
 domath(x::Number) = (x + 5)
 
+f() = 2
+
 end
```

**Comment by timholy** [comment]
You're doing everything right. That's truly bizarre. Can you try adding `dump(event)` right before [this line](https://github.com/timholy/Revise.jl/blob/30691f5c61062c172dfc13d40ccd01c34ab23235/src/Revise.jl#L416)?

**Comment by thofma** [comment]
```julia
julia> Example.f()
ERROR: UndefVarError: f not defined

julia> Base.Filesystem.FileEvent
  renamed: Bool true
  changed: Bool false
  timedout: Bool false
WARNING: /home/bla/.julia/v0.6/Example/src/Example.jl changed in ways that Revise cannot track. You will likely have to restart your Julia session.
```

**Comment by timholy** [comment]
Somehow it's claiming the file has been renamed rather than modified! Can you try this:
```sh
tim@diva:/tmp$ echo "silly" > silly.txt
```
Now open another terminal and start julia, do:
```julia
julia> dump(watch_file("silly.txt"))
```
It should "hang". Then go back to the first terminal and do this:
```sh
tim@diva:/tmp$ touch silly.txt
```
Now check your julia session, you should see
```julia
julia> dump(watch_file("silly.txt"))
Base.Filesystem.FileEvent
  renamed: Bool false
  changed: Bool true
  timedout: Bool false

julia> 
```

If you do see that, then try the same thing again, except this time use the same editor you were using to edit Example.jl. This might be an issue with specific editors, or perhaps even the filesystem you're using?

**Comment by thofma** [comment]
Every editor worked fine except for vim. With vim I experience super strange behaviour and I think am hitting something similar as in https://github.com/joyent/libuv/issues/787

**Comment by thofma** [comment]
It works with
```
set nobackup
set nowritebackup
```
Note that this disables backups, see also https://stackoverflow.com/questions/607435/why-does-vim-save-files-with-a-extension/607475#607475, but who needs backups anyways

**Comment by timholy** [comment]
Interesting. I'm on the road, but perhaps could try changing that conditional to test changed OR renamed? I guessed renamed meant something similar to deleted, but maybe it's more like what vim is doing?

**Comment by thofma** [comment]
I'm neither a vim expert nor a libuv expert, but I think when working with backups/swap files, vim is renaming the original file when saving, instead of making a change to it.

The test for changed OR renamed helps with vim. If you then do a proper renaming/deletion you will get
```julia
julia> WARNING: /home/bla/.julia/v0.6/Example/src/Example.jl is not an existing file, Revise is not watching
```
This case is handled at https://github.com/timholy/Revise.jl/blob/master/src/Revise.jl#L405, so checking for changed OR renamed should be safe?

**Comment by timholy** [comment]
Thanks for the diagnostics and suggestions. See #7. Because I'm traveling I haven't even tested, but you can try that branch if you like.
