### ISSUE TITLE
Revise when editing/running on two different systems

### ISSUE THREAD

**Issue by raminammour** [timholy/Revise.jl#60]
Hello,

Revise is not working for me; I managed to track it down. It is because I edit my files on one system (call it system A) and Julia is running on another (call it system B; some hpc systems do not have a decent editor :) ).

I confirmed that if you `watch_file(file)` on system A, and `touch file` on system B, the change is not detected on System A (`watch_file` is still blocking).

I have also found out that `poll_file` can get around that problem by polling every `t` seconds. However, it turns out that `poll_file` only works for files, when `watch_file` works for directories too. Looked at the code and it watches the directory. I can implement recursive polling on a directory, but not sure if it leads to a bottleneck.

Is there a clean way to get around this or fix it? I appreciate any help :)

Not sure if this qualifies as an issue, but thought it is good to leave it here if someone encounters the same issue (it will probably be lost on discourse).

Thanks for a great package anyway!

**Comment by timholy** [comment]
When you edit files on A, how do you move the changes over to B? In other words, even if you restarted your julia session, would those changes take effect?

The reason we watch directories rather than files is given in the issues history here, particularly #15 and #22.

**Comment by raminammour** [comment]
If I restart the julia session it sees the change. I can see the time stamp change on System B when I edit from system A but for some reason `watch_file` does not react. Now if i `touch file` on system B now, `watch_file` returns.

**Comment by raminammour** [comment]
I assumed watching all the files recursively would spell trouble. Either way you will have to `poll_file` and not `watch_file` to see the change ( I don't understand why though).

**Comment by timholy** [comment]
To make sure I understand, do the files reside on a shared network drive? That would explain how they get synced. 

Can you tell me more about the system? Are these unix systems using NFS? Or something else? This page seems relevant: https://stackoverflow.com/questions/4231243/inotify-with-nfs

**Comment by raminammour** [comment]
It is on a shared network drive. 

I ran `nfsstat -m |grep my_username` on both systems and showed the same thing.

**Comment by timholy** [comment]
Not good news, but it sounds like it's been considered quite carefully.

If you want to keep pursuing this, perhaps search for `libuv poll nfs` and see whether there are good solutions. (I have a deadline I'm late for, sorry to put this on you.) `libuv` is what Julia uses under the hood for most  file operations.

**Comment by raminammour** [comment]
No worries, our system is quite `special` anyway. 

Thanks for the help, will let you know if this leads anywhere.

**Comment by raminammour** [comment]
For now, I pinned  `Revise` to `v0.0.3`, changed `watch_file(file)` to `poll_file(file)` and looks like it is working. Better than nothing :)

**Comment by timholy** [comment]
Good to know. Perhaps this could be set up as a configurable option. There are new goodies coming, you may not want to miss out by staying on an old version forever.

**Comment by timholy** [comment]
If you have a build of Julia 0.7, any chance you can test #81? You'd need to launch julia with
```sh
JULIA_REVISE_POLL=1 julia
```
where `julia` means Julia 0.7.

**Comment by raminammour** [comment]
I tried to checkout 0.7 and compile it, but the master branch is earlier than the version required by Revise.

```
julia is fixed at 0.7.0-DEV.2774 conflicting with requirement for Revise: [0.7.0-DEV.3131,â)
```
and Revise would not precompile...

**Comment by raminammour** [comment]
Sorry, I just learned about `git fetch` :)

```
julia> Pkg.status("Revise")
WARNING: Base.Pkg is deprecated, run `using Pkg` instead.
 in module Main
 - Revise    
```

```
julia> versioninfo()
Julia Version 0.7.0-DEV.3703
Commit 358ccc2* (2018-02-02 20:43 UTC)
Platform Info:
  OS: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-4640 0 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
Environment:
  JULIA_REVISE_POLL = 1
```

But the #81 does not work for me yet. Still only detects changes on the same system.

I will not have access to the codes on the weekend, so I may not be of much help, but thanks for looking into this!

**Comment by timholy** [comment]
Did you make sure to set `JULIA_REVISE_POLL=1`? It *definitely* won't work unless you do. Polling is very undesirable unless you have no alternative, so it requires the user to say "yes I want this."

**Comment by raminammour** [comment]
I did, it shows up in the version info environment. I realized polling was undesirable, so now I just do `;touch foo.jl` to get revise to update the definition.

**Comment by timholy** [comment]
Hmm, interesting. Not quite sure what's up with that. Perhaps I should just close that PR?

**Comment by raminammour** [comment]
I will see if I can figure out what is wrong in the next few days, and will
get back to you.

**Comment by raminammour** [comment]
Looks like it is working, I don't know what I was doing wrong! Maybe not waiting for 5 seconds, maybe it was just too late on a Friday afternoon.

Feel free to close the issue, and again, thanks for supporting this!

**Comment by timholy** [comment]
Awesome, really glad to hear it!

To make sure this doesn't decay, I'd love to have the tests (`test/polling.jl`, see also the corresponding commented-out line in `.travis.yml`) working. Do you by any chance have any insights about why they only work when pasted into the REPL?

**Comment by timholy** [comment]
nvm, I figured out a way to make it work. It seems that `sleep(0.2)` is not the same as `sleep(0.1); sleep(0.1)`. That's a bit of a head-scratcher...

**Comment by raminammour** [comment]
I confirm that the `pollling` test passes, whether included from the REPL or ran as a script (from `.travis.yml`) .

I needed the two sleep commands to get the script to pass too, weird indeed!
