### ISSUE TITLE
Revise "forgets" renamed imports

### ISSUE THREAD

**Issue by fredrikekre** [timholy/Revise.jl#600]
I have a package with something like
```
module ForgetImports

import TOML as toml

function test()
    toml.print(stdout, Dict("hello" => "world"))
end

end
```
and when this module is revised I get
```
julia> ForgetImports.test()
ERROR: UndefVarError: toml not defined
```
The code above does not actually trigger it for some reason though, so I will try to find an MWE later I thought it might be worth reporting anyway since someone might have an idea what is wrong without an MWE.

Edit: Julia 1.6.0-beta1, Revise 3.1.11

**Comment by fredrikekre** [comment]
Okay, it seems I can trigger it when changing the scope of a variable, e.g. changing:
```
function test()
    x = 1
    try
        toml.print(...)
    end
end
```
to
```
function test()
    try
       x = 1
        toml.print(...)
    end
end
```

Just another clue, still no sharable MWE.

**Comment by fredrikekre** [comment]
I also checked the Revise debug logs but nothing strange there; just the expected `DeleteMethod` and then the expected `Eval` entries.

**Comment by fredrikekre** [comment]
Ah, it is probably https://github.com/JuliaLang/julia/issues/39405

Just for the record, why does this show up only after a first revision when using Revise?

**Comment by fredrikekre** [comment]
I can also note that the original code has worked (and still does) without any problems until i involve Revise unlike the MWE from https://github.com/JuliaLang/julia/issues/39405 which reproduces without Revise at all.

**Comment by fredrikekre** [comment]
Assuming this is fixed by https://github.com/JuliaLang/julia/pull/39408.

**Comment by timholy** [comment]
Thanks for figuring it out!
