### ISSUE TITLE
Can't compile on Julia 1.7.0-DEV.653 (2021-03-03)

### ISSUE THREAD

**Issue by xijiang** [timholy/Revise.jl#613]
| | |_| | | | (_| |  |  Version 1.7.0-DEV.653 (2021-03-03)
 _/ |\__'_|_|_|\__'_|  |  Commit 502c03974b (0 days old master)
|__/                   |

(@v1.7) pkg> update
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`

julia> using Revise
[ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
ERROR: LoadError: LoadError: AssertionError: precompile(Tuple{mbody.sig.parameters[1], Symbol, Bool, Bool, Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(methods_by_execution!), Any, MI, DocExprs, Module, Expr})
Stacktrace:
  [1] _precompile_()
    @ Revise ~/.julia/packages/Revise/chUcN/src/precompile.jl:54
  [2] top-level scope
    @ ~/.julia/packages/Revise/chUcN/src/packagedef.jl:1417
  [3] include(mod::Module, _path::String)
    @ Base ./Base.jl:386
  [4] include(x::String)
    @ Revise ~/.julia/packages/Revise/chUcN/src/Revise.jl:1
  [5] top-level scope
    @ ~/.julia/packages/Revise/chUcN/src/Revise.jl:20
  [6] include
    @ ./Base.jl:386 [inlined]
  [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1213
  [8] top-level scope
    @ none:1
  [9] eval
    @ ./boot.jl:369 [inlined]
 [10] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [11] top-level scope
    @ none:1
in expression starting at /home/xijiang/.julia/packages/Revise/chUcN/src/packagedef.jl:1417
in expression starting at /home/xijiang/.julia/packages/Revise/chUcN/src/Revise.jl:1
ERROR: Failed to precompile Revise [295af30f-e4ad-537b-8983-00126c2a3abe] to /home/xijiang/.julia/compiled/v1.7/Revise/jl_0r1bSq.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY)
   @ Base ./loading.jl:1360
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1306
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1021
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:914
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:901

**Comment by timholy** [comment]
There's a new bug in precompilation on anything but Linux.

**Comment by timholy** [comment]
Oh, and this should already be fixed on 3.1.13

**Comment by xijiang** [comment]
mine is `Revise` 3.1.13. not working.

**Comment by timholy** [comment]
Oh, didn't realize initially that you were on Linux. Interesting. You can temporarily remove the `islinux` from #612 while we investigate. Of course, you could also use 1.6-rc1.

**Comment by timholy** [comment]
OK, so it was just a question of when different platforms updated their nightly. I can replicate this too.
