### ISSUE TITLE
Logo graphics and Dark Mode

### ISSUE THREAD

**Issue by cormullion** [timholy/Revise.jl#628]
With the recent arrival of Dark Mode, some of the graphics used don't look at their best. I suspect many people will see the one on the left  if they visit Revise.jl:

<img width="1531" alt="Screenshot 2021-05-22 at 13 49 45" src="https://user-images.githubusercontent.com/52289/119227275-f0d9c900-bb04-11eb-87c4-6e74640f9cc6.png">

A simple fix for this is to use a color that works well on both dark and white backgrounds - something like a teal-y color might be OK:

<img width="1529" alt="Screenshot 2021-05-22 at 13 49 58" src="https://user-images.githubusercontent.com/52289/119227271-ee776f00-bb04-11eb-95a1-f834ae7641b8.png">

Or something a bit more blue/purple?

<img width="1523" alt="Screenshot 2021-05-22 at 14 11 20" src="https://user-images.githubusercontent.com/52289/119227800-9c841880-bb07-11eb-8a17-efad7da83c8f.png">

I have no preference. Perhaps you have a favourite?

**Comment by pfitzseb** [comment]
How would the wordmark look with the Julia colors, i.e. blue or purple as the text color with the Julia green and red for the s/z replacement?

**Comment by cormullion** [comment]
Like this:

<img width="1353" alt="Screenshot 2021-05-22 at 15 47 44" src="https://user-images.githubusercontent.com/52289/119230643-1373de00-bb15-11eb-9fc7-29c0e2c00496.png">

**Comment by pfitzseb** [comment]
Yep! Love both of these :)

**Comment by tk3369** [comment]
Very nice! I like the blue one more than the purple one. Not that it would matter though. They are both awesome. 😀

**Comment by KristofferC** [comment]
Agree, blue one looks great.
