### ISSUE TITLE
Tracking stdlib packages (eg Test)

### ISSUE THREAD

**Issue by vchuravy** [timholy/Revise.jl#63]
I was hacking yesterday on Test and I tried Revise, but it didn't seem to pick up changes.
It might have something to do with the fact that Test etc still go into the sysimage, but are not longer part of Base?

**Comment by timholy** [comment]
Almost certainly true, and something that should be fixed. Unfortunately it seems that none of these files are getting cached in `usr/share/julia/base.cache`, so a real fix would require some more work in Base (maybe writing them to `usr/share/julia/stdlib.cache`). I'll see if I can get to it in time, but the broadcasting API (which you so kindly helped pave the way for) will take first priority.

**Comment by timholy** [comment]
In the short term, `Revise.track(filename)` may work for you. I'm well aware that it's awkward.

**Comment by vchuravy** [comment]
In the long-term std-lib packages won't be part of the sysimage So just `Revise.track(filename)` might be enough for now.
(And the broadcasting work definitely takes priority, I want that to land for 0.7)

**Comment by jlapeyre** [comment]
Did this work in the end ? I am trying the following, but changes appear to be silently ignored:
`Revise.track("/pathto/julia/stdlib/SharedArrays/src/SharedArrays.jl")`

`Revise.track(Base)` is working. 

FWIW, I am using `v"0.7.0-DEV.4564"`.  The symbol `:SharedArrays` does appear in the array `stdlibs` in `usr/share/julia/base.cache`

**Comment by timholy** [comment]
Fixed by #104
