### ISSUE TITLE
Loading Revise from `if` block

### ISSUE THREAD

**Issue by jebej** [timholy/Revise.jl#632]
I want to start Revise conditionally based on an environment variable (checked in `startup.jl`), and found that simply having `using Revise` in an `if` block would not track files properly. I had to use the pre-1.5 method below. Is that expected?

```julia
if parse(Bool, get(ENV, "JULIA_REVISE", "false"))
    @eval using Revise
    @async Revise.wait_steal_repl_backend()
end
```

**Comment by jebej** [comment]
This is on Windows, with julia 1.6.1.

**Comment by timholy** [comment]
Unexpected. What does
```julia
julia> Base.active_repl_backend.ast_transforms
2-element Vector{Any}:
 revise_first (generic function with 1 method)
 softscope (generic function with 1 method)
```
contain?

**Comment by timholy** [comment]
It already means something:
https://timholy.github.io/Revise.jl/stable/config/#Manual-revision:-JULIA_REVISE-1

Set it to "auto" or pick a different ENV variable.
