### ISSUE TITLE
`includet` includes files with recursive includes twice

### ISSUE THREAD

**Issue by adomasbaliuka** [timholy/Revise.jl#639]
# Problem description

Suppose I have two files:

```julia
# tmp/file1.jl
include("file2.jl")

println("Hello from file1.jl !")
```
```julia
# tmp/file2.jl
println("Hello from file2.jl!!")
```
If I open a REPL in the directory and do

```jldoctest
julia> using Revise; includet("tmp/file1.jl")
Hello from file2.jl!!
Hello from file1.jl !
Hello from file2.jl!!

julia> 
```

I get the output from `file2.jl` twice. Is this expected? Should one avoid having recursive includes in files that one includes via `includet`?

# System information
Revise v3.1.17

Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8

**Comment by aloy1496** [comment]
> # Problem description
> 
> 
> 
> Suppose I have two files:
> 
> 
> 
> ```julia
> 
> # tmp/file1.jl
> 
> include("file2.jl")
> 
> 
> 
> println("Hello from file1.jl !")
> 
> ```
> 
> ```julia
> 
> # tmp/file2.jl
> 
> println("Hello from file2.jl!!")
> 
> ```
> 
> If I open a REPL in the directory and do
> 
> 
> 
> ```jldoctest
> 
> julia> using Revise; includet("tmp/file1.jl")
> 
> Hello from file2.jl!!
> 
> Hello from file1.jl !
> 
> Hello from file2.jl!!
> 
> 
> 
> julia> 
> 
> ```
> 
> 
> 
> I get the output from `file2.jl` twice. Is this expected? Should one avoid having recursive includes in files that one includes via `includet`?
> 
> 
> 
> # System information
> 
> Revise v3.1.17
> 
> 
> 
> Julia Version 1.6.2
> 
> Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
> 
> Platform Info:
> 
>   OS: Linux (x86_64-pc-linux-gnu)
> 
>   CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
> 
>   WORD_SIZE: 64
> 
>   LIBM: libopenlibm
> 
>   LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
> 
> Environment:
> 
>   JULIA_EDITOR = code
> 
>   JULIA_NUM_THREADS = 8
