### ISSUE TITLE
Revise doesn't update methods when code is modified outside of edit()

### ISSUE THREAD

**Issue by palumbom** [timholy/Revise.jl#653]
Revise no longer updates methods when I modify my source code outside of the edit() function on the REPL. Following from the cookbook example in the documentation, everything works as expected when I use the edit() function: 

```
julia> using Revise
julia> using MyPkg
[ Info: Precompiling MyPkg [5f54f0b3-6509-4233-9053-0bcdb092dc6f]
julia> MyPkg.greet()
Hello World!
julia> edit(MyPkg)

julia> MyPkg.greet()
Hello Revised World!
```

In my preferred workflow, I already have the source open in another pane (specifically I'm modifying the code on a remote server using Sublime Text with SFTP). In this scenario I get the following:

```
julia> using Revise
julia> using MyPkg
[ Info: Precompiling MyPkg [5f54f0b3-6509-4233-9053-0bcdb092dc6f]
julia> MyPkg.greet()
Hello World!
```

If I then make changes in my editor without invoking edit(), I get the following output:

```
julia> MyPkg.greet()
Hello World!
```

I've tried updating to the latest version of Revise (3.1.20), but this hasn't remedied the issue either. For reference, I am running Julia 1.6.2.

**Comment by timholy** [comment]
You shouldn't need to call `edit`---any mechanism of editing works for me. What's your platform? WSL2 by any chance? See #514

**Comment by palumbom** [comment]
Sorry, I totally forgot I had opened this issue. It turns out this "bug" was due to a change on the server I use, not an issue with Revise. Calling ```edit``` just happened to be a workaround. I am not using WSL2.
