### ISSUE TITLE
Revise won't load on Mac M1 machines with Macos monterey

### ISSUE THREAD

**Issue by lewisl** [timholy/Revise.jl#654]
Some problem with TOML:
```
ERROR: InitError: MethodError: no method matching Base.TOMLCache()
Closest candidates are:
  Base.TOMLCache(::Base.TOML.Parser, ::Dict{String, Base.CachedTOMLDict}) at loading.jl:215
  Base.TOMLCache(::Any, ::Any) at loading.jl:215
```

**Comment by KristofferC** [comment]
What Revise version are you using?

**Comment by lewisl** [comment]
V2.7.6

From: Kristoffer Carlsson ***@***.***>
Reply-To: "timholy/Revise.jl" ***@***.***>
Date: Friday, November 12, 2021 at 10:31 AM
To: "timholy/Revise.jl" ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [timholy/Revise.jl] Revise won't load on Mac M1 machines with Macos monterey (Issue #654)


What Revise version are you using?

**Comment by KristofferC** [comment]
Try use the latest version (v3).

**Comment by lewisl** [comment]
Is it on the released channel?  When I update I still get v2.7.6

From: Kristoffer Carlsson ***@***.***>
Reply-To: "timholy/Revise.jl" ***@***.***>
Date: Friday, November 12, 2021 at 12:43 PM
To: "timholy/Revise.jl" ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [timholy/Revise.jl] Revise won't load on Mac M1 machines with Macos monterey (Issue #654)


Try use the latest version (v3).

**Comment by KristofferC** [comment]
Maybe something is holding it back. Try `pkg> add Revise@0.3`.

**Comment by lewisl** [comment]
Tried.

Bunch of messages
```
julia> using Revise
[ Info: Precompiling Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
ERROR: LoadError: LoadError: UndefVarError: start not defined
Stacktrace:
  [1] getproperty(x::Module, f::Symbol)
    @ Base ./Base.jl:26
  [2] top-level scope
    @ ~/.julia/packages/Revise/Dpzsu/src/relocatable_exprs.jl:72
  [3] include(mod::Module, _path::String)
    @ Base ./Base.jl:386
  [4] include(x::String)
    @ Revise ~/.julia/packages/Revise/Dpzsu/src/Revise.jl:3
  [5] top-level scope
    @ ~/.julia/packages/Revise/Dpzsu/src/Revise.jl:20
  [6] include
    @ ./Base.jl:386 [inlined]
  [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1235
  [8] top-level scope
    @ none:1
  [9] eval
    @ ./boot.jl:360 [inlined]
[10] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
[11] top-level scope
    @ none:1
in expression starting at /Users/lewis/.julia/packages/Revise/Dpzsu/src/relocatable_exprs.jl:72
in expression starting at /Users/lewis/.julia/packages/Revise/Dpzsu/src/Revise.jl:3
ERROR: Failed to precompile Revise [295af30f-e4ad-537b-8983-00126c2a3abe] to /Users/lewis/.julia/compiled/v1.6/Revise/jl_FuChV0.
Stacktrace:
[1] error(s::String)
   @ Base ./error.jl:33
[2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY, ignore_loaded_modules::Bool)
   @ Base ./loading.jl:1385
[3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1329
[4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1043
[5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:936
[6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:923
```

From: Kristoffer Carlsson ***@***.***>
Reply-To: "timholy/Revise.jl" ***@***.***>
Date: Saturday, November 13, 2021 at 6:51 AM
To: "timholy/Revise.jl" ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [timholy/Revise.jl] Revise won't load on Mac M1 machines with Macos monterey (Issue #654)


Maybe something is holding it back. Try pkg> add ***@***.*** and see what it says.

**Comment by lewisl** [comment]
Ignore previous.

  1.  I think you meant ***@***.******@***.***>.
  2.  In any case, a newer version made it into the catalog: v3.1.20

Works perfectly.  Only needed a little more time for latest version.  Great work.

From: Kristoffer Carlsson ***@***.***>
Reply-To: "timholy/Revise.jl" ***@***.***>
Date: Saturday, November 13, 2021 at 6:51 AM
To: "timholy/Revise.jl" ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [timholy/Revise.jl] Revise won't load on Mac M1 machines with Macos monterey (Issue #654)


Maybe something is holding it back. Try pkg> add ***@***.*** and see what it says.
