### ISSUE TITLE
Behaviour of watch_file on FreeBSD is different

### ISSUE THREAD

**Issue by iblis17** [timholy/Revise.jl#66]
https://github.com/timholy/Revise.jl/blob/5754f39e17133b384913a7d05a44f377fcc174a6/src/Revise.jl#L188-L200

On FreeBSD modifying a existed file which located at `dir` will not being caught by `watch_dir(dir)`.

**Comment by timholy** [comment]
I don't have access to a FreeBSD system, so I might need some help with this one. I did a little [reading](https://forums.freebsd.org/threads/38162/). Can you check `kern.maxfiles`? If it's set to a low value then supporting FreeBSD is probably hopeless for anyone who doesn't have root access to their machine to change that setting.

**Comment by iblis17** [comment]
Here is mine

```
└─[iblis@gungnir]% uname -a
FreeBSD gungnir.nba.nctu.edu.tw 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
┌─[~]
| [-- INSERT --]
└─[iblis@gungnir]% sysctl kern.maxfiles
kern.maxfiles: 261113
┌─[~]
| [-- INSERT --]
└─[iblis@gungnir]% sysctl kern.maxfilesperproc
kern.maxfilesperproc: 234999
```
Different FreeBSD version
```
└─[iblis@abeing]% uname -a
FreeBSD abeing 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r323335: Sun Sep 17 00:56:35 CST 2017     root@abeing:/usr/obj/usr/src/sys/GENERIC  amd64     
┌─[~/git/TimeSeries]
| [Venv(py36)] [ master] [-- INSERT --]
└─[iblis@abeing]% sysctl kern.maxfiles                                                                                                            
kern.maxfiles: 522683                                                                                                                             
┌─[~/git/TimeSeries]
| [Venv(py36)] [ master] [-- INSERT --]
└─[iblis@abeing]% sysctl kern.maxfilesperproc                                                                                                     
kern.maxfilesperproc: 470412
```

**Comment by timholy** [comment]
It will be close, but perhaps possible:
```sh
~/.julia/v0.6$ find . -type f | wc -l
197127
```

**Comment by iblis17** [comment]
```
└─[iblis@abeing]% find . -type f | wc -l                                 
   67527                            
┌─[~/.julia/v0.6]                   
| [Venv(py36)] [-- INSERT --]       
└─[iblis@abeing]% find . -type f -name '*.jl' | wc -l                                                                                             
    2951
```

**Comment by iblis17** [comment]
Here are VM imagesm if you need: https://download.freebsd.org/ftp/releases/VM-IMAGES/

**Comment by timholy** [comment]
> But the number 197127 is the worst case, right?

Correct, but I think it applies to all processes on your system. See https://github.com/timholy/Revise.jl/issues/26#issuecomment-347646986.

**Comment by iblis17** [comment]
Any clue about implementation?
I can try to implement if you draw the picture of pseudo code.

**Comment by iblis17** [comment]
The days without `workspace` and `reload` make me anxious.

**Comment by timholy** [comment]
Sorry, I'm very busy on Julia Base with the push for 0.7-alpha, and didn't notice these pings. Having to first install a VM will also mean this won't be an easy fix for me to make.

This may not be too hard to fix because we used to watch individual files: see #22. You should be able to modify the watching code so that it checks for FreeBSD and if so uses a strategy that's more similar to the original one. I wouldn't try to do some kind of `git revert` though, because all kinds of stuff changed in between. Just check out the changes in #22 and then see if you can modify the current code accordingly.

I think the code is pretty well commented, but let me know if you have questions.
