### ISSUE TITLE
custom revise callback

### ISSUE THREAD

**Issue by Roger-luo** [timholy/Revise.jl#681]
I'm thinking if there is a way to solve this issue: https://github.com/comonicon/Comonicon.jl/issues/166

where a global constant dict that is used as a special method table
needs to be deleted when revise regenerate the code, which I guess can
be marked by the package author (in principle). So I'm wondering if there is a way to
do so using a callback. Anyone might know the answer?

**Comment by timholy** [comment]
Possibly https://github.com/timholy/Revise.jl/blob/d72d5c7c5a23ec913e5f8b1377ca43d619db55cd/src/callbacks.jl#L35-L48?

**Comment by timholy** [comment]
Since this appears in the docs (https://timholy.github.io/Revise.jl/stable/dev_reference/#Revise.add_callback) I think we can close this, but feel free to reopen if the existing support is inadequate.
