### ISSUE TITLE
Revise breaks on recursive struct definitions

### ISSUE THREAD

**Issue by IsaacRudich** [timholy/Revise.jl#683]
The MWE is tiny, but it took me ages to figure out:

```using Revise
struct Test
    test::Test
end
```

running `include("Test.jl")` on the above file twice in a row without changing anything returns:
ERROR: LoadError: invalid redefinition of constant Test

**Comment by Seelengrab** [comment]
I can't reproduce this, neither with `include` nor `includet`. The error suggests this is (was?) a julia issue, since you've used `include`, not the Revise specific version `includet`. Which julia and Revise versions are you on? 

It worked on this:

```
julia> versioninfo()
]Julia Version 1.9.0-DEV.614
Commit 0488abc625* (2022-05-24 15:28 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4

(@v1.9) pkg> st
Status `~/.julia/environments/v1.9/Project.toml`
  [6e4b80f9] BenchmarkTools v1.3.1
  [31a5f54b] Debugger v0.7.6
⌃ [c3a54625] JET v0.5.14
  [bf22376a] LIKWID v0.3.2
  [a81df072] MCAnalyzer v0.3.1
  [e4faabce] PProf v2.1.5
  [c46f51b8] ProfileView v1.5.1
  [295af30f] Revise v3.3.3
  [aa65fe97] SnoopCompile v2.9.1
Info Packages marked with ⌃ have new versions available
```

**Comment by IsaacRudich** [comment]
I was on Revise 3.3.3 and Julia 1.5.4, but I updated to 1.7.3 and it works so it must've been an older Julia problem. Sorry about that. I was unaware that revise had its own version of include though, I will be using that in the future.
