### ISSUE TITLE
Can't track changes in module loaded via "using ..Module"?

### ISSUE THREAD

**Issue by jochenkrattenmacher** [timholy/Revise.jl#692]
Hello!
I have a [Genie](https://github.com/GenieFramework/) app looking like this:

routes.jl:
```julia
using Genie.Router, Stipple, StipplePlotly #modules belonging to the Genie framework
using Presentations
```

Presentations.jl: (a file containing a local module I am working on)
```julia
module Presentations
using Stipple, StipplePlotly
```

This works fine with revise: If I update Presentations.jl, revise tracks the changes.

However, I found that my app loads much faster (45 sec versus 90 sec) when I use the following way of importing modules:

in routes.jl:
```julia
using Genie.Router, Stipple, StipplePlotly
include("src/Presentations.jl")
using ..Presentations
```

in Presentations.jl:
```julia
module Presentations
using ..Stipple, ..StipplePlotly
```

Unfortunately, revise does not work anymore with this setup. Do I need to live with the fact that I cannot have a fast startup time AND revise? Reorganizing my code into bigger modules would also work to reduce startup time by reducing the number of times I have to import stuff (while being able to keep revise), and I'll probably do it. However, it won't be as fast (I have to import the Genie framework at least twice), and arguably not as nice, so I am wondering whether I am missing something here.

Note: Omitting the include statement and writing "using Presentations" in routes.jl does not work (as I wrote [here](https://github.com/GenieFramework/Genie.jl/discussions/534))

Cheers

**Comment by jochenkrattenmacher** [comment]
So I have combined three of my modules, and used [@reexport](https://juliapackages.com/p/reexport) Stipple, StippleUI, StipplePlotly to make available these modules in both of my remaining modules without loading them twice. This doesn't seem that pretty to me, but it loads quickly, and revise works :) . 

I suppose this can be closed. Sorry for the inconveniences!

**Comment by timholy** [comment]
No inconvenience. You may be able to replace `include` with `includet` and get it to work. Let me know how it works out if you get a chance.

**Comment by jochenkrattenmacher** [comment]
Thanks! Unfortunately, `includet` only works in the REPL for me... (it doesn't actually include anything when called within a module).

I also tried 

```
include("Module.jl")
using .Module
Revise.track(Module)
```

in this case, one of two things happen: Either I get an error `no Revise.track recipe for module Moo` or there is no error (but tracking doesn't work). I am not quite sure why an error is only thrown sometimes, but it is reproducible: If Revise.track() is within my routes.jl file (from Genie 5.0), no error is thrown, however, if I create two very small modules, where module A tracks module B, then the error is thrown upon includet("Module B.jl") in the REPL

**Comment by t-bltg** [comment]
Can you try with `Revise@3.3.4` ?

**Comment by jochenkrattenmacher** [comment]
@t-bltg I tried today with Julia 1.8, Genie 5, and Revise 3.3.4

I would like to give a minimal working example but well when trying this I encounter the error message from above.

There is one more thing I am not sure about because well, I am a newbie: Since Genie includes Revise already as a dependency, I do not know exactly what I am doing when I add Revise to my repo and use it. And I do not know which Revise version is being shipped with Genie.

**Comment by t-bltg** [comment]
> And I do not know which Revise version is being shipped with Genie.

Maybe try something like: `println(Pkg.Operations.read_project(Pkg.Types.projectfile_path(pkgdir(Genie.Revise))).version)`

**Comment by jochenkrattenmacher** [comment]
```julia
julia> println(Pkg.Operations.read_project(Pkg.Types.projectfile_path(pkgdir(Genie.Loader.Revise))).version)
3.3.4
```

**Comment by jochenkrattenmacher** [comment]
I just want to note that I restructured my app, and I am no longer using routes.jl because I now start my Genie app with a script, which I include via calling "includet" in the REPL. Within the script itself, I include my module via includet as well:

```julia
includet("../src/Module.jl")
using .Module
```

This works well enough for me for the foreseeable future, as, again, I do not see a big need to split my module's code into several files/submodules (vscode regions work well enough).

**Comment by anke1460** [comment]
I have the same issues, my app is Genie 5.11.0. Julia 1.8.3
```
module A
include("B")
using .B
function test
  println("111")
end
end
```
```
model B
function foo
println("bbb")
end
```

if I changed module A code , the hot reload is works, but I change module B, it dose not works.

**Comment by jochenkrattenmacher** [comment]
Maybe I should say that I did something which really helped:
I now develop "Presentations.jl" as a package (via the "dev" command of the package manager). With this, I can develop the package as I like (include files via "include", and import modules from the imported files via ".."), and Revise tracks the changes splendidly.

**Comment by untoreh** [comment]
put `__revise_mode__ = :eval` inside the top module 
```julia
module A
__revise_mode__ = :eval
include("abc.jl")
end
```
- comment include statements `# include("abc.jl")`
- call revise()
- uncomment 
- call revise()

Now It should start tracking changes inside the included files

**Comment by timholy** [comment]
I've tested a setup that is similar to https://github.com/timholy/Revise.jl/issues/692#issuecomment-1321127336. To be completely explicit:

```sh
tim@diva:~/tmp/Genie$ ls
A  Manifest.toml  Project.toml
tim@diva:~/tmp/Genie$ ls A
Project.toml  src
tim@diva:~/tmp/Genie$ ls A/src
A.jl  B.jl
tim@diva:~/tmp/Genie$ cat A/src/A.jl
module A
include("B.jl")
using .B
function test()
  println("111")
end
end
tim@diva:~/tmp/Genie$ cat A/src/B.jl
module B
function foo()
    println("bbb")
end
end
```

Revise seems to work just fine in Revising B. I'll close this, but I can reopen it if someone provides a minimal working example.
