### ISSUE TITLE
Requires latency due to Revise

### ISSUE THREAD

**Issue by johnnychen94** [timholy/Revise.jl#702]
```julia
julia> @time using Requires
  0.007453 seconds (9.04 k allocations: 706.047 KiB)

# in a new Julia session
julia> using Revise

julia> @time using Requires
  0.248279 seconds (16.28 k allocations: 907.938 KiB, 97.48% compilation time)
```

This seems due to the [Requires notification callback](https://github.com/JuliaPackaging/Requires.jl/blob/542a641b633fa38a5950c2b1dbb90861967c7015/src/require.jl#L15). Given that Revise is loaded by default in many situations, many small packages might hit this 0.24s overhead, e.g.,

```julia
julia> @time using Ratios
# with Revise: 0.276081 seconds (41.21 k allocations: 2.392 MiB, 92.99% compilation time: 1% of which was recompilation)
# without Revise: 0.029011 seconds (34.23 k allocations: 3.354 MiB, 30.99% compilation time: 16% of which was recompilation)
```

Any chance to improve this package loading latency issue?

**Comment by timholy** [comment]
It only affects the first Requires-using package. AFAICT there's no inference running, just LLVM compilation. I don't think there's a way to fix it until we can cache native code. I've deliberately placed the most-expensive-to-compile calls behind a `Base.invokelatest` to prevent them from being compiled until you actually load Requires.

**Comment by johnnychen94** [comment]
Looking forward to the new pkg image solution proposed in the juliacon!

**Comment by timholy** [comment]
Me too! :laughing:
