### ISSUE TITLE
Anonymous functions

### ISSUE THREAD

**Issue by Keno** [timholy/Revise.jl#72]
Revise currently doesn't handle anonymous functions changing, e.g.
```
module TestPrint
f = ()->println("Hello")
end
```
Changing the printed string will not revise properly. This makes some sense, because it's not necessarily clear how updates to the text affect anonymous functions. However, I think one could do a fairly decent job by performing an AST diff and if the anonymous functions appears in the same place in the AST as a previous anonymous function, update the code accordingly.

**Comment by timholy** [comment]
Yep, this is an interesting case. I assume you don't mean "same line number" but really "same predecessor/successor." That could cause trouble if one of those lines got edited too, of course.

If nothing else I should add this to the list of things Revise doesn't handle.

**Comment by Keno** [comment]
> I assume you don't mean "same line number" but really "same predecessor/successor." That could cause trouble if one of those lines got edited too, of course.

Right, just some heuristic like if
```
f = ...
```
appears in the AST assume that was supposed to be the same.

**Comment by timholy** [comment]
I just tested this myself and it seems to be working for me when I test it at the REPL. Can you give a more complete example?

**Comment by timholy** [comment]
Seems to work now.
