### ISSUE TITLE
UndefVarError: invoked_get! not defined

### ISSUE THREAD

**Issue by charnik** [timholy/Revise.jl#727]
Hi there! Ever since I updated Revise to the latest version (v3.5 that is), I've been getting errors after making even the smallest/most trivial of changes to the source code. The source code is private but I can share the exception thrown by Revise in case it is helpful.
```
┌ Error: 2023-01-16T19:09:48.968
│ Failed to revise /Users/charnik/.../src/file.jl
│   exception =
│    UndefVarError: invoked_get! not defined
│    Stacktrace:
│     [1] top-level scope
│       @ ~/.julia/packages/AutoHashEquals/tDuUH/src/AutoHashEquals.jl:81
│    Revise evaluation error at /Users/charnik/.../.julia/packages/AutoHashEquals/tDuUH/src/AutoHashEquals.jl:81
│
└ @ Revise ~/.julia/packages/Revise/VRgaS/src/packagedef.jl:714
┌ Warning: 2023-01-16T19:09:49.019
│ The running code does not match the saved version for the following files:
│
│   /Users/charnik/.../src/file.jl
│
│ If the error was due to evaluation order, it can sometimes be resolved by calling `Revise.retry()`.
│ Use Revise.errors() to report errors again. Only the first error in each file is shown.
│ Your prompt color may be yellow until the errors are resolved.
└ @ Revise ~/.julia/packages/Revise/VRgaS/src/packagedef.jl:824
```
This seems to be related to [this line](https://github.com/timholy/Revise.jl/blame/8f1552ee61bdec67f8e9d60890fe5fd4560e512c/src/packagedef.jl#L418).

Many thanks in advance!

**Comment by KristofferC** [comment]
It seems this requires CodeTracking 1.2.0. What version of CodeTracking.jl are you on.

As a side note, putting this into a package feels to me a bit overkill, might as well just define it where you use it.

**Comment by timholy** [comment]
What's strange is that Revise 3.5 requires CodeTracking 1.2.

**Comment by timholy** [comment]
> As a side note, putting this into a package feels to me a bit overkill, might as well just define it where you use it.

Perhaps true. I didn't want to violate the ability of CodeTracking to maintain its own data structures, but you're not wrong...

**Comment by charnik** [comment]
Thank you @KristofferC and @timholy ! Indeed, I didn't even have CodeTracking installed.
Would it make sense to have Revise check whether CodeTracking is installed at least?

**Comment by NHDaly** [comment]
Yeah, @charnik: That's what tim was saying here:

> What's strange is that Revise 3.5 requires CodeTracking 1.2.

It is weird that this isn't being installed automatically.. 🤔

**Comment by KristofferC** [comment]
Could be environment stack shenanigans or something:

```
(@v1.9) pkg> add Revise@3.5 CodeTracking@1.1
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Revise [295af30f]:
 Revise [295af30f] log:
 ├─possible versions are: 0.2.0-3.5.0 or uninstalled
 ├─restricted to versions 3.5 by an explicit requirement, leaving only versions: 3.5.0
 └─restricted by compatibility requirements with CodeTracking [da1fd8a2] to versions: [0.2.0-1.0.3, 3.0.0-3.4.0] or uninstalled — no versions left
   └─CodeTracking [da1fd8a2] log:
     ├─possible versions are: 0.1.0-1.2.0 or uninstalled
     └─restricted to versions 1.1 by an explicit requirement, leaving only versions: 1.1.0-1.1.2
```

**Comment by NHDaly** [comment]
Aha, @KristofferC that's exactly what's happening.

We have `Revise` installed in our top-level `1.8` environment, like good citizens, so that it doesn't pollute our project.
But our project has this dependency in its manifest:
```
  [da1fd8a2] CodeTracking v1.1.2
```
So then I guess when we start julia as `julia --proj=.`, and then our `startup.jl` has `using Revise` in it, we end up import Revise from within the active project, and even though Revise is being pulled from the top-level env, the project is allowed to change the version of one of the deps that Revise needs?

That's a tricky bug!

What should we do about that? Obviously the issue isn't in Revise, so this is the wrong repo for it, but this seems like an issue with Pkg... Maybe it should complain that we cannot import `Revise`, since our current manifest pins one of its dependencies to an incompatible version??

**Comment by timholy** [comment]
https://github.com/JuliaLang/julia/issues/35663

**Comment by NHDaly** [comment]
Aha. Thanks Tim.

So i've skimmed the issue. Is there any good recommended guidance for what _we_ should do in the meantime?
Just make sure we update our project's manifest to use a version of CodeTracking that keeps Revise happy?

**Comment by timholy** [comment]
I think the Julia bug is fixable now, given that I think we now store version numbers of loaded packages.
