### ISSUE TITLE
`redefinition of constant` bug when using `@require`

### ISSUE THREAD

**Issue by t-bltg** [timholy/Revise.jl#736]
Reduced case for https://github.com/JuliaPlots/UnicodePlots.jl/issues/334, code available here: https://github.com/t-bltg/Ext.jl.

On `julia` versions < 1.9 (this bug does not occur on `1.9.0-betaX`):

**without Revise**
```julia
julia> VERSION
v"1.8.5"
julia> using FreeType
julia> using Ext
Ext __init__
FreeTypeExt include
FreeTypeExt __init__
```

**with Revise**
```julia
julia> VERSION
v"1.8.5"
julia> using Revise
julia> using FreeType
julia> using Ext
Ext __init__
FreeTypeExt include
FreeTypeExt __init__
FreeTypeExt include
WARNING: redefinition of constant VALID_FONTPATHS. This may fail, cause incorrect answers, or produce other errors.
```

Note that when using `Revise`, `include` is called twice on the extension module while `__init__` only once, causing redefinition warnings and errors in the full `UnicodePlots` report.

**Comment by timholy** [comment]
On Julia 1.10, with current versions of Revise (3.5.11) & LoweredCodeUtils (2.4.2), I can't replicate this.

**Comment by t-bltg** [comment]
Yes, this nug only occurs on versions `< 1.9`.

Thanks, I think we can probably close this issue now.
