### ISSUE TITLE
Duplicate functions can confuse `Revise`

### ISSUE THREAD

**Issue by rikhuijzer** [timholy/Revise.jl#750]
It looks like defining duplicate functions and then modifying one, can lead to an out-of-date definition:

To reproduce, define the following module:
```julia
module M

struct A end
struct B end
foo(::Type{A}) = 1
foo(::Type{A}) = 2

end
```
now:
```julia
julia> M.foo(M.A)
2
```
This is correct. However, if we change the second definition, the output is incorrect:
```julia
module M

struct A end
struct B end
foo(::Type{A}) = 1
foo(::Type{B}) = 2

end
```
now:
```julia
julia> M.foo(M.A)
2
```
whereas the output should be `1` since `foo(::Type{A}) = 1`.

This issue looks similar to https://github.com/timholy/Revise.jl/issues/249. I think the root cause is different, but apologies if it is actually the same. Then, feel free to close this issue

**Comment by timholy** [comment]
This is indeed #249 and it's not really fixable.
