### ISSUE TITLE
Revise fails tracking when editing file from different cluster nodes

### ISSUE THREAD

**Issue by haakon-e** [timholy/Revise.jl#752]
I work on a project on a remote cluster that I ssh into. The cluster uses slurm for job management.
After I have connected my VSCode window to the remote project, I often use e.g. `srun [...] --time=04:00:00 --pty bash -i` in the terminal to request dedicated resources for a julia REPL session. This allocates resources on one of hundreds of nodes we have available on the cluster.

I also use Revise to track changes I make to the project while working in REPL. It appears that if I make edits (using e.g. vim or vscode) to my `dev`'d project from a _different_ node than the node where my Julia session (with Revise) runs, then these edits are not seen by Revise.
If I then open said edited file using vim on the same node, I will see the edits. If I save and close the file (from the node where julia is running), then Revise sees the edits and does the correct thing.

I hope this issue made sense, and I'm happy to provide clarifications.

<details><summary>version info</summary>

```julia
(v1.9) pkg> st
Status `/abc/.julia/environments/v1.9/Project.toml`
  [295af30f] Revise v3.5.3
  [....]

julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake-avx512)
  Threads: 1 on 32 virtual cores
Environment:
  JULIA_CUDA_USE_BINARYBUILDER = false
  LD_LIBRARY_PATH = [...]
  JULIA_NUM_THREADS = 1
  LD_RUN_PATH = [...]
```

</details>

**Comment by KristofferC** [comment]
https://timholy.github.io/Revise.jl/stable/config/#Polling-and-NFS-mounted-code-directories:-JULIA_REVISE_POLL-1 might be of use.

**Comment by timholy** [comment]
Polling is the answer here.
