### ISSUE TITLE
support julia extension

### ISSUE THREAD

**Issue by kongdd** [timholy/Revise.jl#756]
Taking the package `Rasters.jl` as an example, Revise unable to automatically reload functions in ext. 

Without Revise, it is really hard to debug functions.

## References:
1. <https://github.com/rafaqz/Rasters.jl/blob/main/ext/RastersHDF5Ext/smap_source.jl>

**Comment by KristofferC** [comment]
Revise already works with extensions:

```
julia> using Revise

julia> using Rasters

julia> using HDF5

julia> ext = Base.get_extension(Rasters, :RastersHDF5Ext)
RastersHDF5Ext

julia> ext.foo
ERROR: UndefVarError: `foo` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ REPL[5]:1

< Updating source code in extension to define foo here>

julia> ext.foo
3
```

**Comment by kongdd** [comment]
This is awesome. Thank u.

**Comment by KristofferC** [comment]
Didn't you try this before opening an issue? What was the problem?
