### ISSUE TITLE
Can it be that revise does not track functions under invokelatest?

### ISSUE THREAD

**Issue by schlichtanders** [timholy/Revise.jl#775]
Hi, I am using Revise and have a nested setup, a package calling another package, both dev-ed by me. The second spawns a  HTTP server where all the functionality is called.

- While Revise seamingly always updates the outer calling package
- it seems to have difficulties updating changes to the nested package

I couldn't replicate it with a simple package nesting and now have the thought it might be a complex interaction between something like nested dev packages and an invokelatest which complicates the revelation of dependencies

**Comment by fredrikekre** [comment]
I have used a similar setup in the past without problems, so I think you have to present an MWE.

**Comment by schlichtanders** [comment]
Thank you for your comment. It is always good to know that things should work.
It is really annoying when I cannot rely on hot-reloading ;-) but it is also so hard to create a MWE example (the first attempt was not successful)

I will keep this issue updated if I am successful

**Comment by schlichtanders** [comment]
I have astonishingly weird and not-understandable revising-problems. While it is still super difficult to reproduce it in form of a MWE, if the updating fails, it is doing so in a stable manner (so that I need to restart julia). 

If someone from Revise would like get pinged if this happens, we could take a look together (Even without NDA ;-) ).

**Comment by schlichtanders** [comment]
Can it be that Revise does not handle paths with spaces well?

**Comment by schlichtanders** [comment]
This is super weird... even a direct
```
@eval BuggyModule function functionname()
    # fixed version
end
```
Is not picked up.

I really don't know how this can be, how the new function definition is not picked up...

**Comment by pfitzseb** [comment]
Any chance that something caused two modules of the same name to be created? So your new reference to `BuggyModule` is not actually what's used in your server?

**Comment by KristofferC** [comment]
If you are doing something like

```
f() = println("Hello")

function run_server()
    while true
        f()
        sleep(1)
    end
end

@async run_server()

f() = println("World")
```

you need to change that to `@invokelatest f()` in `run_server` for new definitions to get picked up.

**Comment by KristofferC** [comment]
> This indicates that it really has something todo with the update logic.

The fact that it doesn't work with `@eval` means that it is also likely not related to Revise. I think a full MWE here is needed to make progress.

**Comment by schlichtanders** [comment]
> > This indicates that it really has something todo with the update logic.
> 
> The fact that it doesn't work with `@eval` means that it is also likely not related to Revise. I think a full MWE here is needed to make progress.

I understand your thought. But it could also be that revise is creating the two versions of the same Module and then every @eval would of course not work.

Some further steps I tried:
- I tried renaming the file to not include whitespace, but it still occurs (but I also haven't restarted Julia, so it can still be something initially triggered by whitespace but then resistant to whitespace)
- I @eval the surround method calling the one I @eval initially without success and out of a sudden all changes appear... This truly feels like black magic. I hope I don't get crazy :grin:

**Comment by KristofferC** [comment]
> But it could also be that revise is creating the two versions of the same Module and then every `@eval` would of course not work.

I mean, `@eval` into a module completely without using Revise should also work (that is pretty much what Revise ends up doing). So if that doesn't work, there is something else.

**Comment by schlichtanders** [comment]
> > But it could also be that revise is creating the two versions of the same Module and then every `@eval` would of course not work.
> 
> I mean, `@eval` into a module completely without using Revise should also work (that is pretty much what Revise ends up doing). So if that doesn't work, there is something else.

I still need to test this. Currently I am only falling back to @eval if revise does not work. Hence I really need to create test setup without Revise and use `@eval` there. It is a bit more effort, I guess I will be motivated enough to test this over the next days.

**Comment by schlichtanders** [comment]
bad news for me:

I now started Julia **without** Revise and have the very same behaviour: @eval a new version of one function does not get picked up, but as soon as the surrounding function is also @evaled a new version, also the inner change is picked up...

Any help about how I can debug this further is highly appreciated.

**Comment by KristofferC** [comment]
> Any help about how I can debug this further is highly appreciated.

I would try minify it as much as possible (while having the problem still occur) and then post the code that reproduces it here.

**Comment by timholy** [comment]
This does not appear to be a Revise issue. (Revise does not create modules.)
