### ISSUE TITLE
Solved: Revise does not work on linux 

### ISSUE THREAD

**Issue by j-fu** [timholy/Revise.jl#778]
I quite often encountered a situation that Revise.jl somehow ceased to work. No errors messages, nothing besides revise not working - see e.g. https://github.com/fonsp/Pluto.jl/issues/2094 .
Testing Revise appears to reliably detect this situation.

Tests look like
```
File paths: Test Failed at /home/fuhrmann/.julia/packages/Revise/xRltd/test/runtests.jl:511
Expression: pcwf1() == -1
Evaluated: 1 == -1

Stacktrace:
[1] top-level scope
@ ~/local/julia/julia-1.9.4/share/julia/stdlib/v1.9/Test/src/Test.jl:478
[2] eval(m::Module, e::Any)
@ Core ./boot.jl:370
[3] macro expansion
@ ~/.julia/packages/Revise/xRltd/test/runtests.jl:511 [inlined]
[4] macro expansion
@ ~/local/julia/julia-1.9.4/share/julia/stdlib/v1.9/Test/src/Test.jl:1498 [inlined]
[5] macro expansion
@ ~/.julia/packages/Revise/xRltd/test/runtests.jl:412 [inlined]
[6] macro expansion
@ ~/local/julia/julia-1.9.4/share/julia/stdlib/v1.9/Test/src/Test.jl:1498 [inlined]
[7] top-level scope
@ ~/.julia/packages/Revise/xRltd/test/runtests.jl:72
File paths: Test Failed at /home/fuhrmann/.julia/packages/Revise/xRltd/test/runtests.jl:518
Expression: using_macro_pcwf() == -6
Evaluated: 6 == -6
```

In another round of digging I learned that Revise is tracking files using file system tools and  about the "inotify limits". I found a quite good explanation [here](https://github.com/fonsp/Pluto.jl/issues/2094). On my system (openSUSE Leap 15.5) these limits are by default:
```
$ sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 524288
```
Increasing  `fs.inotify.max_user_instances` immediatly fixes the problem.
E.g. after setting
```
sudo sysctl fs.inotify.max_user_instances=2048
```
Revise unit tests immediately start to work. This also can be made [permanent](https://www.suse.com/de-de/support/kb/doc/?id=000020048).

I could create a documention PR  on this.

**Comment by timholy** [comment]
Fixed by #779
