### ISSUE TITLE
Error with module docstring

### ISSUE THREAD

**Issue by cstjean** [timholy/Revise.jl#8]
MWE, Julia 0.6:
```julia
""" Ahoy """
module FormulaBase  # in FormulaBase.jl

include("matching.jl")   # matching.jl can contain anything (even empty file)
blag() = 10000

end # module
```

```julia
julia> using Revise

julia> using FormulaBase

julia> FormulaBase.blag()
1000

#### change the blag return value

julia> FormulaBase.blag()
WARNING: replacing module FormulaBase
WARNING: failure to evaluate changes in Main
Core.@doc " Hey " module FormulaBase # /Users/cedric/Programa/RL/FormulaBase.jl, line 2: # /Users/cedric/Programa/RL/FormulaBase.jl, line 5:
    include("matching.jl") # /Users/cedric/Programa/RL/FormulaBase.jl, line 8:
    blag() = begin  # /Users/cedric/Programa/RL/FormulaBase.jl, line 8:
            10000
        end
    end
ERROR: UndefVarError: blag not defined
```

Unrelated question: how do you manage to keep the file info correct in the stack traces? In my own package, I can get the line number right, but the stack trace shows `foo(::Int64) at ./none:5`. Is it `add_filename!`?

**Comment by cstjean** [comment]
> Is it `add_filename!`?

Yes it is, thank you!

**Comment by timholy** [comment]
> in my own package

Hmm, with this hint I just discovered ClobberingReload.jl. Sorry I didn't discover that earlier, since it sounds like we use similar strategies.

Thanks for the bug report! I'm on vacation now but will see what I can do.

**Comment by cstjean** [comment]
No worries, glad to see someone found a solution that works for the REPL!
