### ISSUE TITLE
Incomplete docs for `track`

### ISSUE THREAD

**Issue by MasonProtter** [timholy/Revise.jl#804]
The [docstring for `includet` says](https://timholy.github.io/Revise.jl/stable/user_reference/#Revise.includet) 
> `includet` is deliberately non-recursive, so if filename loads any other files, they will not be automatically tracked. (See [Revise.track](https://timholy.github.io/Revise.jl/stable/user_reference/#Revise.track) to set it up manually.)

but then the docstring for `track` doesn't give any relevant information on how it can be used to do recursive tracking.

**Comment by timholy** [comment]
I'm not even sure what I meant by that comment! Maybe that you can retrospectively start tracking on files that you've already `include`d?
