### ISSUE TITLE
Putting revise in `atreplinit()` leads to error on julia v1.11 - InitError

### ISSUE THREAD

**Issue by kescobo** [timholy/Revise.jl#812]
On previous version of julia, I have the following in my startup.jl:

```
atreplinit() do repl
    # other stuff
    @eval using Revise
    # more stuff
end
```

This has worked fine, but on julia v1.11.0-beta1, I'm getting 

```
InitError: UndefRefError: access to undefined reference
during initialization of module REPLExt
```

I've isolated it to the `@eval Revise` inside `atreplinit()` - removing that line clears the error, and removing everything else still has the error.

I **do not** get the error and everything works fine if I do `using Revise` outside of `atreplinit()`, nor if I put `@eval using Revise` inside a `try` block.

I don't remember why I put it inside `atreplinit()` in the first place, so maybe this isn't actually a problem. But it's a different behavior than previously, so I thought I'd raise it.

**Comment by timholy** [comment]
This was necessary in much older versions of Julia, and the Revise docs recommended it, which is probably why that was in your `startup`. But the new recommendation https://timholy.github.io/Revise.jl/stable/config/#Using-Revise-by-default has been there for many releases now. REPLExt is a Julia/Pkg thing, not a Revise thing, so I don't think there's anything Revise can/should do about this.

Thanks for leaving the breadcrumbs! It seems likely to help others (and may already have).
