### ISSUE TITLE
Revising modules on multiple workers/processes

### ISSUE THREAD

**Issue by pasha2718** [timholy/Revise.jl#82]
Hi, and thank you for Revise.jl.

Really there are two issues here.

The thing I really want is to have mypkg Revised on all of the Julia workers as well.  That doesn't happen with either of my below scenarios.  I have tried `@everywhere using mypkg` and `@everywhere using Revise` but no dice.    This makes for a long restart process.  Any suggestions on how to achieve this multi-process revise?

As far as process 1 is concerned, it appears that Revise will not update a local module when Julia is started with -p procs.  Interestingly Revise will notice updates when procs were added with addprocs().

Successful operation:
- Start `julia`
- run `using mypkg` 
- run `f()` from mypkg and get baseline output
- edit source code  to mypkg - add an `info("test1")`
- run `f()` from mypkg and see the new info line test1
- run `addprocs(2)` to add two worker processes
- edit source code  to mypkg - add an `info("test2")`
- run `f()` from mypkg and see the new info line test2

Error replication:
- Start `julia -p 2`
- run `using mypkg` 
- run `f()` from mypkg and get baseline output
- edit source code  to mypkg - add an `info("test1")`
- run `f()` from mypkg and fail to see the new info line test1

My Julia versioninfo, running on latest Arch:

```
Julia Version 0.6.2
Commit d386e40 (2017-12-13 18:08 UTC)
Platform Info:
	OS: Linux (x86_64-pc-linux-gnu)
	CPU: AMD Opteron(TM) Processor 6276
	WORD_SIZE: 64
	BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Bulldozer)
	LAPACK: libopenblas
	LIBM: libm
	LLVM: libLLVM-3.9.1 (ORCJIT, bdver1)
```

**Comment by timholy** [comment]
OK, see #82. It's only on 0.7, but you're welcome to steal bits and submit a PR against the `v0.6` branch.
