### ISSUE TITLE
Unable to Revise a package using ParallelStencil.jl

### ISSUE THREAD

**Issue by jdm204** [timholy/Revise.jl#821]
Hi, Revise is brilliant. I've ran into an issue revising package code that uses ParallelStencil.

ParallelStencil provides macros such as `@parallel` to annotate functions with, but before these annotations can be used, an initialisation macro must be run first, so I have this at the top level of my package:

```
using ParallelStencil
@init_parallel_stencil(Threads, Float64, 3);
```

before including other files with `@parallel` calls.

My development workflow involves activiating `MyPackage` environment, `using MyPackage`, and then testing out bits of code in the REPL, editing the package, Revise reloads, back to the REPL, etc.

The problem is, this workflow breaks when using Revise and ParallelStencil in combination, as upon the first code change in the session (not necessarily to any ParallelStencil-involved code), Revise does its thing, but I get an error:

```
NotInitializedError: no ParallelStencil macro or function can be called before @init_parallel_stencil in each module (missing call in MyPackage)
```
That I didn't call the init macro, despite it appearing before any other ParallelStencil macros in my package.

CC @omlins who thought this might be a Revise issue

**Comment by timholy** [comment]
This does seem like a Revise bug. Can you give me a MWE?

**Comment by timholy** [comment]
This is not a Revise issue. Put `@init_parallel_stencil(Threads, Float64, 3)` into an `__init__()` function in CancerCellModels.

The fundamental issue is that a package's `src/*.jl` files are best thought of as *build scripts*, and precompilation stores a snapshot of the resulting module. But ParallelStencil maintains its own [storage](https://github.com/omlins/ParallelStencil.jl/blob/936ddae00c607c1ec9a07bc615a36a0a53aa9291/src/init_parallel_stencil.jl#L77-L81) for all relevant settings (it's not local to the module being compiled). During precompilation of CancelCellModels, all the important settings get stored in ParallelStencil, but ParallelStencil is not the one being compiled so those settings are discarded when the process doing the precompilation of CancerCellModels shuts down. Thus, with the current design of ParallelStencil, you'll have to repeat that work when CancerCellModels first gets loaded, and that's the job of `__init__`.
