### ISSUE TITLE
Add force_revise function to handle delayed updates on NFS when using JULIA_REVISE_POLL=1

### ISSUE THREAD

**Issue by danielalcalde** [timholy/Revise.jl#842]
Revise does not always update package files on NFS when setting JULIA_REVISE_POLL=1, in particular sometimes it takes a few minutes for the changes to take effect automatically.

I have been using a workaround for a while and think it would be a great addition to the package, for systems where julias `poll_file` works poorly. This is the workaround:

```
function force_revise(mod)
    id = Revise.PkgId(mod)
    pkgdata = Revise.parse_pkg_files(id)
    files = Revise.srcfiles(pkgdata)
    for file in files
        file = joinpath(Revise.basedir(pkgdata), file)
        push!(Revise.revision_queue, (pkgdata, relpath(file, pkgdata)))
    end
end
``` 
If you think it makes sense I can add it in a PR.

**Comment by frankier** [comment]
Related: https://github.com/timholy/Revise.jl/issues/839
