### ISSUE TITLE
Revise causes method ambiguity

### ISSUE THREAD

**Issue by rafaqz** [timholy/Revise.jl#843]
This doesn't always happen immediately or at all so isn't easy to MWE. It seems to depend on code load order or something after editing a file.

But using Revise with DimensionalData after editing a file I regularly get ambiguity errors for `similar` that are not there without Revise.

DimensionalData.jl has some overly complicated `similar` dispatch to handle axes returning DimUnitRange to reconstruct `DimArray` rather than array.  Maybe some of this code being inside `@eval` blocks in a loop could cause problems?

https://github.com/rafaqz/DimensionalData.jl/blob/2a11716df4f820b01debb606f11f65600226118c/src/array/array.jl#L143-L240

**Comment by timholy** [comment]
Do you use vim by any chance? I wonder if this could be #841? Perhaps the best approach would be to dump the output of `methods(similar)` to a file and then see if you can figure out what changed.

**Comment by rafaqz** [comment]
Yes, vim! That looks like the problem

**Comment by timholy** [comment]
Interesting that you can trigger this by "ordinary usage" rather than via `entr`. You must be a keyboard Olympic athlete to save a file and execute the next REPL command faster than vim can save a file 😮.

**Comment by rafaqz** [comment]
Maybe that could happen in some fraction of a second? it's three key strokes to send a line to julia after hitting `:w`to dave

**Comment by rafaqz** [comment]
Also I use nvim these days, to complicate the fix...

**Comment by timholy** [comment]
Any chance you can try `backupcopy=yes` in your nvim settings to test whether that works? Just while waiting for https://github.com/vim/vim/issues/15733 to resolve.

**Comment by rafaqz** [comment]
Seems fixed so far
