### ISSUE TITLE
Revise doesn't get triggered in IJulia

### ISSUE THREAD

**Issue by cstjean** [timholy/Revise.jl#9]
I believe the typical way of setting it up is with:
```julia
        try # to avoid requiring IJulia
            Main.IJulia.push_preexecute_hook(check_for_revision)
        end
```

**Comment by timholy** [comment]
My Jupyter doesn't offer a 0.6 kernel, do you know how to get one?

**Comment by timholy** [comment]
Oh, haha, I had a confusing symlink in my `~/bin` directory...
