### ISSUE TITLE
In README, change .juliarc.jl to ~/.julia/config/startup.jl

### ISSUE THREAD

**Issue by dlfivefifty** [timholy/Revise.jl#95]

**Comment by nstiurca** [comment]
I just had to figure this out for myself as well.

**Comment by timholy** [comment]
Good catch. FYI these are very easy as a PR: in your browser, just select the README.md file from the list of files, then click the pencil icon and you can edit right in your browser. It's sometimes easier than filing an issue :smile:.

**Comment by dlfivefifty** [comment]
Good point. I didn’t realise I can do that on repos  I’m not a collaborator on.
